silx-kit/h5web

- src/demo-app/mock-data/metadata.json
- src/demo-app/mock-data/models.ts
- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/Icon.tsx
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/hooks.ts
- src/h5web/providers/models.ts
- src/h5web/providers/type-guards.ts
- Add interfaces for HDF5 shape, type, attributes, etc.
- Rename interface used to type a mocked JSON metadata file from `HDF5Metadata` to `MockHDF5Metadata`, since this interface won't be used to type the data returned from HSDS.
> Review metadata models

- README.md
- package.json
- src/h5web/explorer/utils.test.ts
Turns out ESLint and Jest don't type-check, so tests were not being type-checked. I've added a script to type-check the whole project. It's faster than running `npm run build`, so it will be useful for continuous integration.
> Fix typing error in tests and improve linting script

- src/h5web/App.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/hooks.ts
Mock data retrieval is now abstracted out in custom hooks, which will make  adding the network layer easier.
> Note that the filename is still hardcoded for now.
> Move data retrieval for Explorer in custom hook

- src/demo-app/DemoApp.tsx
- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/SilxProvider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hooks.ts
This PR adds a [React Context](https://reactjs.org/docs/context.html) called `DataProviderContext`. This context can hold an object of type `DataProvider` composed of three methods to encapsulate three data retrieval operations: `getMetadataTree`, `getEntity` and `getValues`.
In order to provide data, one must provide implementations of these methods and wrap the app with the context's provider:
```tsx
<DataProviderContext.Provider value={impl}>
<App />
</DataProviderContext.Provider>
```
`SilxProvider` is one such implementations that will be used to retrieve data from silx.org/pub/h5web
> Add data provider SilxProvider, available through context

- src/h5web/App.tsx
- src/h5web/explorer/Explorer.module.css
- src/h5web/explorer/Explorer.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hooks.ts
- src/h5web/providers/silx/SilxProvider.tsx
- src/h5web/providers/silx/api.ts
Also, display domain passed to `<Silx>` data provider instead of mocked filename.
> Load real data from silx.org

- src/h5web/metadata-viewer/LinkInfo.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/models.ts
- src/h5web/providers/silx/SilxProvider.tsx
- src/h5web/providers/silx/utils.test.ts
- src/h5web/providers/silx/utils.ts
- Add component `LinkInfo` to display metadata for a `link`
- Add a new type to represent the root link, `HDF5RootLink`, with a custom class, `H5WEB_ROOT`, to make it clear that this is not a class of link defined by the HDF5 spec.
- Don't show the title and class info for the root link, as this doesn't make sense.
> Display link metadata

- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.module.css
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hooks.ts
- src/h5web/providers/silx/SilxProvider.tsx
I think it makes more sense to pass a valid dataset to the visualizer rather than a link. In `App.tsx`, `selectedDataset` is now of type `HDF5Entity<HDF5Collection.Datasets>`, which is more logicial and means we don't have to re-check that the corresponding entity is indeed a dataset inside `DatasetVisualizer`.
> Pass dataset instead of link to DatasetVisualizer

- src/h5web/providers/context.ts
- src/h5web/providers/hooks.ts
- src/h5web/providers/models.ts
- src/h5web/providers/silx/SilxProvider.tsx
- src/h5web/providers/silx/models.ts
It's just an alias for `any` to avoid having to disable ESLint warnings everywhere.
> Add HDF5Value model

- package-lock.json
- package.json
- src/h5web/App.module.css
- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.module.css
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/TableVis.tsx
Uses `react-window` for virtualization and works smoothly with one-million-point datasets!
> First implementation disclaimer: there's no styling, the columns have a fixed width, and the visualization appears only for datasets with a basic type and a simple shape with 1 or 2 dimensions.
> Implement table visualization

- package-lock.json
- package.json
- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/dataset-visualizer/utils.ts
- src/h5web/dataset-visualizer/vis/MatrixVis.tsx
- src/h5web/metadata-viewer/EntityInfo.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/metadata-viewer/RawInspector.tsx
- src/h5web/providers/hooks.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/models.ts
- src/h5web/providers/silx/api.ts
- src/h5web/providers/silx/models.ts
- src/h5web/providers/utils.test.ts
- src/h5web/providers/utils.ts
Review the models so that entities are persisted with `collection` and `id` properties directly (instead of adding these properties dynamically in the `useEntity` hook).
> Store entities with `collection` and `id`

- src/h5web/App.module.css
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/dataset-visualizer/VisSelector.tsx
- src/h5web/dataset-visualizer/models.ts
- src/h5web/dataset-visualizer/utils.test.ts
- src/h5web/dataset-visualizer/utils.ts
- src/h5web/dataset-visualizer/vis/MatrixVis.module.css
- src/h5web/dataset-visualizer/vis/ScalarVis.module.css
- src/h5web/dataset-visualizer/vis/ScalarVis.tsx
- src/h5web/providers/utils.ts
- src/index.tsx
- src/styles/base.css
- src/styles/index.css
- src/styles/vars.css
The Raw visualization was showing double quotes around scalar values, and backslashes in stringified JSON values. This is much more readable:
> Implement Scalar visualization

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/Mesh.tsx
I tried using Three's [OrbitControls](https://threejs.org/examples/?q=orbit#misc_controls_orbit) ([doc](https://threejs.org/docs/#examples/en/controls/OrbitControls)) but it's not quite our use case - we don't want to orbit the camera around an object. I got zoom and pan (screen pan, not target pan) working but I couldn't restrict the screen pan to the bounds of the mesh... So I went for a simple, custom solution.
For now, I just zoom on the centre of the mesh.
> Implement centred zoom

- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/hooks.ts
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
The re-renders when navigating in the explorer are caused by `App`, so the memoization we had on `HeatmapVis` can be moved higher up, to the direct descendants of `App`: `DatasetVisualizer` and `MetadataViewer`.
Now we'll notice if we ever trigger re-renders in `HeatmapVis` by mistake.
`key` prop was telling React to delete the entire DOM sub-tree and to recreate it when switching between two datasets, leading to the ThreeJS canvas and rendering context having to be recreated each time.
> Optimise rendering of DatasetVisualizer

- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/dataset-visualizer/utils.ts
By removing the `key` prop from `DatasetVisualizer`, I introduced a regression where `activeVis` could become stale when switching between two datasets with different sets of supported visualizations. `activeVis` is updated asynchronously with `useEffect`, so it may become stale for one render.
I now check whether `activeVis` is stale before rendering `VisDisplay`.
> Fix stale `activeVis` state

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/Mesh.tsx
- src/h5web/visualizations/heatmap/utils.ts
**VICTORY** 😤 
I found these two techniques while digging through [this R3F issue](https://github.com/react-spring/react-three-fiber/issues/240).
The material and the texture are initialised within `useMemo`, which means they're not recreated on resize. This is enough to provide fluid resizing.
By default, R3F starts a game loop - i.e. it re-renders continuously in a `requestAnimationFrame()` loop. This simplifies things, but it also uses more CPU/GPU/battery.
I switch off the game loop with `invalidateFrameloop`, and trigger re-renders manually with `invalidate()` when needed. Re-renders are required when zooming/panning, so I call `invalidate` inside `moveCameraTo`.
Interestingly, disabling the game loop resulted in a side effect on resize: the camera's viewport would leave the bounds …
> Fluid resizing and optimised animation loop

- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/ColorMapSelector.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/IndexAxis.tsx
- src/h5web/visualizations/heatmap/LogScaleToggler.tsx
- src/h5web/visualizations/heatmap/interpolators.ts
- src/h5web/visualizations/heatmap/store.ts
- src/h5web/visualizations/heatmap/utils.ts
The commits give a good overview of the refactor, but basically the whole domain/interpolator/scale logic now resides in a single place: the store.
> Move domain, interpolator and scales to Heatmap state

- src/h5web/App.module.css
- src/h5web/App.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.module.css
- src/h5web/metadata-viewer/MetadataViewer.module.css
- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/styles/vars.css
Here is the first version:
I think some improvements are to be made on the styling so I open the PR early for discussion.
The reasons for the aspect of this first version are the following: I wanted the `roleToggler` to integrate with the rest of the viewer with the same background color. While this poses no problem in `Visualize` mode, in `Inspect` mode, the roleToggle merges visually with the first header `Link Info`. I added a border then but this is not extremely elegant...
> MetadataViewer and DatasetVisualizer are now a single switchable panel

- src/h5web/App.module.css
- src/h5web/App.tsx
Fixes #85 
I didn't extract the sidebar into a separate component as I believe you've started on the breadcrumbs and didn't want to risk conflicts. I hide the explorer with `display: none` for now so it doesn't lose its internal state.
> Add button to show/hide explorer sidebar

- package-lock.json
- package.json
- src/h5web/visualizations/LineVis.module.css
- src/h5web/visualizations/LineVis.tsx
- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/IndexAxis.tsx
- src/h5web/visualizations/matrix/MatrixVis.module.css
- src/h5web/visualizations/matrix/MatrixVis.tsx
Fix #88 
I use `useMeasure` everywhere instead. This leads to a significant gain in performance when resizing the matrix and line visualizations. It also fixes a bug where the internal state of the matrix vis, notably, would reset on resize (e.g. turn sticky off then resize => stickiness turns back on).
When `useMeasure` is first executed, it returns a width and height of 0. I check for this everywhere to save us from rendering invisible things.
> Stop using AutoSizer

- src/h5web/visualizations/heatmap/HeatmapVis.module.css
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/store.ts
Fixes #70 
I added a boolean to the state (`true` by default), but I didn't add a button to change it as this will go in the soon-to-be toolbar.
The Heatmap takes all available width or height depending on the size ratio of the dataset.
> Implement orthonormal option for heatmap

- package-lock.json
- package.json
- src/h5web/visualizations/heatmap/HeatmapToolbar.module.css
- src/h5web/visualizations/heatmap/HeatmapVis.module.css
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/Toggler.tsx
- src/h5web/visualizations/heatmap/Tooltip.tsx
- src/h5web/visualizations/heatmap/hooks.ts
Fix #48 -- The tooltip:
- shows the data coordinates and value;
- moves to the other side of the cursor when reaching the bounds of the canvas (thanks to VX's `TooltipWithBounds`);
- disappears while panning.
In order to not couple the event handling logic for the tooltip with the zoom/pan logic, I render a second mesh behind the textured mesh to which I pass tooltip-specific pointer event listeners. I may refactor the zoom/pan code in a similar fashion so it can be re-used more easily in other visualizations.
> Implement heatmap tooltip

- package-lock.json
- package.json
- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/utils.ts
- src/h5web/visualizations/heatmap/worker.ts
- src/workerLoaderMock.js
I used [`comlink`](https://github.com/GoogleChromeLabs/comlink), which simplifies writing and communicating with web workers, along with [`react-use-comlink`](https://github.com/pocesar/react-use-comlink).
I had to replace `useDataScale` with a utility function so I could recreate the data scale on the web worker (functions can't be sent to web workers).
The result is that the UI remains fluid while the texture is being recomputed.
Next, I'll investigate whether there's a better way to send the values to the web worker. At the moment, the JS array is copied. I hear it's better to _transfer_ a `Uint8Array` by reference... I don't think I'll bother with moving finding the domain to a web worker, as it seems to be pretty fast at the moment, and it only occurs once when selecting a dataset …
> Perform texture computation on web worker

- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/worker.ts
This should improve the performance of texture computations.
> Transfer buffers to/from worker to avoid cloning

- src/h5web/visualizations/heatmap/HeatmapToolbar.module.css
- src/h5web/visualizations/heatmap/HeatmapToolbar.tsx
- src/h5web/visualizations/shared/ScreenshotButton.module.css
- src/h5web/visualizations/shared/ScreenshotButton.tsx
- src/h5web/visualizations/shared/VisCanvas.tsx
Fix #95. The new toolbar button converts the canvas to a data URI and opens it in a new tab. This is the equivalent to <kbd>right click > View image</kbd>, which now also works consistently. The generated image can then be saved as PNG with <kbd>Ctrl+S</kbd>
Note that the generated image has the same dimension of the canvas, so you need to go full screen to export a bigger image. I think this is sufficient to meet the requirements for an image export feature, but we'll see with usage.
I've implemented the button as a shared component so it can be reused in the line vis toolbar. I also made the choice:
- to just query for the canvas in the DOM instead of trying to get a reference through React, as this would have complexified things significantly...
- to do nothing if the canvas is not in …
> Implement screenshot button

- .env
- .gitignore
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/TreeView.tsx
Fix #122 
I went for an environment variable in `.env.local` for now, as it is not version controlled. This means we don't have to be careful not to stage the change on every commit anymore...
So for instance, to select the `intensity_normed` dataset on mount, create a file called `.env.local` at the root and paste the following config:
```
REACT_APP_DEFAULT_PATH=[0,2,1,0]
```
> Add default path configuration to select explorer node on mount

- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/visualizations/heatmap/HeatmapProvider.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/line/LineProvider.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/shared/AxisSystem.module.css
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/VisCanvas.tsx
- src/h5web/visualizations/shared/models.ts
- src/h5web/visualizations/shared/utils.ts
Reopening of #128 due to my mistaken push.
This has several advantages:
- Fixing #104 
- Generalizing the axis placement: putting xAxis on the top or yAxis on the right can be done more easily.
- Adding some breathing room between the canvas and the toolbar:
* Previously:
* Now:
> Add top and right padding to visualisation area

- src/h5web/visualizations/line/hooks.ts
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/utils.ts
This PR addresses the problem that the scales linking the scene coordinates (R3F) to axis domains were computed separately for the `LineVis` and `AxisSystem`. I foresaw problems due to this for future `LineVis` developments (#119, #74).
In short:
* The computation of scaleToAxis scales was moved in a shared function in `visualisations/shared/utils`.
* `LineVis` now uses the output of this function to do axisToScale computations thanks to `invert`.
* The state of `AxisSystem` was revert to axisDomains rather than scales as `computeAxisScales` was not shared anyway.
> Refactored sceneToAxis scales computation

- src/h5web/explorer/Explorer.module.css
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/TreeView.tsx
- src/h5web/explorer/models.ts
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/providers/utils.test.ts
- src/h5web/providers/utils.ts
The default path set with `REACT_APP_DEFAULT_PATH` no longer prevents navigating the explorer tree.
> Fix default path processing

- package-lock.json
- package.json
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/shared/TooltipMesh.tsx
Vertical for `LineVis`. Both directions for `HeatmatVis`. Uses `Line` from `@vx/shape`
More fancy things such as constraining the guide to the data and adding a marker must wait until axes domains/scales are refactored.
As a consequence, it is not necessary to merge this right now.
> Added tooltip guides

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/hooks.ts
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/TooltipMesh.tsx
- src/h5web/visualizations/shared/VisCanvas.tsx
- src/h5web/visualizations/shared/models.ts
- src/h5web/visualizations/shared/utils.ts
The new API allows passing a config for each axis. It gets us one step closer to the axis-to-dimension mapping feature.
An axis config can declare either an "index" axis (i.e. ordinal) or a "data" axis (i.e. non-ordinal) -- this behaviour is based on the property used to pass the domain: `indexDomain` or `dataDomain`.
- A data axis config can have `isLog: true`, but not a index axis config.
- Both configs can have `showGrid: true`, but I haven't changed the current grid for now, so it's only visible if both axis configs have `showGrid: true`.
- There are no additional configuration options for now, although the goal will be to add `centerTicks` for index axis, and perhaps a `logType` enum for data axis, an `oppositeSide` boolean to move the axis to the top/right side, etc.
> Refactor VisCanvas API

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
Fixes #146. The main fix is to ask for a number of ticks that matches the number of integer values in the visible domain. This works very well in most cases.
Unfortunately, [`d3.ticks()`](https://github.com/d3/d3-array#ticks) (used internally by d3-scale) doesn't always respect the requested number of ticks. For instance, `d3.ticks(0, 4, 3)` outputs 5 ticks instead of the requested 3. This is easy to check on https://observablehq.com/@d3/d3-ticks. 
This weird behaviour can lead to decimal tick values in some cases. For instance, `d3.ticks(0, 2, 3)`  returns `[0, 0.5, 1, 1.5, 2]`.
The problem comes from `d3.tickIncrement` (or its equivalent, `d3.tickSteps`), which is used internally by `d3.ticks()`. To work around the issue, I re-implemented a simplified version of `d3.ticks()` that calls …
> Show only integer ticks on index axes

- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/models.ts
- src/h5web/visualizations/heatmap/utils.ts
- src/h5web/visualizations/heatmap/worker.ts
- src/h5web/visualizations/line/hooks.ts
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/TooltipMesh.tsx
- src/h5web/visualizations/shared/models.ts
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
The main goal of this refactoring is to simplify the code that relies on the axis configs passed to `VisCanvas`. From now on, `AxisSystemProvider` converts the two configs into two `AxisInfo` objects. These objects have two jobs:
- to represent the configs in a format common to both index and data axes (e.g. `domain` instead of `indexDomain` and `dataDomain`, `isLog` always present but always `false` for index axes, etc.);
- to store any information that can be deduced from the configs so the child components don't have to deduce them themselves (e.g. `isIndexAxis`, `scaleFn`).
This implementation allows `VisCanvas` to keep a simple, type-safe, public API, while also reducing a lot of the complexity in our internal components.
> Pass axes info through axis system context instead of raw config

- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/dataset-visualizer/VisSelector.tsx
- src/h5web/dataset-visualizer/utils.ts
- src/h5web/visualizations/index.ts
Previously, we had:
1. Dataset changes
1. `DatasetVisualizer` renders
- `activeVis` is identified as invalid, so `undefined` is used instead;
- `useEffect` schedules reset of `activeVis` state on next render.
1. Children of `DatasetVisualizer` render, but `VisDisplay` is removed from DOM because `activeVis` is `undefined`.
1. `DatasetVisualizer` renders again on next tick (because of change of `activeVis` state in `useEffect`) 
1. Children of `DatasetVisualizer` render, and `VisDisplay` is re-added to the DOM now that `activeVis` is valid again.
Now, we have:
1. Dataset changes
1. `DatasetVisualizer` renders
- Change of dataset is detected, so `setActiveVis` is called right away (instead of being scheduled in `useEffect`) -- this cancels rendering of `DatasetVisualizer`'s children.
- …
> Refactor update of active visualization

- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/visualizations/line/hooks.ts
When the first dataset I open is a 1D dataset (line vis by default), the dimension mapper doesn't appear. I have to switch to the matrix vis and come back to the line vis for the mapper to appear.
This commit fixes this issue, and applies the fix to the other use of the derived state pattern. It also fixes an issue with the line vis when `slicingIndices` is an empty array, which occurs when there are no indices to slice (e.g. line vis with 1D dataset).
> Fix dim mapper not appearing on initial dataset selection

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
I was getting errors when leaving/entering the heatmap at the top. `formatValue` was receiving a `y` data coordinate equal to the number of rows, when the max should be `rows - 1`.
This happens because we pass `[0 rows]` as ordinate domain. The tooltip uses the same scale as the axis instead of a scale with a domain of `[0, rows[`.
Can't think of a better solution for now...
> Fix out-of-bound error with Heatmap tooltip

- src/h5web/visualizations/line/DataCurve.tsx
- src/h5web/visualizations/line/LineToolbar.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/config.ts
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/ToggleGroup.tsx
- src/h5web/visualizations/shared/Toolbar.module.css
- src/h5web/visualizations/shared/models.ts
- src/h5web/visualizations/shared/utils.ts
Another go at the log scale but the approach is different than the one in #176. Here I choose the following implementation (discussed in #74):
> 2. Display only the positive values on which the log transformation was able to be done.
There are things already discussed in #176 but I feel it was cleaner to open a new PR.
> Implemented LogScale for LineVis (hide points if the values are not supported)

- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/HeatmapToolbar.tsx
- src/h5web/visualizations/heatmap/config.ts
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/models.ts
- src/h5web/visualizations/heatmap/utils.ts
- src/h5web/visualizations/heatmap/worker.ts
- src/h5web/visualizations/line/LineToolbar.tsx
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/ScaleSelector.tsx
- src/h5web/visualizations/shared/models.ts
First step of #184 
For now, an invalid domain (i.e crossing zero) will lead to a black texture. I will address the proper support in a future MR but I wanted first to discuss the refactoring needed for the simple implementation.
> Added log scale to the Heatmap

- .env
- src/h5web/Profiler.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- Add env var to enable profiling in development (use of React's Profiler are automatically removed by React when building for production).
- Create component to wrap a tree with React's `Profiler` based on the new env var.
- Wrap the visualizations render call in `VisDisplay` with a profiler to profile every visualization.
> Allow profiling visualisations

- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/Mesh.tsx
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/utils.ts
- src/h5web/visualizations/heatmap/worker.ts
After our discussion in #184, I finally settled for the following behaviour:
- Pixels with invalid values are set to white color*
- The store is untouched: the `supportedDomain` is computed in the `HeatmapVis` as the single source of truth and passed to the components needing it.
- As a consequence, `customDomain` and its associated slider do **not** reflect the changes in `supportedDomain`
_* This is the behaviour in matplotlib so I expect users to be used to it:_
> Heatmap is working with LogScale with invalid values (set to white)

- src/h5web/visualizations/heatmap/ColorBar.tsx
- src/h5web/visualizations/heatmap/DomainSlider.tsx
- src/h5web/visualizations/heatmap/HeatmapToolbar.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.module.css
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/Mesh.tsx
- src/h5web/visualizations/heatmap/config.ts
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/heatmap/utils.ts
- src/styles/vars.css
The texture flickering issue is gone for good!
- Compute data domain in `HeatmapVis` instead of config (in `useMemo` to avoid unnecessary recomputations).
- Make `HeatmapVis` the source of truth for the custom domain whenever `values` prop changes (because for one render, the config may have a stale custom domain).
- Use effect hook to update data domain and reset custom domain in config when `values` prop changes.
Since the domain is no longer computed asynchronously, we can also:
- remove the workaround that used to avoid consecutive texture recomputations;
- render an error message and return early when the domain can be computed from the current `values`.
> Fix custom domain resetting

- package-lock.json
- package.json
- src/h5web/visualizations/shared/MappedVis.tsx
- src/react-app-env.d.ts
A revised version of #178 to fix #170.
> Split useMemo in two in VisProvider (one for ndarray creation, one for slicing).
The `useMemo` now lives in `MappedVis` that replaced `VisProvider`. But it was done.
> Simplify unpack(mappedView).flat() by unpacking a flat array directly.
Done with `ndarray-ops` (https://github.com/scijs/ndarray/issues/32#issuecomment-253972844)
Other tasks were not considered as they depend on `cwise` which does not seem actively maintained [as I pointed out](https://github.com/silx-kit/h5web/issues/170#issuecomment-643970544).
> Optimize ndarray uses in MappedVis

- src/stories/ColorBar.stories.tsx
To get used to Storybook, I had some fun to change the domain args into two sliders. But it may obfuscate the true `domain` arg so I can revert to a regular `domain` control.
> Adding story for the ColorBar

- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
<s>
Getting back to the integer ticks problems, I felt that the current implementation was sometimes hard to follow:
- `AxisInfo` and `AxisConfig` are quite similar but used for different purposes
- The distinction between `IndexAxisConfig` and `DataAxisConfig` leads to additional code (different types, a type guard) as both are again very similar. Also, it is not clear from first approach that `IndexAxisConfig` forces the axis to contain only integers.
Reading the code, I found myself sometimes misdirected by all these different but similar types.
To address these points, I did the following:
- I removed `AxisInfo`. `AxisConfig` is used instead with a new boolean member `onlyIntegers`.
- The boolean `onlyIntegers` makes the distinction between `IndexAxisConfig` and `DataAxisConfig` …
> Remove AxisInfo from getTickProps

- src/h5web/visualizations/heatmap/Mesh.tsx
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/TooltipMesh.tsx
- src/h5web/visualizations/shared/VisCanvas.module.css
Fixes the following warning in the console as `<HTML />` component was renamed to `<Html />` (https://github.com/pmndrs/drei#html-):
> Renamed drei's HTML into Html

- src/h5web/visualizations/MappedHeatmapVis.tsx
- src/h5web/visualizations/MappedLineVis.tsx
- src/h5web/visualizations/MappedMatrixVis.tsx
- src/h5web/visualizations/line/LineToolbar.tsx
- src/h5web/visualizations/line/config.ts
- src/h5web/visualizations/shared/ToggleBtn.tsx
- src/h5web/visualizations/shared/hooks.ts
Fix #182 
It bothers me a bit though: this toggle serves no purpose when the array is not mapped and I did not find any easy way to disable it in this case. 
Also I find that the label `Auto scale` does not convey the true purpose of this button.
> Implements Auto-scaling toggle

- package-lock.json
- package.json
- src/h5web/visualizations/heatmap/Mesh.tsx
- src/h5web/visualizations/shared/AxisSystem.module.css
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/Html.tsx
- src/h5web/visualizations/shared/TooltipMesh.tsx
- src/h5web/visualizations/shared/VisCanvas.module.css
If you recall, drei's `Html` element is meant to "follow" the camera zoom and position. There are a couple of props like `center` and `fullscreen`, but they don't do what we need: make a `div` fill the canvas regardless of camera zoom and position.
I couldn't make `createPortal` work (neither ReactDOM's nor R3F's `createPortal`) to replace drei's `Html` element, as suggested in #204, so I decided to implement my own, simplified version of the component.
This allowed me to simplify a number of things in the codebase. For instance, we no longer need to pass a width and height to `Html` or its children, since, by default, it fills the space of the canvas.
> Implement simplified version of drei's `Html` component

- src/h5web/visualizations/MappedHeatmapVis.tsx
- src/h5web/visualizations/heatmap/HeatmapToolbar.tsx
- src/h5web/visualizations/heatmap/config.ts
Fix #221 
In terms of interaction with the custom domain:
- When autoscale is off, the custom domain is kept when moving through slices.
- When autoscale is on, the custom domain is set to the `dataDomain` (that is the domain of the slice) at each slice change. However, it can still be changed when looking at a single slice (same as before).
- When toggling the autoscale, the custom domain is reset
> Added Auto-scale for Heatmap

- src/h5web/BreadcrumbsBar.module.css
- src/h5web/BreadcrumbsBar.tsx
Fix #127 
Because of the resizable explorer panel, we can't rely on a simple CSS media query to hide crumbs. So to avoid measuring things with JS, I just went with `text-overflow: ellipsis;`.
Thanks to flexbox, the crumbs all shrink proportionately, so it actually looks great. I tell the last crumb to not shrink, though.
If there's not enough space even for the last crumb, then a last-resort `overflow: hidden` comes into play:
> Make breadcrumbs responsive

- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/Loader.module.css
- src/h5web/dataset-visualizer/Loader.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
Fix #223 
To retrieve the value of a dataset, providers expose a function called `getValue` that returns a promise. The value is therefore retrieved asynchronously whether or not the provider already has access to it in memory. One challenge was to not flash the loader when this is the case.
I used react-use's `useAsyncFn` hook for this. Hopefully this is clear in the code, but the goal is to set the `loading` flag to `true` only if `getValue` takes more than 50ms to complete.
> Show loader while fetching datasets values

- src/h5web/visualizations/line/LineVis.module.css
- src/h5web/visualizations/matrix/MatrixVis.module.css
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/utils.ts
- src/stories/LineVis.stories.tsx
Fix #183
I just had another crack at the issue, and it's looking good... 😤 
1. I log the min and max of the axis' visible domain and compute the difference.
1. I compare the result with a threshold, which I compute with a linear scale based on the space available to the axis (similarly to `adaptedNumTicks`).
1. If the logged extent of the domain spans less than the threshold, then it means that all ticks can be displayed without any overlap and I use the default tick formatter (`format('0')`).
1. Otherwise, I use a formatter that displays only exact powers of 10.
The only downside I see is that I don't check whether the visible ticks are far apart or close together; the threshold is computed on the assumption that the ticks are close together. As a result, there may be cases where zero or …
> Improve display of log ticks

- src/h5web/visualizations/shared/Axis.tsx
- src/h5web/visualizations/shared/AxisSystem.module.css
- src/h5web/visualizations/shared/AxisSystem.tsx
- src/h5web/visualizations/shared/hooks.ts
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
I've split the fix/refactor in two commits:
1. In the first commit, I fix the bug where the axes were being temporarily reset on any change, like the color map.
The bug occurs because of the `useUpdateEffect` in `AxisSystem`, which resets the visible domains to the initial axis domains any time the latter changed ... which happens on every render of `HeatmapVis` and `LineVis` since we pass inline arrays as domains - e.g. `[0, rows]`.
I could have fixed this by computing the visible domains in the `useUpdateEffect` (in addition to computing them in `useFrame`), but this led to an incoherent state for one render when the newly calculated scale would no longer be coherent with the yet-to-be-calculated visible domains.
I then realised that storing the visible domains in the state was …
> Refactor axis system and fix re-rendering bug

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/shared/hooks.ts
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
- src/packages/lib.ts
- src/stories/HeatmapVis.stories.tsx
- src/stories/Home.stories.mdx
- src/stories/LineVis.stories.tsx
Fix #246 
`getSupportedDomain` merges into `getDataDomain` so that `useDataDomain` now returns a supported domain right away. In other words, the visualizations no longer compute the supported domain themselves; they must now receive a supported domain as prop.
Passing an unsupported domain to a visualization fails silently (but not invisibly); it does not throw an error and break the app. This can be observed in the Storybook:
- with `LineVis`, the y axis and the curve are not rendered;
- with `HeatmapVis`, the textured mesh and the color bar's axis are not rendered.
I believe this behaviour to be adequate and sufficient.
> Fix no auto-scale behaviour with log scale and domain that crosses zero

- src/h5web/App.test.tsx
- src/h5web/dataset-visualizer/DatasetVisualizer.tsx
- src/h5web/dataset-visualizer/VisDisplay.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hooks.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/mock/api.ts
- src/h5web/providers/silx/api.ts
- src/setupTests.js
This allows the metadata to be provided synchronously to components, which simplifies a bunch of code.
`useEntity` no longer contains an async state, which means that in no longer triggers an extra rendering of `App`, which makes the use of `React.memo` in `DatasetVisualizer` obsolete. I was tempted to turn `useEntity(link)` into `getEntity(metadata, link)` to be able to call the function more freely, but I'll leave that until I actually need the flexbiity (e.g. to find the `default` NeXus group).
> Fetch metadata in provider before rendering app

- src/stories/HeatmapVis.stories.tsx
The story was using a transposed view as `dataArray` so that the dimensions were transposed but the data itself was not. 
The tooltip values were then inverting x and y.
**Before:**
**Now:**
(with correct tooltip)
> Use real transposed array rather than view in Heatmap story

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/line/DataCurve.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/shared/Axis.tsx
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/hooks.ts
- src/h5web/visualizations/shared/models.ts
- src/h5web/visualizations/shared/utils.test.ts
- src/h5web/visualizations/shared/utils.ts
- src/packages/lib.ts
- src/stories/AxisSystem.stories.tsx
- src/stories/HeatmapVis.stories.tsx
- src/stories/Home.stories.mdx
- src/stories/LineVis.stories.tsx
... and falls back to indices when arrays are not supplied (previous behaviour)
<s>We may want to discuss a change that may be seen as a regression: the tooltip on the LineVis now shows the X/Y values of the closest point to the left and not of the closest point.
Ex: Previously, moving the mouse to X=28.75 showed the X/Y values for X=29. Now it shows the X/Y values for X=28.
The reason is that the previous behaviour can not be easily reproduced when X represents arbitrary values and not indices.</s>
**EDIT**: Actually, I found a way to do this ! See the end of https://github.com/silx-kit/h5web/pull/251#discussion_r506201340
I will fix the `AxisSystem` story after the first round of discussions.
>  LineVis and HeatmapVis now accept arrays of values for x and y

- src/demo-app/DemoApp.tsx
With #253, I'm planning to provide a number of mock data generation utilities, and perhaps generate the mock `metadata` object right away, so as discussed, lazy-loading the provider to split it from the main bundle makes sense.
> Lazy-load MockProvider for code-splitting purposes

- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/visualizations/containers/HeatmapVisContainer.tsx
- src/h5web/visualizations/containers/LineVisContainer.tsx
- src/h5web/visualizations/containers/MatrixVisContainer.tsx
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/containers/hooks.ts
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/matrix/MappedMatrixVis.tsx
- src/h5web/visualizations/nexus/models.ts
- src/h5web/visualizations/nexus/utils.ts
- src/h5web/visualizations/shared/hooks.ts
- src/h5web/visualizations/shared/utils.ts
Fix #236
Even with the heavy refactoring of #251, this ended up more complex than expected.
`NXSpectrum` uses now the `MappedLineVis` and not the `LineVis` which means I had to implement a way to determine the correct dataset as abscissas to use given its position in the `axes` list.
> NXSpectrum now uses the axes attribute to fetch the abscissa dataset to be used in the vis.

- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/index.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/nexus/utils.ts
- src/h5web/visualizations/shared/Axis.tsx
- src/h5web/visualizations/shared/AxisSystem.module.css
- src/h5web/visualizations/shared/AxisSystemProvider.tsx
- src/h5web/visualizations/shared/VisCanvas.tsx
- src/h5web/visualizations/shared/models.ts
- src/stories/AxisSystem.stories.tsx
- src/stories/LineVis.stories.tsx
Updates also the tooltip.
I also added some stories showing this for `LineVis` and `AxisSystem`
> NxSpectrum now shows the axis label for x and y

- src/h5web/providers/mock/data.ts
- src/h5web/providers/models.ts
- src/h5web/providers/silx/api.ts
- src/h5web/providers/silx/models.ts
- src/h5web/visualizations/index.test.ts
- src/h5web/visualizations/index.tsx
Start of #253 
I add a file called `providers/mocks/data.ts` with mock HDF5 objects and generation utilities, which I then used to rewrite the tests of the visualizations' `supportsEntity` functions.
In the next PR, I will use these objects and utilities to generate mock data for the `/mock` endpoint.
> Use mock data generation utilities in tests

- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
I thought a refactoring would be needed to fix this but I found a workaround.
That being said, I am not extremely happy about the current state of things. To be discussed together when we have time.
> Fix non-integer ticks when abscissa/ordinate values were not supplied

- src/h5web/App.test.tsx
- src/h5web/providers/mock/data.ts
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/index.test.ts
- src/h5web/visualizations/index.tsx
- src/h5web/visualizations/nexus/models.ts
- src/h5web/visualizations/nexus/utils.ts
Fix #233 
The default attribute can:
- be a relative path in the file
- be an absolute path in the file
- points to another entity with a default attribute
> NxImage and NxSpectrum now supports NX groups with default attribute

- src/h5web/visualizations/shared/AxisSystem.module.css
Fix #258 
_Mocked dataset `fourD` with D0 in Y and D3 in X:_
It was due to the default size of the parent `<svg>` of `Axis` (300 x 150). At heights lower than 150px, the height of the ordinate axis `<svg>` made the bottom axis go lower than the canvas.
<s>I fixed it by setting the dimensions of the `Grid` and `Axis` `<svg>` to `100%` so that they always have the same width/height as the canvas.</s>
https://github.com/silx-kit/h5web/pull/269#issuecomment-717955822 instead
> AxisSystem svg now have zero width and height to avoid svg default size

- .env
- .eslintignore
- .eslintrc.json
- package-lock.json
- package.json
- packages/package.json
- src/h5web/visualizations/heatmap/hooks.ts
- src/h5web/visualizations/shared/hooks.ts
- src/h5web/visualizer/Visualizer.tsx
- src/setupTests.js
- tsconfig.json
Here is a summary of what has changed:
- drops Node 8
- Jest's `resetMocks` option is enabled by default
- `EXTEND_ESLINT` env var is no longer needed
It also brings a lot of major dependency upgrades:
- drops Node 8
- ignores nested `node_modules` by default
- allows additional comments in disable comments - e.g. `// eslint-disable-line no-console - this is why`
Our config, `@wsmd/eslint-config` hasn't upgraded to ESLint v7 and seems unmaintained... We're going to have to replace it, perhaps with https://github.com/ljosberinn/eslint-config-galex. In the meantime, I've removed it completely and I now extend CRA's built-in config. I've also cleaned up some of the overrides that we had for `@wsmd/eslint-config`.
- drops Node 6! 😱 
- faster and better console outputs
- JSDOM from 11 to 15
- …
> Upgrade Create React App to v4

- src/h5web/providers/mock/data.ts
- src/h5web/visualizations/containers/HeatmapVisContainer.tsx
- src/h5web/visualizations/containers/LineVisContainer.tsx
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/index.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/nexus/models.ts
- src/h5web/visualizations/nexus/utils.ts
- src/h5web/visualizations/shared/AxisSystem.module.css
- src/stories/HeatmapVis.stories.tsx
Fix #265 
I added the support of `long_name` as well as it was the same logic.
Also updated the mock data with some `long_name` and `units` attributes.
> Nx Axis labels are now determined from long_name and units attributes

- .eslintrc.js
- src/h5web/visualizations/Visualizations.test.tsx
- src/h5web/visualizer/Visualizer.test.tsx
Some higher-level feature tests for `supportsEntity` and the vis selector. I only test ideal scenarios with existing mock data. I think the tests in `visualizations/index.test.ts` are worth keeping, though.
> Test vis selector

- src/h5web/App.tsx
- src/h5web/providers/mock/data.ts
- src/h5web/visualizations/containers/HeatmapVisContainer.tsx
- src/h5web/visualizations/containers/LineVisContainer.tsx
- src/h5web/visualizations/containers/models.ts
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizer/Visualizer.tsx
- src/stories/LineVis.stories.tsx
Fix #278 
<s>I had to make a few changes to have access to the entity name. Indeed, Vis containers only recieve `entity` in props which did not contain the name of the entity.
I therefore changed the `HDF5Entity` names and the API creating them so that the name is now included in `entity`.</s> 
See https://github.com/silx-kit/h5web/pull/286#issuecomment-721728077
> Line and Heatmap now show the entity name as title

- src/h5web/visualizations/matrix/Cell.tsx
- src/h5web/visualizations/matrix/StickyGrid.tsx
The Matrix vis table was just made of `div`s with no semantic whatsoever. I noticed it when trying to feature test the Matrix vis (which I ended up giving up on, because of `useMeasure` not working in JSDOM).
> Improve accessibility of Matrix vis table

- .env
- src/demo-app/DemoApp.tsx
- src/demo-app/HsdsApp.tsx
- src/h5web/providers/Provider.tsx
- src/h5web/providers/hsds/HsdsProvider.tsx
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/silx/SilxProvider.tsx
Fix #280 
Available domains so far on `bosquet`:
- `/home/reader/water`
- `/home/reader/tall`
> Different HSDS domains can now be queried by URL

- cypress/integration/app.spec.ts
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/containers/hooks.ts
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/nexus/hooks.ts
- src/h5web/visualizations/nexus/models.ts
- src/h5web/visualizations/nexus/utils.ts
- src/h5web/visualizations/shared/models.ts
Another tentative refactoring. Following our discussion, I:
- added a dedicated `NxData` type
- implemented the fetching of **all** children datasets at the beginning at it is much more easier then to build the NxData object.
Let me know what you think.
> Now using custom hook to parse nxData entities

- cypress/integration/app.spec.ts
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/shared/models.ts
- src/stories/HeatmapVis.stories.tsx
- src/stories/LineVis.stories.tsx
Fix #300 and adds the relevant Cypress test to avoid unnoticed regression.
The source was the fact that `AxisParams` uses a member `values` while in the refacto #297 I did use `value` instead. Not sure why it was not caught by TS...
> Fixed NeXus vis that did not use `axes` values

- src/h5web/visualizations/index.tsx
- src/h5web/visualizer/utils.test.ts
- src/h5web/visualizer/utils.ts
The `supportsEntity` function of `NxSpectrum` no longer worries about the behaviour of `NxImage`. The spectrum vis supports nD datasets, not just 1D datasets, so that's what it checks for. The `NxSpectrum` is removed from the `supportedVis` array later, if `NxImage` is also supported. This matches the behaviour of the `Raw` vis.
> Remove coupling between `supportsEntity` functions of NeXus vis

- .env
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/models.ts
- src/h5web/providers/utils.ts
- src/h5web/visualizations/containers/HeatmapVisContainer.tsx
- src/h5web/visualizations/containers/LineVisContainer.tsx
- src/h5web/visualizations/containers/MatrixVisContainer.tsx
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/index.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/nexus/hooks.ts
- src/h5web/visualizer/Visualizer.test.tsx
I just had a spark on how we can better type `HDF5Dataset` so that our assertions can accept `HDF5Dataset` objects rather than `HDF5Shape` or `HDF5Type`. This should open up some refactoring opportunities. 🎇 
Apart from that, I use single-line assertions in a few more places to make the code more readable.
> Add generic types to HDF5Dataset and improve assertions

- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/utils.ts
- src/h5web/visualizations/containers/hooks.ts
- src/h5web/visualizations/nexus/hooks.ts
I'm going step by step to keep things clear. I'll refactor `findSignalDataset` next.
> Simplify signature of `useDatasetValues` hook

- .vscode/settings.json
- src/h5web/dimension-mapper/AxisMapper.tsx
- src/h5web/dimension-mapper/SlicingSlider.tsx
- src/h5web/dimension-mapper/models.ts
- src/h5web/visualizations/containers/MatrixVisContainer.tsx
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/matrix/MappedMatrixVis.tsx
- src/h5web/visualizations/shared/hooks.ts
- src/stories/LineVis.stories.tsx
Four commits:
- **Pass errors as `ndarray` to Line vis** instead of as `number[]` for consistency with data array and with errors in Heatmap vis.
- **Make `DimensionMapping` type non-nullable**. Ever since the big refactoring of `Visualizer`, we only use the `DimensionMapper` on visualizations that need it, so we never have a `dimensionMapper` state of `undefined`.
- **Move Matrix vis mapper state from container to mapped vis**. I forgot about the Matrix vis in #342...
- **Replace `useDataArray` hook with overrides**. The overrides add a bit of bloat, but as discussed, they're a little bit cleaner than alternative solutions.
> Replace `useDataArray` hook with overrides and more

- .env
- src/h5web/App.tsx
- src/h5web/BreadcrumbsBar.tsx
- src/h5web/explorer/Explorer.module.css
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/Icon.tsx
- src/h5web/explorer/TreeView.tsx
- src/h5web/explorer/models.ts
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/providers/models.ts
- src/h5web/providers/utils.ts
**Part 1 of The Big Refactoring** ™️  that aims to remove the complexity of having to follow links to find entities by providing a nested HDF5 structure to the entire app.
Since the Explorer already uses a nested structure (`TreeNode`), I thought it would be a good place to start. So this first refactoring consists of replacing the generic `TreeNode<T>` model with a specific, nested HDF5 structure, and to refactor the `buildTree` function to return an object with this new structure.
To keep things manageable and limit the scope of the refactoring, I decided:
- to keep all the existing HDF5 models for now;
- to temporarily prefix the new models with `My`;
- to keep references to the raw links and entities in the new HDF5 structure, so I can pass them to `Visualizer` and `MetadataViewer`;
- …
> Introduce new nested HDF5 models to replace Explorer's `TreeNode`

- src/h5web/metadata-viewer/LinkInfo.tsx
> Show link class in metadata viewer

- .prettierignore
- package-lock.json
- package.json
- src/h5web/BreadcrumbsBar.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/metadata-viewer/EntityTable.tsx
- src/h5web/providers/models.ts
- src/h5web/test-utils.tsx
- src/h5web/visualizations/index.test.ts
- src/h5web/visualizations/nexus/utils.ts
Some isolated preparatory work for #365.
When creating mock data, it feels too complex and unnecessary to recursively add a parent to its nested children. A classic tree structure in which entities reference only their direct parent is perfectly suited to our use case. It is indeed very easy to recursively find every ancestor of an entity when needed.
> Store only direct parents in nested entities

- src/h5web/explorer/Explorer.test.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/providers/context.ts
- src/h5web/providers/mock/MockProvider.tsx
- src/h5web/providers/mock/data.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/models.ts
- src/h5web/providers/my-utils.ts
- src/h5web/providers/utils.ts
- src/h5web/visualizations/index.test.ts
- src/h5web/visualizer/Visualizer.test.tsx
- src/h5web/visualizer/utils.test.ts
- src/packages/lib.ts
- src/stories/HeatmapVis.stories.tsx
- src/stories/Home.stories.mdx
- src/stories/LineVis.stories.tsx
- src/stories/LineVisDisplay.stories.tsx
- src/stories/LineVisScales.stories.tsx
I use the new metadata in `MockProvider` with a temporary change to the types of the providers' context. This will allow us to migrate the providers one at a time.
> Generate nested mock metadata

- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/providers/mock/data.ts
- src/h5web/providers/my-utils.ts
- src/h5web/providers/raw-utils.ts
- src/h5web/visualizations/index.test.ts
- src/h5web/visualizer/utils.test.ts
I also move all the old utilities into a file called `raw-utils.ts` to avoid circular imports, as some of these "raw" utilities are used by the new utilities (like `makeStrAttr`). I'm not a huge fan of this; we'll have to talk about it over Zoom later on.
> Refactor `buildTree` to use new entity creation utilities

- .env
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/utils.test.ts
- src/h5web/explorer/utils.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/visualizations/nexus/utils.ts
`REACT_APP_DEFAULT_PATH` now accepts a string path, like `/entry_0000/2_buffer_subtraction`.
> Refactor `getEntityAtPath` to accept string path

- src/h5web/visualizations/line/DataCurve.tsx
Fix #373 
This reverts a part of #371 by creating the shared `BufferGeometry` imperatively rather than declaratively with `useUpdate`. `useUpdate` indeed leads a `undefined` shared geometry at first render: https://github.com/pmndrs/react-three-fiber/discussions/863
> Fixed geometry display in DataCurve

- src/h5web/explorer/Explorer.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hsds/HsdsProvider.tsx
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/silx/api.ts
- src/h5web/providers/utils.ts
And ... done! All providers now provide the new nested metadata structure to the app!
Well, one step remains: cleaning things up -- i.e. moving and renaming things. But we should maybe do this together via LiveShare.
> Build nest metadata in HSDS and Silx providers directly

- src/h5web/explorer/EntityList.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/explorer/Icon.tsx
- src/h5web/explorer/utils.ts
- src/h5web/guards.ts
- src/h5web/metadata-viewer/EntityTable.tsx
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/mock/data.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/my-utils.ts
- src/h5web/providers/raw-utils.ts
- src/h5web/visualizations/ScalarVis.tsx
- src/h5web/visualizations/containers/HeatmapVisContainer.tsx
- src/h5web/visualizations/containers/LineVisContainer.tsx
- src/h5web/visualizations/containers/MatrixVisContainer.tsx
- src/h5web/visualizations/containers/NxImageContainer.tsx
- src/h5web/visualizations/containers/NxSpectrumContainer.tsx
- src/h5web/visualizations/containers/RawVisContainer.tsx
- src/h5web/visualizations/containers/ScalarVisContainer.tsx
- src/h5web/visualizations/heatmap/HeatmapVis.tsx
- src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx
- src/h5web/visualizations/index.tsx
- src/h5web/visualizations/line/LineVis.tsx
- src/h5web/visualizations/line/MappedLineVis.tsx
- src/h5web/visualizations/matrix/MappedMatrixVis.tsx
- src/h5web/visualizations/nexus/hooks.ts
- src/h5web/visualizations/nexus/models.ts
- src/h5web/visualizations/nexus/utils.ts
- src/h5web/visualizations/shared/utils.ts
- Move shared guards to `h5web/guards.ts`.
- Don't use `make*` mock data utilities in `buildTree` to avoid confusion.
- Remove `RawSilxStyle` model and rename properties of `SilxStyle` to camel case.
- Silently protect against malformed `SILX_style `attribute.
> First round of clean up

- src/h5web/visualizations/shared/utils.ts
I had a crack at #346 but I can't find a solution that infers the subset of the `ScaleType` union automatically. Best I can do is `createScale<'linear' | 'log' | 'symlog'>(config)`, so telling Typescript which types of config to expect, which isn't bad but isn't particularly amazing either...
So I think our current solution of having our own `createScale` implementation is fine. I just rewrote it with a `switch` and by referring to the `ScaleType` enum instead of repeating the strings `linear`, `log` and `symlog`.
> Use `ScaleType` enum in `createAxisScale` function

- .env
- src/demo-app/DemoApp.tsx
- src/demo-app/JupyterApp.tsx
- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/jupyter/JupyterProvider.tsx
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/jupyter/models.ts
- src/h5web/providers/jupyter/utils.ts
- src/packages/app.ts
A few loose ends left to tie:
**EDIT**: I think it is fine for now: shapes can be either scalar, simple or null. Inferring from the dims seems sufficient.
> Basic working version of the Jupyter backend provider

- src/h5web/providers/hsds/api.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.ts
Is stored as `h5domain` in HSDS external links.
> Fixed file field in HSDS external link

- src/h5web/App.module.css
- src/h5web/App.tsx
- src/h5web/explorer/EntityItem.tsx
- src/h5web/explorer/EntityList.tsx
- src/h5web/explorer/Explorer.module.css
- src/h5web/explorer/Explorer.test.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/jupyter/utils.ts
- src/h5web/providers/mock/MockProvider.tsx
- src/h5web/providers/silx/api.ts
- src/h5web/visualizer/ErrorMessage.tsx
- src/h5web/visualizer/Visualizer.module.css
- src/h5web/visualizer/Visualizer.test.tsx
After much staring into space trying to figure out the best approach, here is what I came up with:
- The `ProviderAPI` contract that providers must implement now includes a `getGroup` method, which will eventually replace `getMetadata`. `getGroup` accepts a string `path` and must return a `Group` entity. As an example, `getGroup('/')` must return the root `Group`. 
- `Provider` now includes a second suspense store called `groupsStore` that wraps the new `getGroup` method. In other words, **we now have a cache that stores groups against their paths**. `groupsStore` is available through context, which means that we can call `groupsStore.get('/some/path')` to either get the metadata of the group at `/some/path` from the cache, or suspend rendering while the group's metadata is being fetched …
> Implement async loading of groups metadata in Explorer

- src/h5web/guards.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/utils.ts
Part of #417.
The `getGroup` methods now return fuller `Group` objects (with attributes, type/shape of child datasets, etc.) They also make mroe use of the existing methods and utilities.
> Refactor `getGroup` in HSDS and Jupyter provider APIs

- src/h5web/App.tsx
- src/h5web/BreadcrumbsBar.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/visualizations/RawVis.module.css
Part of #417. The `BreadcrumbsBar` is now much simpler, since it now has direct access to the path. The path is now the core state of the `App`. It will be used to retrieve the associated `Entity` metadata.
> Lift `selectedPath` state up into App and use in BreadcrumbsBar

- cypress/specs/app.spec.ts
- src/h5web/explorer/EntityList.tsx
- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/mock/MockProvider.tsx
- src/h5web/providers/silx/api.ts
- src/h5web/providers/utils.ts
Part of #417. Now that the `selectedPath` is the core local state of `App`, sub-components will need a way to retrieve the metadata object of any selected entity from its path, not only selected groups. Therefore, I had to reconsider my approach with the `getGroup` API method and `groupsStore` suspense store, and switch to a more generic `getEntity` method and `entitiesStore` suspense store.
From a back-end point of view, `getEntity` still returns the same thing when passed the path of a group (i.e. the metadata of the group and its direct children). However, it now also accepts paths to datasets and datatypes and should return their metadata.
To avoid fetching the same dataset/datatype twice (once when selecting its parent group in the Explorer, and a second time when actually using the …
> Replace `getGroup` with `getEntity` in provider API

- src/h5web/guards.ts
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/hooks.ts
- src/h5web/vis-packs/nexus/models.ts
- src/h5web/vis-packs/nexus/utils.test.ts
- src/h5web/vis-packs/nexus/utils.ts
In `useNxData`, we fetch the values of all of the children of the NXdata group at once and return an object that contains various information about the signal, errors and axes, as well their respective values. This approach is convenient but prevents us from doing more precise fetching of values based on the dimension mapping state for the `Heatmap` and `NxImage` visualizations.
As a first step, I refactor `useNxData` so that it returns the metadata objects of all the relevant datasets without their values. The values are now fetched in the vis containers. This will evolve a bit in the next PR, since we'll need to fetch values based on the dimension mapping state, which is currently managed in the mapped visualizations.
> Refactor `useNxData` so datasets values are fetched separately

- src/h5web/vis-packs/core/containers/HeatmapVisContainer.tsx
- src/h5web/vis-packs/core/containers/LineVisContainer.tsx
- src/h5web/vis-packs/core/containers/MatrixVisContainer.tsx
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/line/MappedLineVis.tsx
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
The dimension mapping state now comes before the calls to `useDatasetValue`, which means we'll be able to pass the current slice's "address" to the hook.
> Move dimension mappers up into containers

- src/h5web/guards.ts
- src/h5web/providers/mock/MockProvider.tsx
- src/h5web/providers/mock/utils.test.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/models.ts
- src/h5web/vis-packs/core/containers/HeatmapVisContainer.tsx
- src/h5web/vis-packs/core/containers/LineVisContainer.tsx
- src/h5web/vis-packs/core/containers/MatrixVisContainer.tsx
- src/h5web/vis-packs/core/containers/RawVisContainer.tsx
- src/h5web/vis-packs/core/containers/ScalarVisContainer.tsx
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/line/MappedLineVis.tsx
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/core/raw/RawVis.tsx
- src/h5web/vis-packs/core/scalar/ScalarVis.tsx
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/hooks.ts
I'll probably be able to use the same approach to infer of types of attribute values.
---
Also, remove the need to pass `mockMetadata` to `findMockEntity` and remove `Metadata` model.
> Infer type of dataset values from HDF5 type/shape instead of asserting

- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/mock/metadata-utils.ts
A refactoring in preparation of #406.
`HDF5FloatType` and `HDF5IntegerType` no longer holds a `base` string but directly the information that can be deduced from it (endianness, number of bits, sign). This will allow a much easier handling in the `JupyterProvider` (for type inferring) and in the `MetadataViewer` (for displaying the HDF5Type of a dataset).
The `base` string is now parsed in the `HsdsProvider` to add the relevant fields to `HDF5Type`. Note that some advanced types that hold reference to other types need to be recursively parsed.
> Change HDF5Type by parsing `base` into object fields

- src/h5web/metadata-viewer/EntityTable.tsx
- src/h5web/metadata-viewer/MetadataViewer.test.tsx
- src/h5web/metadata-viewer/utils.ts
Some examples:
- Scalar dataset with string type
- 2D dataset with integer type
> Adding data type row to the metadata inspector

- src/h5web/dimension-mapper/utils.ts
- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/mock/MockProvider.tsx
- src/h5web/providers/utils.ts
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/hooks.ts
- src/h5web/vis-packs/nexus/utils.ts
- src/react-app-env.d.ts
In order to fetch values by slice, I need to pass an extra `selection` parameter (of the form `0,0,:,:`) along with the entity `path`. I also need the values store to use both the path and the selection as keys when caching results.
`react-suspense-fetch` accepts fetch functions with a single string or object parameter. An object parameter would do the job, but when `react-suspense-fetch` encounters an object parameter, it stores it in a `WeakMap` cache internally, which means that cached results would disappear as soon as the input objects were garbage collected...
The workaround is to stringify an input object before passing it to the store, and then parsing the string back into an object inside the fetch function:
```ts
const store = createFetchStore(async (key: string) => {
const { …
```
> Fetch values by slice in Heatmap and Matrix vis

- .env
- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/heatmap/Mesh.tsx
- src/h5web/vis-packs/core/heatmap/ShadersMesh.tsx
- src/h5web/vis-packs/core/shared/PanZoomMesh.tsx
- src/h5web/vis-packs/core/shared/TooltipMesh.tsx
This is an initial implementation to get things moving. For now, I use the inferno colour map function in the shader (instead of passing the colour map as a texture, as discussed). Also, only the linear scale is supported.
> Start implementing shaders-based heatmap behind flag

- src/h5web/toolbar/controls/DomainSlider.tsx
Fix #444 
Hadn't realised this was our doing 😂 
The use case mentioned in the issue is fixed:
> Don't round domain slider values on change

- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/jupyter/utils.ts
- src/h5web/providers/mock/metadata-utils.ts
- src/h5web/providers/mock/metadata.ts
- src/h5web/providers/mock/values.ts
A step towards #479 as even if not a base type, the boolean can be displayed using the Raw visu:
Glad to have your feedback on this: on one hand, we add the support of the enum type, on the other, it might seem overthought only for booleans.
> Adding boolean type, a subset of enum type

- src/h5web/toolbar/controls/ColorMapSelector.tsx
- src/h5web/vis-packs/core/heatmap/interpolators.ts
Fixes #481.
HSL/HSV are the same thing since we only care about the hue. As discussed, since `Sinebow` is an improved version of `HSL`, I've put the former into the _Common_ group instead of `HSL`.
> Implement HSL color scale

- .env
- src/h5web/toolbar/controls/DomainSlider.tsx
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/heatmap/config.ts
- src/h5web/vis-packs/core/heatmap/hooks.ts
- src/h5web/vis-packs/core/models.ts
Preparation for #510 
I change the `customDomain` state to `[number | undefined, number | undefined]` instead of `Domain | undefined`. This change is required if we want to support auto-scaling the domain bounds independently.
> Refactor Heatmap config to support auto-scaling a single domain bound

- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/ScaledSlider.tsx
Not as straightforward as I was hoping... As a reminder, the initial goal was **to update only the `customDomain` bound that changed after moving a thumb**, so that the other bound could remain `undefined` (and therefore autoscaled) if applicable.
There were a couple of unforeseen challenges that made this more complicated than expected:
- The bound that doesn't change must also **_not_ be updated in `sliderDomain` _during_ the interaction**.
Initially, I had `ScaledSlider` scale-invert both bounds and send the result to `DomainSlider` to set as is as the new `sliderDomain`. The problem is that `sliderDomain` is displayed in the popup (for real-time feedback when moving a thumb), and `scale()` rounds to the nearest integer, so `scale.invert()` doesn't always give back the same value... As …
> Update only the domain bounds that change when interacting with the slider

- src/h5web/toolbar/controls/DomainSlider/BoundEditor.tsx
- src/h5web/toolbar/controls/DomainSlider/BoundErrorMessage.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.module.css
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
The error "unsticks" when the popup is closed because the `BoundErrorMessage` components are rendered conditionally based on  the `open` state.
> Make errors sticky in domain tooltip

- src/h5web/toolbar/controls/DomainSlider/BoundEditor.module.css
- src/h5web/toolbar/controls/DomainSlider/BoundEditor.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.module.css
- src/h5web/vis-packs/core/heatmap/utils.ts
- src/h5web/vis-packs/core/utils.test.ts
- src/h5web/vis-packs/core/utils.ts
First, I change the values used for clamping (previously `Number.EPSILON` and `1 / Number.EPSILON`) to `Number.MIN_VALUE` and `Number.MAX_VALUE / 2`, thus giving users a much wider range of values (but with a precision of 6 significant digits).
Why not `Number.MAX_VALUE`? Because `scaleLinear` does not support domains wider than `Number.MAX_VALUE`:
```ts
const scale = scaleLinear([-Number.MAX_VALUE, Number.MAX_VALUE]).domain([1, 100]);
scale(Number.MAX_VALUE) // => NaN
```
Since allowing domains such as `[-Number.MAX_VALUE, 0]` would make the clamping behaviour non trivial (for us and for users), I decided to just clamp to `[-Number.MAX_VALUE / 2, Number.MAX_VALUE / 2]`.
With this done, I'm able to use `clampBound` in `BoundEditor` to clamp values entered by the user. I also:
- deal with …
> Clamp bounds typed in by user

- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
- src/h5web/toolbar/controls/DomainSlider/ScaledSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/Thumb.tsx
- src/h5web/vis-packs/core/heatmap/utils.ts
- src/h5web/vis-packs/core/models.ts
I've identified two remaining edge cases:
1. Go to http://localhost:3000/mock 
2. Change max bound to `-400` 🡪 `visDomain=[-95, -400]`, so `min > max` and `safeVisDomain=[-95, 400]`. Note that custom max (-400) is much lower than data min (-95), so custom max is still lower than the slider's extent min.
3. Click to the left of the min bound 🡪 the custom min changes to a value still greater than custom max, so `safeVisDomain` and the slider's extent don't change.
4. Click to the left of the min bound again 🡪 the custom min doesn't change or very little, because the slider's extent stays the same after every click.
I don't believe there's a way around this. To restore normal behaviour, the user has to move the max thumb or edit the values manually.
1. Go to http://localhost:3000/mock 
2. …
> Fall back to data domain when min is greater than max

- src/h5web/toolbar/controls/DomainSlider/BoundErrorMessage.tsx
- src/h5web/vis-packs/core/heatmap/utils.ts
- src/h5web/vis-packs/core/models.ts
This resolves scenario 5 described in https://github.com/silx-kit/h5web/issues/510#issuecomment-797402408
To reproduce:
1. Go to http://localhost:3000/mock
2. Switch to log.
3. Enter a custom min value lower than or equal to 0.
4. Enter a custom max between 0 and data min (1), for instance 0.5
This introduces a noteworthy, but still logical, behaviour: in the same state as above, move the max thumb to the right 🡪 the two thumbs don't separate because the new custom max is still lower than data min. You have to move the max thumb again until you go past the data min:
... or instead, push the min thumb to the left with the max thumb so custom min becomes positive.
> Let custom min fall back to custom max in one specific edge case

- .eslintrc.js
- src/h5web/dimension-mapper/DimensionMapper.test.tsx
- src/h5web/explorer/Explorer.test.tsx
- src/h5web/metadata-viewer/MetadataViewer.test.tsx
- src/h5web/metadata-viewer/utils.test.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.test.ts
- src/h5web/providers/jupyter/utils.test.ts
- src/h5web/providers/mock/utils.test.ts
- src/h5web/utils.test.ts
- src/h5web/vis-packs/core/CorePack.test.tsx
- src/h5web/vis-packs/core/pack-utils.test.ts
- src/h5web/vis-packs/core/utils.test.ts
- src/h5web/vis-packs/core/visualizations.test.ts
- src/h5web/vis-packs/nexus/NexusPack.test.tsx
- src/h5web/vis-packs/nexus/pack-utils.test.ts
- src/h5web/vis-packs/nexus/utils.test.ts
- src/h5web/visualizer/Visualizer.test.tsx
Came across this: https://kentcdodds.com/blog/avoid-nesting-when-youre-testing ... and I whole-heartily agree: top-level describe blocks don't add much value when you consider that the file path/name already appears in Jest's output. They increase the nesting level for no good reason.
> Remove top-level describe blocks

- src/h5web/toolbar/MeasuredControl.tsx
- src/h5web/toolbar/Separator.module.css
- src/h5web/toolbar/Separator.tsx
- src/h5web/toolbar/Toolbar.module.css
- src/h5web/toolbar/Toolbar.tsx
- src/h5web/toolbar/controls/ColorMapSelector.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainSlider.module.css
- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/ScaledSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/Thumb.tsx
- src/h5web/toolbar/controls/ScaleSelector/ScaleSelector.tsx
- src/h5web/toolbar/controls/SnapshotButton.tsx
I've created separate commits, which will probably be easier to review.
The gist of it is that the previous implementation did not allow the toolbar controls to be feature tested. We used to render every control twice:
- Once visibly (or in the overflow menu) but only when measured.
- A second time (with `React.clone`) invisibly and disabled in order to measure them (and keep the measurements up to date).
Since JSDom does not support measuring elements, the controls were never "measured" and would remain hidden and disabled. React Testing Library excludes disabled elements when querying, so it would never find any controls in the toolbar.
The new implementation renders every control only once and never disabled. It uses CSS to hide the controls while they are being measured, and once all …
> Make responsive toolbar more efficient and flexible

- .github/workflows/release.yml
- https://github.com/geritol/match-tag-to-package-version/issues/2
- https://github.com/geritol/match-tag-to-package-version/releases/tag/0.1.0
> Use output from `match-tag-to-package-version` action in release workflow

- src/index.tsx
https://reactjs.org/docs/strict-mode.html
I think we weren't using Strict Mode because of the `UNSAFE_componentWillReceiveProps` warnings caused by React-Reflex. Now that it's resolved #578, might as well! I can't see any new warnings yet, which is great 😄
> Render React in Strict Mode

- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/models.ts
- src/h5web/vis-packs/core/hooks.ts
Part of #519 
A significant simplification of the `Value` type, which is used as the return type for the `useDatasetValue` and `useDatasetValues` hooks. Instead of two separate generics (`HDF5Shape` and `HDF5Type`), it now requires only one: `Dataset` (as this type already includes the types of the dataset's HDF5 shape and type).
> Build `Value` type from dataset rather than shape and type

- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.ts
I can simplify the new `HsdsShape` type _a lot_ by being a bit less descriptive of what HSDS returns and by simplifying the conversion to `Shape`.
I'm also able to remove `HDF5Attribute`! 🎉
> Move `HDF5Shape` types to HSDS provider and simplify them

- src/h5web/guards.ts
- src/h5web/metadata-viewer/utils.ts
- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.test.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/jupyter/utils.test.ts
- src/h5web/providers/jupyter/utils.ts
- src/h5web/providers/models.ts
- I add a type called `UnknownType` to catch any type we don't yet support so users can still inspect them in the metadata viewer.
- I stop supporting `HDF5Id` as a valid type since we don't yet have proof that this type is returned by our back-end providers. If we discover that it can, then we'll re-introduce it but in a more meaningful way (e.g. for instance by resolving the datatype in the provider so the front doesn't "see" the ID).
> Allow inspection of unknown types

- src/h5web/guards.ts
- src/h5web/metadata-viewer/utils.ts
- src/h5web/providers/hdf5-models.ts
- src/h5web/providers/hsds/models.ts
- src/h5web/providers/hsds/utils.test.ts
- src/h5web/providers/hsds/utils.ts
- src/h5web/providers/jupyter/utils.test.ts
- src/h5web/providers/jupyter/utils.ts
- src/h5web/providers/mock/metadata-utils.ts
I wasn't able to go as far as I'd planned by replacing the union of HDF5 types with `interface HDF5Type { class: HDF5TypeClass; }`. This led to some issues, notably when using `HDF5Type` as a return type of the provider's conversion functions. I realised that the significant benefit of a type union `A | B | C` is that TypeScript is able to infer the sub-types `A`, `B` and `C` inline, without the need for type guards.
So I've made only two changes:
1. I've merged a few HDF5 type interfaces together:
- `HDF5FloatType` and `HDF5IntegerType` are now represented with a single `HDF5NumericType` interface.
- Unsigned integers now have their own `HDF5TypeClass` entry and are also represented with `HDF5NumericType`.
- `HDF5VLenType` is now represented by `HDF5ArrayType` (by making the latter's …
> Simplify HDF5 types and separate out HDF5 from HSDS type classes

- src/h5web/metadata-viewer/AttributeValueLink.tsx
- src/h5web/metadata-viewer/AttributesTable.tsx
- src/h5web/metadata-viewer/MetadataViewer.module.css
Fix #582 
Not a huge fan of the resulting code, I may have missed a simpler solution. Perhaps I need my :coffee: :smile: 
**Before:**
**After:**
> Followable attributes array members can be used for navigation

- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/heatmap/hooks.ts
- src/h5web/vis-packs/core/heatmap/utils.ts
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/line/LineVis.tsx
- src/h5web/vis-packs/core/line/hooks.ts
- src/h5web/vis-packs/core/models.ts
- src/h5web/vis-packs/core/shared/TooltipMesh.tsx
As mentioned, I move the tooltip formatters into custom hooks. I think it's a lot cleaner, since it also moves the creation of the scales that are specifically used for the tooltips.
I also fix performance bottlenecks in the Heatmap: `getPixelEdges` and `getValueToIndexScale` weren't wrapped in `useMemo`, so they were probably slowing down slicing through big image stacks significantly (since they both loop through the abscissas/ordinates arrays, which don't change when slicing). Do we have a large image stack somewhere? The one at `/entry_0000/0_measurement` in the `water` file that I usually use is unavailable because of compression. 😢
> Create tooltip formatters in custom hooks and fix perf issues on Heatmap

- src/h5web/metadata-viewer/MetadataViewer.tsx
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/mock/utils.test.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/models.ts
- src/h5web/utils.ts
- src/h5web/vis-packs/VisPackChooser.tsx
- src/h5web/vis-packs/nexus/NexusPack.test.tsx
- src/h5web/vis-packs/nexus/pack-utils.ts
Fix partially #618 for mock and HSDS providers.
I throw a specific error message, `ProviderError.NotFound`, from the mock and HSDS providers, which I catch from the calls to `entitiesStore.get(path)`. I then rethrow a more specific error that can be caught by the error boundary and displayed to the user.
Three error cases are now properly handled with the mock and HSDS providers:
1. In "Display", when the default path is not found (`getDefaultEntity` in `NexusPack`).
2. In "Inspect", when the user follows a default path that is not found (`MetadataViewer`).
3. In "Display", when the user switches back from the `MetadataViewer` after following a path that was not found (`VisPackChooser`).
> Improve error handling when entity is not found

- src/h5web/providers/hsds/api.ts
A temporary fix to work around https://github.com/HDFGroup/hsds/issues/87
To be removed when the issue is solved in HSDS.
> Fix HSDS responses containing NaN (which is invalid JSON)

- src/h5web/toolbar/controls/DomainSlider/DomainSlider.test.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/utils.ts
Fix #636 
I had some inconsistent test failures locally on the `DomainSlider` but it passes on the CI...
@axelboc can you try on your end to see if tests are passing ?
> Avoid recomputing bounds on scaleType changes

- src/h5web/providers/hsds/api.ts
Linked to:
* https://github.com/HDFGroup/hsds/issues/87
* https://github.com/HDFGroup/hsds/issues/88
> Fix errors on Infinity and on slices with integers for HSDS

- src/h5web/App.tsx
- src/h5web/VisConfigProvider.tsx
- src/h5web/dimension-mapper/DimensionMapper.test.tsx
- src/h5web/explorer/Explorer.test.tsx
- src/h5web/metadata-viewer/MetadataViewer.test.tsx
- src/h5web/providers/mock/metadata.ts
- src/h5web/test-utils.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainSlider.test.tsx
- src/h5web/vis-packs/core/CorePack.test.tsx
- src/h5web/vis-packs/core/heatmap/config.tsx
- src/h5web/vis-packs/core/line/config.tsx
- src/h5web/vis-packs/nexus/NexusPack.test.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/hooks.ts
- src/h5web/visualizer/Visualizer.test.tsx
- src/h5web/visualizer/Visualizer.tsx
... so they are not re-rendered every time the user switches to another visualization.
I also:
- moved the prefetching of values and errors into the `useNxData` hook;
- removed the `defaultPath` from `nx_process` as it was previously;
- made sure that the config providers wait until their stores are rehydrated before rendering their children;
- fixed all the tests by wrapping the main `render` of the app in `act`.
> Move config providers higher up in the tree

- src/h5web/toolbar/ComplexToolbar.tsx
- src/h5web/utils.ts
- src/h5web/vis-packs/core/complex/MappedComplexVis.tsx
- src/h5web/vis-packs/core/complex/config.tsx
- src/h5web/vis-packs/core/complex/models.ts
- src/h5web/vis-packs/core/containers/ComplexVisContainer.tsx
- src/h5web/vis-packs/core/containers/index.ts
- src/h5web/vis-packs/core/heatmap/config.tsx
- src/h5web/vis-packs/core/line/config.tsx
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/core/visualizations.test.ts
- src/h5web/vis-packs/core/visualizations.ts
Continuation of work on #310 
Also changed the aspect of imaginary `i` when displaying complex data:
> Added two variants of ComplexVis: phase map and amplitude map

- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
- src/h5web/providers/hsds/api.ts
- src/h5web/providers/jupyter/api.ts
- src/h5web/providers/jupyter/devApi.ts
- src/h5web/providers/mock/api.ts
- src/h5web/vis-packs/core/containers/ComplexVisContainer.tsx
- src/h5web/vis-packs/core/containers/HeatmapVisContainer.tsx
- src/h5web/vis-packs/core/containers/LineVisContainer.tsx
- src/h5web/vis-packs/core/containers/MatrixVisContainer.tsx
- src/h5web/vis-packs/nexus/NexusPack.test.tsx
- src/h5web/vis-packs/nexus/containers/NxComplexContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/visualizer/ValueLoader.tsx
- src/h5web/visualizer/Visualizer.test.tsx
- src/h5web/visualizer/Visualizer.tsx
Retrying a cancelled NeXus vis now works, but leads to a waterfall effect.
The calls to `valuesStore.prefetch` are located in `useNxData`, itself called from the NeXus vis containers. When the error boundary in the container resets, it re-renders its children, not the container itself, so the prefetches aren't triggered and the requests in the mapped vis happen sequential instead of in parallel.
I will fix this behaviour in my next PR by moving the prefetching down into the mapped vis.
---
**UPDATE**
The initial solution had problems with the slicing. The new solution is much better, as it's completely generic.
Everything is done in in the base class of the provider APIs; the containers' error boundaries no longer have to evict requests from the store by passing the right cache keys. The …
> Fix cancelling/retrying in NeXus visualizations

- src/h5web/guards.ts
- src/h5web/providers/jupyter/models.ts
- src/h5web/providers/jupyter/utils.ts
- src/h5web/providers/mock/metadata-utils.ts
- src/h5web/providers/models.ts
- src/h5web/vis-packs/core/ValueFetcher.tsx
- src/h5web/vis-packs/core/VisBoundary.tsx
- src/h5web/vis-packs/core/complex/MappedComplexVis.tsx
- src/h5web/vis-packs/core/containers/ComplexVisContainer.tsx
- src/h5web/vis-packs/core/containers/HeatmapVisContainer.tsx
- src/h5web/vis-packs/core/containers/LineVisContainer.tsx
- src/h5web/vis-packs/core/containers/MatrixVisContainer.tsx
- src/h5web/vis-packs/core/containers/RawVisContainer.tsx
- src/h5web/vis-packs/core/containers/ScalarVisContainer.tsx
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/line/MappedLineVis.tsx
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/core/matrix/MatrixVis.tsx
- src/h5web/vis-packs/core/matrix/utils.ts
- src/h5web/vis-packs/core/models.ts
- src/h5web/vis-packs/core/scalar/ScalarVis.tsx
- src/h5web/vis-packs/core/scalar/utils.ts
- src/h5web/vis-packs/core/utils.ts
- src/h5web/vis-packs/nexus/NxValuesFetcher.tsx
- src/h5web/vis-packs/nexus/containers/NxComplexContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/models.ts
- src/h5web/visualizer/Visualizer.tsx
First, I created a `VisBoundary` component to hold the `ErrorBoundary` and `Suspense` logic of the vis containers. I did not end up moving the `DimensionMapper` into this component, as keeping the mapper in the containers means I could use `VisBoundary` in the `RawVisContainer` and `ScalarVisContainer` and remove `ErrorBoundary` and `Suspense` from `Visualizer`.
Second, I moved all the data fetching (`useDatasetValue(s)`) out of the mapped visualizations and inside two new components: `ValueFetcher` and `NxValuesFetcher`. I used the [render props](https://reactjs.org/docs/render-props.html) pattern, as it is much clearer than my previous state-based solution.
Third, I refactored the way we pass formatters to `ScalarVis` and `MatrixVis`. Instead of having a guard and an early return in the …
> Abstract values fetching out of mapped vis components

- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/line/DataCurve.tsx
- src/h5web/vis-packs/core/line/LineVis.module.css
- src/h5web/vis-packs/core/line/LineVis.tsx
This relates to #631 and #555.
`DataCurve` no longer relies on H5Web's CSS custom properties. The `color` prop is now expected to be a valid color string. I've kept a default value for convenience, but I've chosen `black`. (If we add a `bgColor` prop to the canvas as per https://github.com/silx-kit/h5web/issues/555#issuecomment-821144768, we can use `white` as default.)
The CSS custom properties are now read by `LineVis` on the root `figure` element via a `ref` (instead of on the `canvas` element via `useThree`).
> Read CSS custom property in `LineVis` instead of `DataCurve`

- package-lock.json
- package.json
- src/h5web/providers/hsds/hsds-api.ts
- src/h5web/providers/jupyter/jupyter-api.ts
- src/h5web/providers/jupyter/jupyter-dev-api.ts
- src/h5web/providers/mock/mock-api.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/vis-packs/core/complex/MappedComplexVis.tsx
- src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx
- src/h5web/vis-packs/core/utils.ts
- src/react-app-env.d.ts
Work towards https://github.com/silx-kit/h5web/issues/616#issuecomment-828238108
This means that the `valuesStore` now only stores flattened values.
There are several points I would like to discuss that I highlight below.
> Values are now flattened in providers 

- src/h5web/vis-packs/core/line/LineVis.tsx
- src/stories/Customization.stories.mdx
`--h5w-line-auxColor` now accepts a comma-separated list of colours. If there are more auxiliary curves than colours, then the extra curves receive the last colour in the list.
Here is what the new default auxiliary colors look like:
They are similar to Matplotlib's colors: https://matplotlib.org/stable/_images/dflt_style_changes-1.png.
> Support providing multiple auxiliary curve colors

- CONTRIBUTING.md
- packages/webpack.config.js
- src/h5web/breadcrumbs/BreadcrumbsBar.module.css
- src/h5web/explorer/Explorer.module.css
- src/h5web/metadata-viewer/MetadataViewer.module.css
- src/h5web/toolbar/Toolbar.module.css
- src/h5web/toolbar/controls/ColorMapSelector/ColorMapSelector.module.css
- src/h5web/toolbar/controls/ColorMapSelector/ColorMapSelector.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.module.css
- src/h5web/utils.module.css
- src/h5web/vis-packs/core/heatmap/ColorBar.module.css
- src/h5web/vis-packs/core/heatmap/ColorBar.tsx
- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/matrix/MatrixVis.module.css
- src/h5web/vis-packs/core/shared/VisCanvas.module.css
- src/h5web/visualizer/ValueLoader.module.css
- src/h5web/visualizer/VisSelector.module.css
- src/h5web/visualizer/Visualizer.module.css
- src/styles/base.css
Global utility classes are problematic when importing components in other apps. They require importing global CSS, which isn't ideal in terms of namespacing and developer experience.
We had four global utility classes: `btn-clean`, `btn-link`, `no-invert` and `no-invert-canvas`. For the first two, I move them into a CSS module: `src/h5web/utils.module.css` so they become locally scoped. For the last two, since `jupyterlab-h5web` has to be able to write selectors targeting them, they cannot be locally scoped -- so instead of moving them into a CSS module, I replace them with `data-` attributes: `data-keep-colors` and `data-keep-canvas-colors`.
> Remove global utility classes

- src/h5web/toolbar/controls/DomainSlider/BoundEditor.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
This PR fixes the following bug: 
1. Start editing min or max bound in domain tooltip.
2. Don't apply the edit -- instead, close the tooltip with Escape or by clicking outside of it.
3. Re-open the tooltip 👉 the field is no longer in edit mode and the edited value isn't applied, yet the field shows the edited value.
> Cancel bound editors when closing domain tooltip

- src/h5web/breadcrumbs/BreadcrumbsBar.tsx
- src/h5web/toolbar/ComplexLineToolbar.tsx
- src/h5web/toolbar/ComplexToolbar.tsx
- src/h5web/toolbar/HeatmapToolbar.tsx
- src/h5web/toolbar/LineToolbar.tsx
- src/h5web/toolbar/controls/ColorMapSelector/ColorMapSelector.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
- src/h5web/toolbar/controls/GridToggler.tsx
- src/h5web/toolbar/controls/ToggleBtn.tsx
- src/packages/lib.ts
- src/stories/GettingStarted.stories.mdx
- src/stories/Toolbar.stories.tsx
- Add `Toolbar` and the main controls to `@h5web/lib`, as well as a couple more hooks and models.
- Create `GridToggler` control and expose to `@h5web/lib`.
- Document toolbar usage in storybook.
- Rename prop `onChange` of `ToggleBtn` to `onToggle`.
> Add toolbar components to lib package and document

- src/h5web/toolbar/OverflowMenu.tsx
`useClickAway` was triggered when clicking the button. Not sure why it was working in H5Web before 🤷
> Fix overflow menu not opening

- src/h5web/vis-packs/core/shared/Html.tsx
- src/h5web/vis-packs/core/shared/PanZoomMesh.tsx
- src/stories/HeatmapVis.stories.tsx
Implements `calculatePosition` from https://github.com/pmndrs/drei/blob/v6.0.3/src/web/Html.tsx
This is a prop that can be overridden which is needed for `AxisSystem` and `Tooltip` that should not move.
> Make `Html` move according to camera

- src/h5web/vis-packs/core/shared/Html.tsx
- src/stories/HeatmapVis.stories.tsx
Follow-up of #695 
Simplified version of the [scaling of drei's Html](https://github.com/pmndrs/drei/blob/v6.0.3/src/web/Html.tsx#L269) as we only support Orthographic Camera.
> Allow Html to scale according to the camera zoom

- src/h5web/vis-packs/core/line/LineVis.tsx
- src/h5web/vis-packs/core/shared/Annotation.tsx
- src/packages/lib.ts
- src/stories/HeatmapVis.stories.tsx
- src/stories/LineVisDisplay.stories.tsx
`Annotation` is a simple wrapper around `Html` that takes vis coordinates instead of canvas coordinates.
> Add Annotation component and allow children in LineVis

- src/h5web/vis-packs/core/shared/Axis.tsx
- src/h5web/vis-packs/core/shared/AxisSystem.module.css
> Add thin axis line when grid is not displayed

- packages/webpack.config.js
Three is a peer dependency of R3F, so we need to also make it an explicit dependency.
> Mark Three as dep/external of packages

- src/h5web/breadcrumbs/Breadcrumbs.tsx
- src/h5web/breadcrumbs/BreadcrumbsBar.tsx
- src/h5web/explorer/Explorer.tsx
- src/h5web/metadata-viewer/EntityTable.tsx
- src/h5web/providers/Provider.tsx
- src/h5web/providers/context.ts
With https://github.com/silx-kit/jupyterlab-h5web/issues/37 next release, the filepaths in h5web can be absolute and therefore quite lengthy. I think it would be prettier to show only the filename and not the full path, which is the point of this PR.
**Before:**
**After:**
> Show file name instead of file path in headings

- src/h5web/guards.ts
- src/h5web/providers/models.ts
- src/h5web/toolbar/RgbVisToolbar.tsx
- src/h5web/utils.test.ts
- src/h5web/utils.ts
- src/h5web/vis-packs/VisPackChooser.tsx
- src/h5web/vis-packs/core/VisBoundary.tsx
- src/h5web/vis-packs/core/containers/RgbVisContainer.tsx
- src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx
- src/h5web/vis-packs/core/rgb/RgbVis.tsx
- src/h5web/vis-packs/core/rgb/config.tsx
- src/h5web/vis-packs/core/visualizations.test.ts
- src/h5web/vis-packs/core/visualizations.ts
- src/h5web/vis-packs/nexus/pack-utils.ts
- src/h5web/vis-packs/nexus/utils.test.ts
- src/h5web/vis-packs/nexus/utils.ts
Work towards #649 :see_no_evil: 
For now, works only for RGB images and only datasets with 3 dimensions, integers dtype and a `CLASS=IMAGE` attribute are interpreted as such.
Future PRs will widen the support but supporting the full specification is out of scope in my opinion.
> Add RgbImageVis for RGB Image of HDF5 spec

- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/line/LineVis.tsx
- src/h5web/vis-packs/core/shared/Annotation.tsx
- src/h5web/vis-packs/core/shared/Html.tsx
- src/stories/HeatmapVis.stories.tsx
- src/stories/LineVisDisplay.stories.tsx
Big refactoring, but worth it, I think. It's no longer the outer element that is transformed around the canvas, but the inner element. The outer element now takes the whole size of the canvas, which means it now has to have the `pointer-events: none`. This revealed an event propagation regression with the tooltip, which was easily fixed. Most importantly, I find that it makes the roles of all the `useLayoutEffect`, `useEffect` and `useFrame` hooks a lot clearer (as demonstrated by the fact that we no longer need to disable ESLint because of missing hook dependencies).
> Prevent HTML annotations from overflowing canvas

- src/h5web/providers/h5grove/h5grove-api.ts
Technically, the API is meant to be compatible with `jupyterlab_h5web`'s backend that is based on `h5grove`... 
We could rename it into `JupyterlabH5Web` API but that's lengthier and we already have a `JupyterProvider` so we would need a **lot** of renames...
> Update h5grove API to pass filename as query arg

- src/h5web/explorer/EntityList.tsx
- src/h5web/guards.ts
- src/h5web/providers/Provider.tsx
- src/h5web/providers/h5grove/h5grove-api.ts
- src/h5web/providers/hsds/hsds-api.ts
- src/h5web/providers/jupyter/jupyter-api.ts
- src/h5web/providers/mock/metadata-utils.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/providers/models.ts
- src/h5web/utils.ts
- src/h5web/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxComplexSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxImageContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxRgbContainer.tsx
- src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- src/h5web/vis-packs/nexus/pack-utils.ts
- src/h5web/vis-packs/nexus/utils.ts
Something I'd been meaning to do for a while.
- When a group is fetched directly with `api.getEntity('/path/to/group')`, its children are also fetched. The group entity must therefore include a `children` array (which may be empty if the group doesn't actually have children).
- When fetching a group's children, if a child group is encountered, then this child group's own children are _not_ fetched. The child group entity must therefore _not_ include a `children` array.
This PR aims at making this behaviour clearer in the codebase by enforcing stricter type checking when accessing the `children` property of a group. It also adds runtime type checking, notably after `api.getEntity` to make sure provider APIs never return a group without a `children` property. Additionally, providers can now …
> Enforce stricter types for groups with/without children

- src/h5web/providers/h5grove/h5grove-api.ts
- src/h5web/providers/h5grove/models.ts
- src/h5web/providers/h5grove/utils.ts
- src/h5web/providers/jupyter/jupyter-api.ts
- Add attributes values cache.
- Prevent re-fetching children metadata in `processEntity`.
- Rename types and methods.
The code is now practically the same in both providers, which is a great sign. 😄 Now we can focus on improving H5Grove by transferring flat, binary arrays with support for NaN/Infinity.
> Bring H5Grove API in line with Jupyter API

- package-lock.json
- package.json
- src/h5web/guards.ts
- src/h5web/providers/mock/utils.ts
- src/h5web/vis-packs/core/complex/hooks.ts
- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/hooks.ts
- src/h5web/vis-packs/core/line/LineVis.tsx
- src/h5web/vis-packs/core/matrix/MatrixVis.tsx
- src/h5web/vis-packs/core/matrix/config.tsx
- src/h5web/vis-packs/core/matrix/utils.ts
- src/h5web/vis-packs/core/rgb/utils.ts
- src/h5web/vis-packs/core/utils.ts
- src/stories/GettingStarted.stories.mdx
- src/stories/HeatmapVis.stories.tsx
- src/stories/LineVisDisplay.stories.tsx
- src/stories/LineVisScales.stories.tsx
I was able to merge https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53728#issuecomment-878220724. Unfortunately, the PR did not receive any review from maintainers of `@types/ndarray` or `@types/numjs`. Let's hope people are happy with the changes once they upgrade...
Previously, `NdArray` or `NdArray<number>` meant that the underlying data could either be `number[]` or a typed array (`Float32Array` and the like), which is why we always had to cast: `myArr.data as number[]`.
The main change now is that the generic describes the exact type of the underlying data stored in the ndarray - e.g. `NdArray<number[]>` (note the `[]`), `NdArray<TypedArray>`, `NdArray<Float32Array>`, etc. With `NdArray<number[]>`, the type of `myArr.data` no longer includes typed arrays -- only `number[]` -- …
> Upgrade @types/ndarray

- package.json
- src/h5web/toolbar/controls/DomainSlider/ErrorMessage.tsx
- src/h5web/toolbar/controls/DomainSlider/ScaledSlider.tsx
- src/h5web/toolbar/controls/ScaleSelector/ScaleOption.tsx
- src/h5web/toolbar/controls/ScaleSelector/SqrtIcon.tsx
- src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx
- src/h5web/vis-packs/core/heatmap/utils.ts
- src/h5web/vis-packs/core/models.ts
- src/h5web/vis-packs/core/scales.ts
- src/h5web/vis-packs/core/utils.test.ts
- src/h5web/vis-packs/core/utils.ts
Fix #740 
This includes some refactorings. There was several problems with our implementation of scales:
1. **Adding a new scale requires to modify many files** as scale parameters (labels, icons, shaders...) are scattered
2. **The treatment of unsupported values is highly specific to the log** (i.e. supported value means `value > 0`) hampering the addition of scales with other supported values (namely, the square root that supports `value >= 0`) 
3. Combination of the two points above: **Treatment of unsupported values is scattered in many places**.
I address 1. by adding a single record `H5WEB_SCALES` that holds all the scale parameters and is indexed by the `scaleType`.
I address 2. by moving the `support` logic inside the record `H5WEB_SCALES`. I introduce `supportedDomain` which is …
> Implement Square root scale

- src/h5web/metadata-viewer/utils.ts
- src/h5web/utils.ts
- src/h5web/vis-packs/core/matrix/MatrixVis.module.css
- src/h5web/vis-packs/core/matrix/utils.ts
- src/h5web/vis-packs/core/scalar/utils.ts
- src/stories/MatrixVis.stories.tsx
I got side-tracked working on the tooltip. 😄 I was trying to collocate all the D3 formatters in `h5web/utils` so we could have the format specifiers all in one place and keep our sanity.
Here, I do so for the complex formatters used by the scalar vis, matrix vis and metadata viewer. I refactor the code that creates these formatters so we no longer have to pass specifiers around multiple functions.
I also did the following to improve the display of the matrix vis:
- I replaced the fancy `i` for imaginary numbers with a simple `i` with a space before it. The fancy `i` just looked off. I find the normal `i` works better, especially with that extra space to give it some breathing room.
- I centered the values inside the cells of the Matrix vis, since the formatters (and monospace font) …
> Refactor formatting of complex numbers

- src/h5web/toolbar/controls/DomainSlider/BoundEditor.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
- src/h5web/utils.ts
- src/h5web/vis-packs/core/heatmap/ColorBar.tsx
- src/h5web/vis-packs/core/heatmap/HeatmapVis.module.css
- src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx
- src/h5web/vis-packs/core/heatmap/hooks.ts
- src/h5web/vis-packs/core/heatmap/models.ts
- src/h5web/vis-packs/core/line/LineVis.module.css
- src/h5web/vis-packs/core/line/LineVis.tsx
- src/h5web/vis-packs/core/line/hooks.ts
- src/h5web/vis-packs/core/line/models.ts
- src/h5web/vis-packs/core/models.ts
- src/h5web/vis-packs/core/shared/TooltipMesh.module.css
- src/h5web/vis-packs/core/shared/TooltipMesh.tsx
- src/h5web/vis-packs/core/utils.ts
- src/stories/HeatmapVisDisplay.stories.tsx
- src/stories/LineVisDisplay.stories.tsx
- src/stories/VisCanvasInteraction.stories.tsx
`HeatmapVis` and `LineVis` both accept a `renderTooltip` function that receives the tooltip's current coordinates, indices and abscissa/ordinate values. This allows the content of the tooltip to be customised (fix #757).
> Add support for custom tooltips

- src/h5web/providers/h5grove/h5grove-api.ts
- src/h5web/providers/utils.ts
See https://github.com/silx-kit/h5web/issues/618#issuecomment-875431360 and https://github.com/silx-kit/h5grove/issues/24
This can be merged before or after the latest version of H5Grove is deployed, it doesn't matter.
> Improve error message when entity is not found with H5Grove

- src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx
- src/h5web/vis-packs/core/utils.test.ts
- src/h5web/vis-packs/core/utils.ts
Fixes HSDS issues reported in https://github.com/silx-kit/h5web/issues/641#issuecomment-894235661:
> :x: LineVis show a blank canvas even for slices containing only valid values
> :x: Computation of the domain in the HeatmapVis yields NaN or Infinity values
Also pixels with `NaN` are not considered as unsupported in `HeatmapVis`:
> Do not support NaN in domain computation and shaders

- package-lock.json
- src/h5web/providers/h5grove/h5grove-api.ts
- src/h5web/providers/utils.test.ts
- src/h5web/providers/utils.ts
To fix https://github.com/silx-kit/jupyterlab-h5web/issues/45
The raw URL `/meta/?file=stack+.h5&path=/` was unchanged. 
The `file` arg gets interpreted as  `stack .h5` by `h5grove`.
The URL `/meta/?file=stack+.h5&path=/` gets encoded as `/meta/?file=stack%2B.h5&path=%2F`. 
The `file` arg gets interpreted as  `stack+.h5` by `h5grove`.
> Encode query parameters in `H5GroveProvider`

- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.module.css
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
- src/h5web/toolbar/controls/DomainSlider/Histogram.module.css
- src/h5web/toolbar/controls/DomainSlider/Histogram.tsx
- src/h5web/vis-packs/core/models.ts
- src/stories/Customization.stories.mdx
- src/stories/DomainSlider.stories.tsx
- src/stories/decorators/Center.tsx
- src/styles/vars.css
First step of #758.
The histogram is really basic for now: no interplay with the current scaleType nor the current slider domain. It simply displays what is given in the `histogram` prop of the `DomainSlider`
> Add optional histogram to DomainSlider in the tooltip

- src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx
- src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx
- src/h5web/toolbar/controls/DomainSlider/Histogram.tsx
- src/h5web/vis-packs/core/models.ts
- src/stories/DomainSlider.stories.tsx
Also tuned `Axis` aspect as in https://github.com/silx-kit/h5web/commit/a522f25f9086ee6a3690ddb06dda4c47cf634005
Leaving indicators for the next PR
> Histogram extension match the slider extension if bigger than data domain

- src/h5web/toolbar/controls/DomainSlider/Histogram.module.css
- src/h5web/toolbar/controls/DomainSlider/Histogram.tsx
- src/h5web/toolbar/controls/DomainSlider/HistogramIndicators.tsx
- src/stories/Customization.stories.mdx
- src/styles/vars.css
Not a huge fan of the `Min`/`Max` legend in silx so I tried to add another type of visual indicator on the limit lines. Tell me if think that is fine or if that looks too much like a golf course :golf:
> Added indicators for slider domain in histogram

- src/h5web/vis-packs/core/matrix/MatrixVis.module.css
- src/h5web/vis-packs/core/shared/VisCanvas.module.css
This should fix the issue with long names on Jupyter Lab. The problem was actually caused by a feedback loop with the sizing of the visualizations. Taking the visualizations out of the flow with `position: absolute` seems to solve the issue.
> Fix vis sizing feedback loop in some contexts

- src/h5web/providers/Provider.tsx
- src/h5web/providers/api.ts
- src/h5web/providers/context.ts
- src/h5web/providers/h5grove/h5grove-api.ts
- src/h5web/providers/hsds/hsds-api.ts
- src/h5web/providers/jupyter/jupyter-api.ts
- src/h5web/providers/mock/mock-api.ts
- src/h5web/providers/models.ts
- src/h5web/providers/utils.test.ts
- src/h5web/providers/utils.ts
Common encoding issues (such as not including `undefined` fields) were not solved by #774. Using axios avoid reimplementing fixes for such issues.
Also, the encoding was extended to all providers and not solely `h5grove`.
> Encode query params with axios

- src/h5web/toolbar/MeasuredControl.tsx
- src/h5web/toolbar/Toolbar.module.css
- src/h5web/toolbar/Toolbar.tsx
The controls have a tendency to jump in and out of the overflow menu when switching back and forth between a shorter and longer option in a selector control - e.g. between "Log" and "Square root" in a scale selector. This shifts the position of the controls in the toolbar (including the one being interacted with), which can be annoying:
**This PR fixes this issue by storing only the largest known width of each control.** This is done by ignoring new measurements of a control if they are shorter than the measurement already present in the state.
This change has the side-effect of decreasing **by half** the number of renders of the `Toolbar` used in `HeatmapToolbar`. Indeed, until now, we weren't checking if a measured width had changed before updating the state, which was triggering a lot …
> Fix controls jumping in/out of overflow menu and refactor controls measuring flow

- src/h5web/toolbar/ComplexToolbar.tsx
- src/h5web/toolbar/HeatmapToolbar.tsx
- src/h5web/vis-packs/core/complex/config.tsx
- src/h5web/vis-packs/core/complex/models.ts
- src/h5web/vis-packs/core/heatmap/config.tsx
Another case of the toolbar controls moving in/out of the overflow menu occurs when changing the scale type on the heatmap/complex vis:
When I switch the `scaleType`, the `dataDomain` in the config store gets reset to `undefined`, which leads to the domain slider being unmounted in the toolbar. The space left by the slider is given to the "Screenshot" button, which was previously hidden in the overflow menu. When the `dataDomain` is recomputed and the `useEffect` that updates it in the store is called, the domain slider is re-mounted and the "Screenshot" button goes back in the overflow menu.
I scratched my head a lot to try to fix this in the toolbar (either in `Toolbar` or in `HeatmapToolbar`/`ComplexToolbar`), but it went nowhere. The problem is not with the toolbar, it is with …
> Prevent flickering of controls when switching scale type of Heatmap

- src/h5web/vis-packs/core/complex/utils.ts
- src/h5web/vis-packs/core/models.ts
- src/h5web/vis-packs/core/utils.test.ts
- src/h5web/vis-packs/core/utils.ts
> SqrtScale: use positive min rather than 0 when domain crosses 0

- src/h5web/toolbar/controls/DomainSlider/Histogram.tsx
- src/stories/DomainSlider.stories.tsx
The domain of the histogram x axis is given by the combination of the slider domain and of the data domain. 
if the domain of bins is not contained in the slider domain or the data domain, the histogram can then overflow (reminder: the parent `svg` has `overflow: visible` to show the axes) :
Note that this occurs if the bin domain is not included in the data domain. This should not occur as normally, when computing a histogram of the data, the bins are spread along the data values. But this is not enforced in h5web.
I could have added a group with `clip-path="view-box"` as mentioned in https://github.com/silx-kit/h5web/pull/771#discussion_r685932539 to clip the overflowing histogram:
But depending on the chosen data domain, the histogram can be really zoomed-in and is only discoverable by …
> Consider domain of bins when computing domain of histogram x axis

- apps/storybook/src/HeatmapVis.stories.tsx
- apps/storybook/src/LineVis.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/utils.test.ts
- packages/lib/src/vis/utils.ts
> Allow descending values in abscissas and ordinates of Heatmap and LineVis

- CONTRIBUTING.md
- packages/app/README.md
- packages/app/package.json
Fix #832 
We had problems testing yesterday because we forgot to run `pnpm packages && pnpm packages:dts`, so VSCode couldn't find the type declarations.
That being said, we cannot test the new exports in the demo because CRA still uses webpack 4, which doesn't look at the `exports` field in `package.json`. This feature is supported only by webpack 5. So we'll have to publish a beta to try it out.
> Add package.json exports for stylesheets in app package

- packages/app/src/breadcrumbs/BreadcrumbsBar.module.css
As I wanted to copy the path by clicking on the copy icon, I realized that the icon was quite shy:
I changed the CSS a bit so that the icon is included in the crumb and is more easily "catchable"
_PS: Yes, I know I could click directly on the crumb but my brain forced me to click on the icon_
> Make copy path button more "catchable"

- packages/app/src/providers/Provider.tsx
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/hsds/utils.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/vis-packs/core/hooks.ts
`getValue`'s `params` parameter now contains a complete `dataset` object instead of just a dataset `path`. This will allow me later to statically type the return value of `getValue` to `Value<D>` instead of `unknown`.
> Simplify `getValue` signature to prepare for stricter typing

- packages/app/src/vis-packs/core/ValueFetcher.tsx
- packages/app/src/vis-packs/core/hooks.ts
This is as far as I'll go.
I did a POC to try to go further (i.e. to move `assertDatasetValue` to the providers' `getValue` methods): https://github.com/silx-kit/h5web/compare/types...poc
However, it doesn't make the code any more statically safe -- it's still a runtime check, just at a different place, and the impact on the code is significant due to the `Context` boundary. So I'm not going to open a PR -- I just thought you might be interested in seeing how I managed to follow this person's advice to type the context with a generic: https://hipsterbrown.com/musings/musing/react-context-with-generics/
> Enforce non-null shape statically when fetching dataset value

- apps/demo/src/H5GroveApp.tsx
- apps/demo/src/HsdsApp.tsx
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/h5grove/h5grove-api.ts
Developing our own provider outside of the h5web monorepo is quite challenging, as most of the required components, models and utilities are not exposed. Since the change to `H5GroveProvider` required to make the future H5Viewer work is very small, I decided to set up a small testing app here as a proof of concept. Once this is confirmed to work, we can remove the test app and merge this PR. We'll then be able to use the `H5GroveProvider` directly in https://gitlab.esrf.fr/ui/h5web-viewer
---
1. Set the `REACT_APP_H5VIEWER_URL` env var to the URL provided by @antolinos in the chat, and then start the dev server.
2. Visit the data portal test URL, also provided by @antolinos, making sure to pass the following query param: `h5viewerURL=http://localhost:3000/h5viewer`
3. Log in, expand a …
> Allow passing custom query params to H5GroveProvider

- packages/app/src/explorer/EntityItem.tsx
- packages/app/src/explorer/NxBadge.tsx
- packages/app/src/explorer/utils.ts
Part of #807 
Here I'm dealing with the NX badge case. I introduce an `NxBadge` component that I wrap with error/suspense boundaries. I give these boudaries empty fallbacks so that the NX badges load silently, and also fail silently in the event of network errors.
For the moment, it's difficult to see whether our NX badge heuristics lead to an appropriate number of requests. We'll have to wait until we no longer fetch any attribute values ahead of time before we can tweak things.
> Fetch attribute values on demand for NX badges in explorer

- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/explorer/utils.ts
- packages/app/src/providers/Provider.tsx
- packages/app/src/providers/context.ts
- packages/app/src/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxRgbContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/app/src/visualizer/utils.ts
- packages/shared/src/mock/metadata.ts
Part of #807 
I add a new `attrValuesStore.getSingle()` method that allows retrieving the value of a specific attribute. It still fetches the values of all the attributes, but it returns only the value of the attribute we're interested in. Moreover, the fetch only happens if we know that the attribute exists.
Also, as per our discussion in the meeting this morning, I know consider that a group without a `signal` attribute is _not_ an `NXdata` group. I even check this first, before the value of the `NX_class`, so that we don't bother fetching the attribute values at all if the entity has no `signal` attribute. As a result of this change, if an entity has an `NXdata` class but no `signal` attribute, we no longer show the "Expected `signal` attribute` error -- we show the "no vis" fallback …
> Fetch `NX_class` on demand when checking if entity is `NXdata` group

- packages/app/src/providers/h5grove/h5grove-api.ts
This made the HeatmapVis crash for arrays where the binary fetching is not supported (e.g. `int64` dtype)
> Fix ignored selection in h5grove fetchData

- packages/app/src/ErrorFallback.tsx
- packages/app/src/explorer/EntityList.tsx
- packages/app/src/explorer/utils.ts
- packages/app/src/metadata-viewer/MetadataViewer.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/context.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/providers/utils.ts
- packages/app/src/vis-packs/core/visualizations.test.ts
- packages/app/src/vis-packs/core/visualizations.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/app/src/visualizer/Visualizer.tsx
- packages/app/src/visualizer/utils.ts
- packages/shared/src/utils.ts
This simplifies things a bit. We no longer have to wrap `entitiesStore.get()` with `handleError`, or create a `getEntity` function in `Visualizer` to pass to `resolvePath`.
> Let providers throw user-facing errors

- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.module.css
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/utils.ts
Friday POC to fix #508, which has been open for a long time.
I pass the dataset type object (`NumericType`) from the container down to the visualization so it can be displayed in the tooltip, next to the hovered value. I let the tooltip's render prop convert the type to a readable string. It seems more straightforward, from a naming point of view, to do it this way than to format the readable string in the container and pass that down to the visualization.
I've only done `LineVisContainer` as a proof of concept for now:
> Show readable dtype in tooltip

- packages/app/src/providers/Provider.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/context.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/lib/src/index.ts
- packages/lib/src/toolbar/controls/ExportMenu.tsx
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/toolbar/controls/Selector/Selector.tsx
Fix #35
- `MatrixVis` : CSV ✅, NPY ✅
- `LineVis` : CSV ✅, NPY ✅
- `HeatmapVis` : NPY ✅ TIFF ✅ (already done in #885)
The export links/buttons sit inside a drop-down menu (similar to a `Selector` but without any selection management). When the `selection` is defined, the menu reads "Export slice"; otherwise, just "Export".
The API method `getTiffUrl` has been generalized to handle other formats. It is now called `getExportURL`. Providers may implement this method but return `undefined` for any unsupported formats. The `ExportMenu` will display download links only for supported formats.
For NeXus visualizations, contrary to what I had initially written in https://github.com/silx-kit/h5web/issues/35#issuecomment-985365726 (now edited), it was simpler to implement the export of the signal …
> Add controls to export dataset or slice to NPY and CSV

- packages/app/src/metadata-viewer/MetadataTable.tsx
- packages/app/src/providers/Provider.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/context.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/lib/src/index.ts
- packages/lib/src/toolbar/controls/DownloadBtn.tsx
- packages/lib/src/toolbar/controls/ExportMenu.tsx
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/toolbar/controls/Selector/Selector.tsx
- packages/lib/src/toolbar/controls/SnapshotButton.tsx
Fix #35 
The feature detection is actually quite simple: I've discovered that an abstract class can have an optional method! So if the provider implements the method, it is defined; otherwise it isn't. This means that the toolbar can just check if `getTiffUrl` is defined to decide whether to show the export button.
I've provided a tentative implementation of the method for H5Grove. It returns a URL of this form: `https://<h5grove.url>/tiff/?<axios-params>&path=/foo&selection=0:,:`. Up to H5Grove to then respond at this URL with the TIFF data and the correct `Content-type` HTTP header (`image/tiff`).
---
I've merged #890 into this branch, so now it includes CSV and NPY exports as well.
> Add "Export" menu to toolbars with CSV/NPY/TIFF exports

- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
Since [h5grove@0.0.12](https://github.com/silx-kit/h5grove/releases/tag/v0.0.12), it is possible to request a flattened array by setting the query parameter `flatten` to `true`.
The `flatten` has no effect for scalar datasets.
> Flatten arrays in backend in h5grove

- packages/lib/src/vis/shared/VisCanvas.tsx
I've opened a discussion thread on R3F's repo that explains what's going on: https://github.com/pmndrs/react-three-fiber/discussions/1906
> Optimise debouncing of re-renders on resize

- apps/storybook/src/Utilities.stories.mdx
- packages/app/src/visualizer/VisManager.tsx
- packages/app/src/visualizer/Visualizer.module.css
- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
- packages/lib/src/vis/shared/VisCanvas.module.css
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/utils.test.ts
- packages/lib/src/vis/utils.ts
The goal is to avoid unnecessary re-renders of the heatmap vis' canvas when the layout is `fill` or `cover` (which is always the case in @h5web/app).
To make this behaviour a bit more readable, I actually reworked a few things:
- I merged `computeVisSize` and `useVisSize` into a single `getSizeToFit`, which takes an `availableSize` and a `ratioToRespect`.
- I moved the axis offsets padding to the measured container (now called `canvasArea` instead of `visArea`), removed the early return, etc.
As mentioned in a comment, one issue is that when the layout changes to/from `contain` dynamically (i.e. when the `canvasRatio` prop of `VisCanvas` changes between a number and `undefined`), the measuring either doesn't start (and nothing gets rendered), or doesn't stop (everything keeps re-rendering …
> Measure canvas area only when a specific canvas ratio is requested

- apps/demo-cra-lib/package.json
- apps/demo/package.json
- apps/storybook/package.json
- eslint.shared.js
- package.json
- packages/app/package.json
- packages/app/src/breadcrumbs/CopyableCrumb.tsx
- packages/app/src/providers/mock/mock-api.ts
- packages/lib/package.json
- packages/shared/package.json
- pnpm-lock.yaml
See:
- https://github.com/ljosberinn/eslint-config-galex/releases/tag/v3.3.6
- https://github.com/ljosberinn/eslint-config-galex/issues/515
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid
> Use void to mark promises that don't need to be awaited

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.ts
Related to #915 
In our entity model, there is a `link` model but we didn't make use of it in the h5grove provider.
This PR adds the parsing of soft and external links responses to fill the `link` field of entities. 
For now, I did not change the model of entity but I think it will worth discussing if links should be first-class entities or not.
> Add link info for soft and external links in h5grove provider

- apps/storybook/src/HeatmapVisDisplay.stories.tsx
- packages/lib/src/vis/shared/AxisSystem.tsx
- packages/lib/src/vis/shared/Html.tsx
- packages/lib/src/vis/shared/TooltipMesh.tsx
- packages/lib/src/vis/utils.ts
While working on #909, I realized that we made a lot of similar computations when going from canvas coordinates to HTML coordinates. These computations were "manually" using the camera parameters (zoom and position).
I refactored these computations to use the camera projection matrix instead, that already contain all the camera parameters. 
This has several advantages:
- The computations are more generic, taking in account *both* the camera field of view and the zoom. This will greatly simplify #909 and allow a seamless transition.
- The computations are more concise and easier to understand in my opinion.
I see one disadvantage tho, we have to deal with (_shudder_) mutable `Vector3`...
Let me know what you think !
_PS: This image from [this SO …
> Project points with camera rather than manually

- apps/storybook/.storybook/main.js
This happens only on Linux and was brought by #911.
On Linux, `preset-create-react-app` from Storybook searches for the react-scripts Webpack config by trying to resolve the symlink `node_modules/.bin/react_scripts` : https://github.com/storybookjs/presets/blob/227cd94ef65adf5b89a2a22cb971455e6f6239d6/packages/preset-create-react-app/src/helpers/getReactScriptsPath.ts#L37.
Before #911, this line raised an error because `react-scripts` was not installed in the Storybook. The resolution was therefore done by [this line instead](https://github.com/storybookjs/presets/blob/227cd94ef65adf5b89a2a22cb971455e6f6239d6/packages/preset-create-react-app/src/helpers/getReactScriptsPath.ts#L49) which gave the appropriate path.
In #911, we installed `react-scripts` which means that the resolution is now …
> Fix react-scripts path resolution in storybook

- apps/storybook/package.json
- packages/app/package.json
- packages/lib/package.json
- packages/lib/src/vis/shared/VisCanvas.tsx
- pnpm-lock.yaml
We can now toggle the value of `VisCanvas`'s `canvasRatio` prop (between a ratio and `undefined`) and the the sizing behaviour of the canvas will change accordingly (i.e. adapt its ratio on resize or just fill the screen). This is thanks to https://github.com/react-hookz/web/commit/4c6f074eca31604d0975a9c8de1262b2fa8bda48, which now allows `useMeasure` to be toggled on/off dynamically.
> Support switching VisCanvas's sizing behaviour dynamically

- README.md
- apps/demo/.env
- apps/demo/src/HsdsApp.tsx
Part of #926 
I thought it might be easier to be able to specify the subdomain of HSDS so that files can be referred the same way whatever the provider.
I also cleaned-up the files on the back-end side.
> Update README with new files and links

- packages/app/package.json
- packages/lib/package.json
Trying this fix for #914. I've tested @h5web/app with CRA v5 outside of the repo and came across a couple of errors that I managed to fix by removing `"type": "module"` from the package, so I thought I'd give it a try.
Note that `"type": "module"` is required in development, so I "revert" it by setting to `"commonjs"` inside `"publishConfig"`.
I'll publish a beta version once merged.
> Remove `type: module` from published app/lib package.json

- packages/lib/src/vis/shared/Html.tsx
- packages/lib/src/vis/shared/PanZoomMesh.tsx
Re-implementation of #909
Using `camera.scale` allows to circumvent the FOV reset on resize while still having the possibility to scale differently in X and Y for #769 
I also had to change a bit the computations like in #912 and #928 so that the change goes smoothly. I expect the computations to be generic enough so that reverting to use `zoom` instead of `scale` should be a breeze.
> Make zoom work with camera scale

- packages/app/README.md
- packages/lib/README.md
- packages/lib/package.json
Next up, I'll remove the `demo-cra-lib` project from the repo.
> Add CRA and Vite sandboxes and fix @h5web/lib stylesheet export

- README.md
Fix https://github.com/silx-kit/h5web/issues/926
@t20100 told me that when landing on h5web repo, the JupyterLab extension is not easily discoverable. I then added a section about h5web usage. Hopefully, this should make the different usecases of h5web ecosystem clearer.
> Add sandboxes screenshots and a section about h5web usage

- apps/storybook/src/VisCanvasSelection.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
This is in essence a revert of https://github.com/silx-kit/h5web/pull/813
While this seemed very elegant for texture-based meshes, this introduces an issue for meshes that make use of the axis scales to position themselves (through `dataToWorld`). 
Indeed, the `flip` is already accounted for in the scales (which make sense for axes) so that coordinates computed through them **already have the correct flipped coordinates**. As a consequence, having an inverting group around such meshes flip them once more **which is incorrect**.
Examples of such meshes include `SelectionMesh` or the ones used in `LineVis`.
> Flip only the needed meshes rather than the whole canvas

- apps/storybook/src/HeatmapVis.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/models.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/utils.ts
This adds support for typed ndarrays in both `HeatmapVis` and `HeatmapMesh`. I haven't touched `@h5web/app` yet, this is just for `@h5web/lib`.
Both `dataArray` and `alpha.array` can now have type `NdArray<number[] | CompatibleTypedArray>`, where `CompatibleTypedArray` is `TypedArray` without `Uint8ClampedArray` and `Float64Array`, neither of which are supported by WebGL (at least to my knowledge, feel free to correct me @t20100).
I've added a new story too. You can tell it works because the `dataArray` control shows that the `data` property of the ndarray has 820 "keys" (instead of "items" when the ndarray contains a simple JS array):
> Let HeatmapVis accept typed ndarrays

- apps/storybook/src/VisCanvasInteraction.stories.tsx
- apps/storybook/src/VisCanvasSelection.stories.tsx
- packages/lib/src/vis/models.ts
- packages/lib/src/vis/shared/LineSelectionMesh.tsx
- packages/lib/src/vis/shared/PanZoomMesh.tsx
- packages/lib/src/vis/shared/RectSelectionMesh.tsx
- packages/lib/src/vis/shared/SelectionMesh.tsx
- packages/lib/src/vis/utils.ts
To use `SelectionMesh` and the `PanZoomMesh` on the same vis, we have to differentiate the clicks linked to the panning and the one linked to the selection.
This PR allows to specify a modifier key (`Alt`, `Ctrl` or `Shift`) to these meshes so that only clicks accompanied by the press of the key trigger the mesh callbacks. 
Also, previously, mesh callbacks were triggered on any clicks (including the one accompanied by press of modifier keys) so I had to change this so that clicks can be differentiated. 
I also added some stories to test things out.
> Allow modifier keys for SelectionMesh and PanZoomMesh

- apps/storybook/src/HeatmapMesh.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/utils.ts
- I simply add a prop called `magFilter` to `HeatmapMesh` that I pass along to the new `getDataTexture` utility.
- I also document `HeatmapMesh` as a new building block in Storybook.
One of the stories tests the texture override feature by passing `HalfFloatTexture` with a `Uint16Array`. For some reason, I get a black heatmap... Not sure if I'm doing things wrong in the story, or if the texture override feature does not work as expected. Any idea?
> Allow passing custom `magFilter` to `HeatmapMesh`

- apps/storybook/src/Utilities.stories.mdx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/utils.ts
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/models.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/models-vis.ts
- packages/shared/src/utils.ts
This has already impacted quite a few files, so I thought I'd keep further changes (line vis, providers, etc.) for separate PRs.
> Let `MappedHeatmapVis` and related utilities accept typed arrays

- packages/lib/src/vis/shared/PanMesh.tsx
- packages/lib/src/vis/shared/PanZoomMesh.tsx
- packages/lib/src/vis/shared/ViewportCenterer.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/shared/ZoomMesh.tsx
- packages/lib/src/vis/shared/hooks.ts
Also refactored the viewport centering on resize: it was extracted from the interaction meshes into a dedicated component `ViewportCenter`.
> Split PanZoom mesh in Pan and Zoom meshes

- packages/lib/src/vis/shared/SelectionLine.tsx
Here is a small bug I noticed when working on the profile feature: after a line is drawn, it can disappear when panning/zooming:
I could reproduce it in a "regular" R3F environment (https://codesandbox.io/s/disappearing-lines-2tgt0) but not as consistently, unfortunately. Peculiar circumstances are needed: the line must not be instantiated at start (i.e. it must be drawn after canvas instantiation) and not every pan/zoom combination make the line disappear...
A quick search led me to try `depthTest=false` on interaction meshes (https://stackoverflow.com/questions/33346970/disappearing-line-object-in-three-js) but it didn't help.
I managed to fix it by computing the bounding sphere explicitly when setting the points of the bufferGeometry. I guess the computation is done under the hood by …
> Fix disappearing selection line when pan/zooming

- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
Fix #962 - Three.js has deprecated the `RGBFormat`, which apparently isn't well optimised by WebGL implementations.
> Switch to `RGBAFormat` for heatmap colormap

- packages/app/src/vis-packs/core/utils.ts
> Avoid copying ndarray when no slicing/mapping is performed

- apps/storybook/src/Utilities.stories.mdx
- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/heatmap/hooks.ts
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/lib/src/vis/heatmap/utils.test.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
Just a bit of almost-Spring cleaning.
> Remove duplicate hooks

- apps/storybook/src/Customization.stories.mdx
- apps/storybook/src/MatrixVis.stories.tsx
- apps/storybook/src/styles.css
- packages/app/src/App.module.css
- packages/app/src/vis-packs/core/complex/config.tsx
- packages/app/src/vis-packs/core/heatmap/config.tsx
- packages/app/src/vis-packs/core/line/config.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/app/src/vis-packs/core/matrix/config.tsx
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/rgb/RgbToolbar.tsx
- packages/app/src/vis-packs/core/rgb/config.tsx
- packages/lib/src/index.ts
- packages/lib/src/toolbar/controls/CellWidthInput.module.css
- packages/lib/src/toolbar/controls/CellWidthInput.tsx
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
Fix #916
Following #976, I've made the computation of the cell width smarter for fixed-length strings, vlen strings and booleans.
Since we cannot reasonably guess the optimal cell width for vlen strings (I've chosen an arbitrary default of 300px), I've also added a control to the toolbar so user can tweak the value themselves:
The value can be reset to the default and is persisted to local storage.
> Add control to change cell width in MatrixVis toolbar

- apps/storybook/src/ScatterVis.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/vis/scatter/ScatterPoints.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/scatter/hooks.ts
Now accepts:
- a `ndarray` instead of `number[]`. The `ndarray` can contain a `number[]` or a `TypedArray`
- a `size` parameter
- a `title` parameter
- Labels for abscissas and ordinates
- `children`
> Bring ScatterVis parameters in line with other vis

- apps/storybook/package.json
- apps/storybook/src/TiledHeatmap.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/shared/VisMesh.tsx
- packages/lib/src/vis/tiles/Tile.tsx
- packages/lib/src/vis/tiles/TiledHeatmap.tsx
- packages/lib/src/vis/tiles/TiledLayer.tsx
- packages/lib/src/vis/tiles/api.ts
- packages/lib/src/vis/tiles/hooks.ts
- packages/lib/src/vis/tiles/models.ts
- packages/lib/src/vis/tiles/utils.ts
- pnpm-lock.yaml
This PR adds a component to render (large) images as tiles with pyramid of level-of-details image support.
The axes are used to compute the level of detail to use rather than the size of the array, this needs to be solved.
~~commit https://github.com/silx-kit/h5web/commit/cc293bc86d51e0d37a991e23a746280d278f908c provides a proof of concept for h5grove-based fetch of subsampled slices. It is there for demo and should be removed before merging.~~
> Add tiles image with multiple level of details layer support

- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/shared/ResetZoomButton.module.css
- packages/lib/src/vis/shared/ResetZoomButton.tsx
Fix #984 
The button only appears when the zoom is not null.
> Add a Reset zoom button to Heatmap, Line, Rgb and ScatterVis

- packages/app/package.json
- packages/app/vite.config.js
- packages/lib/package.json
- packages/lib/src/vis/utils.ts
- packages/lib/vite.config.js
Fix #986 
With `"type": "module"`, webpack v5 enforces Node-compliant paths. For `react-icons/fi`, this should be `react-icons/fi/index.esm.js`, but if I do this in the codebase, then TypeScript complains that it can't find the types...
I think this is linked to the way the `react-icons` package is organised, but not sure it's worth reporting since it works fine with `"type": "module"` removed (or rather overridden with its default value `"commonjs"` when published).
> Fix CRA v5 compatibility by publishing lib and app as CommonJS packages

- packages/lib/src/vis/shared/SelectionTool.tsx
- packages/lib/src/vis/utils.ts
...and make it reappear when it is pressed again.
Fix #1003 
`SelectionTool` is becoming quite complex and `sonarjs` is complaining :scream_cat: 
But I want to get your opinion on the implementation before I start refactoring
> Make selection disappear when modifier key is released

- apps/storybook/src/Pan.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- apps/storybook/src/Selection.stories.tsx
- apps/storybook/src/XZoom.stories.tsx
- apps/storybook/src/YZoom.stories.tsx
- apps/storybook/src/Zoom.stories.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/models.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/shared/AxisSystemContext.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/utils.ts
Stepping stone for #1013 
Following our discussion, here is a first prototype to have interaction configuration stored at a single place (here `AxisSystemContext`) to have a place where we can handle interactions between interactions (do you follow?).
Also, this allows to have a more permissive behaviour for interactions with a `modifierKey` set to `undefined` (`Pan` in particular). They will now only be prevented if the pressed modifier key is bound to another interaction.
This fixes #1015 as default modifier keys values in these components were removed, allowing modifier keys to be set to `undefined`.
> Handle interaction key conflicts by setting them in VisCanvas

- packages/lib/src/interactions/SelectToZoom.tsx
While working on https://github.com/silx-kit/h5web/issues/1025, I noticed a small bug for NXImage with axes.
I captured it below: the ratio of the rectangle is not computed properly while it is for the image without axes.
The cause is quite simple: the part that computes the endpoint to respect the ratio works in the data space but we gave the ratio in the world space (`width / height`). 
Most of the time, this works fine because the ratio in the world space is the same as the ratio in the data space (i.e. the changes in width/height are proportional to the changes in x/y). This obviously changes when using axes in NeXus visualisations where the ratio between abscissas and ordinates values can be different than the ratio between width and `height`.
So two ways of solving this:
- Keep the …
> Fix ratio of SelectToZoom for NXImage

- apps/storybook/src/HeatmapVis.stories.tsx
- apps/storybook/src/Pan.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- apps/storybook/src/Selection.stories.tsx
- apps/storybook/src/XZoom.stories.tsx
- apps/storybook/src/YZoom.stories.tsx
- apps/storybook/src/Zoom.stories.tsx
- packages/lib/src/interactions/DefaultInteractions.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/shared/AxisSystemContext.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/utils.ts
Interaction components have their props back (`modifierKey` and `disabled`).
The registration of interactions is no longer done by `VisCanvas` but in each component using a custom hook that registers the interaction in the `AxisSystemContext`. `VisCanvas` therefore loses its `interactions` props
I also added a `DefaultInteractions` component to deduplicate the instantiations of interaction components in our vis. Props can be given to this component to modify the default components. This brings a bit of complexity in `DefaultInteractions`.
> Register interaction in interaction components through a custom hook

- apps/storybook/src/DomainSlider.stories.tsx
- apps/storybook/src/Utilities.stories.mdx
- packages/lib/src/toolbar/controls/DomainSlider/Histogram.tsx
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/utils.ts
This PR fixes an issue in the `Histogram` which didn't work with TypedArray because of  TypedArray.map returns a TypedArray instead of an Array:
https://github.com/silx-kit/h5web/blob/12a66f7563f8c4d415b4d9b8e7d14ce7a16572cd/packages/lib/src/toolbar/controls/DomainSlider/Histogram.tsx#L56-L65
It also adds a `toArray` function and the corresponding `useArray` hook.
> Fix support of TypedArray in Histogram value + add toArray/useToArray utils

- packages/app/package.json
- packages/app/src/dimension-mapper/SlicingSlider.tsx
- packages/lib/package.json
- pnpm-lock.yaml
Two [main changes](https://github.com/zillow/react-slider/releases/tag/v2.0.0) that concern us:
- `prop-types` is no longer a peer dependency, which means we won't get the warnings any more
- `react-slider` now re-renders itself when it is resized thanks to `ResizeObserver` (before, it used to just listen to the window's `resize` event), which means we no longer have to take care of this ourselves in `SlicingSlider` in order for the sliders to re-render when the H5Web notebook cell is resized in JLab.
> Upgrade react-slider

- apps/storybook/src/LineVis.stories.tsx
- packages/app/src/test-utils.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/nexus/NxValuesFetcher.tsx
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/app/src/vis-packs/nexus/models.ts
- packages/lib/src/vis/line/LineVis.module.css
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/line/models.ts
First part of #970 
In order to display the auxiliaries in the tooltip and the legend, we need to know their names. So I change the API of `LineVis` as follows: the `auxArray: NdArray<NumArray>[]` prop becomes `auxiliaries: Auxiliary[]`, where `Auxiliary` is an object with a `name`, `label` and `array`.
Since this was quite the refactoring already, I decided to implement the legend in a separate PR. So for now, I use the `name` in the tooltip. I plan to use the `label` (either `long_name`, or dataset name + `units`, or just dataset name) in the legend, since I'll have more space to work with.
> Show auxiliary values in tooltip

- packages/lib/src/vis/line/LineVis.module.css
- packages/lib/src/vis/line/LineVis.tsx
Fix #970 
The tooltip remains unchanged when no auxiliaries are passed (i.e. the color of the main plot is not shown unless there are auxiliary plots).
The tooltip code of the line vis is starting to take quite a bit of space, but I wasn't sure if it was worth extracting the whole thing into a separate component, since we need access to so many props/variables from `LineVis`. Perhaps there's a way to abstract things but I'm not seeing it yet, especially since everything in there is so specific to the line vis at the moment.
> Show auxiliary plot colors in line vis tooltip

- apps/storybook/src/ScatterVis.stories.tsx
- packages/lib/src/vis/scatter/ScatterPoints.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
For daiquiri, I need to be able to trigger events when clicking on point of a `ScatterVis`. 
In my early tries, I noticed that when attaching `onClick` to `points`, the handler was only called when clicking on the very center of the point. I figured this was because the handler was unaware of the shader rendering of the point that gives a point of bigger size.
I was able to solve this by increasing [the threshold of the raycaster](https://threejs.org/docs/index.html?q=raycas#api/en/core/Raycaster.params) to the size of the point so that events are caught for the full point.
Note that there is a limitation: the threshold is given in world units but point size stay constant when zooming in the scene. This means that the hitbox does not match the point when zooming in.
> Add onClick callback to ScatterVis

- apps/storybook/src/TiledHeatmap.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/tiles/TiledHeatmap.tsx
- packages/lib/src/vis/tiles/TiledLayer.tsx
- packages/lib/src/vis/tiles/hooks.ts
- packages/lib/src/vis/tiles/utils.ts
This PR fixes display issues of tiles heatmap when an axis is flipped.
It adds a story with both axes flipped.
It supports flipped axes by handling the axes flip early with a `<group>` in `TiledLayer` instead of late in `HeatmapMesh` and by supporting reverted domains.
> Fixes TiledHeatmap display with flipped axes

- apps/storybook/src/DataCurve.stories.tsx
- apps/storybook/src/Overlay.stories.tsx
- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/vis/line/DataCurve.tsx
- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
Also, rename `TiledHeatmap` to `TiledHeatmapMesh` for consistency with `HeatmapMesh`. (Note that we could also have renamed `HeatmapMesh` to `Heatmap` instead, but I think `Mesh` makes it clearer that it is a building block meant to be used inside `VisCanvas`.)
New story for `Overlay`:
New stories for `DataCurve`:
> Clarify what is documented and undocumented in lib index

- apps/storybook/src/HeatmapVisDisplay.stories.tsx
- packages/lib/src/vis/shared/Annotation.tsx
With `scaleOnZoom`, if the annotation is not centered around its coordinates, it shifts once the user starts zooming. The annotation in the story is currently positioned at `(30, 18)`:
But loses its position when zooming:
With this PR, I propose that we always center annotations when `scaleOnZoom` is `true`, with `translate(-50%, -50%)`.
I take the opportunity to improve the annotation stories a little, notably by showing how one might go about drawing an SVG rectangle:
> Center annotation automatically when using `scaleOnZoom`

- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/toolbar/floating/ResetZoomButton.tsx
- packages/lib/src/vis/shared/RatioEnforcer.tsx
- packages/lib/src/vis/shared/ViewportCenterer.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
Fix #1076
This issue is part of #993, but technically, the same problem can occur with the axial zoom components - i.e. you start zooming on one axis because `keepRatio` is `false` then toggle the flag to `true` and the visualisation is broken. Therefore, instead of putting the code in `SelectToZoom`, I decided to create a specialised `VisCanvas` component similarly to `ViewportCenterer`.
Also, instead of resetting the zoom to `(1, 1)` when `visRatio` becomes defined, I reset it to the scale of the axis that is most zoomed out - e.g. `(0.8, 0.6)` becomes `(0.8, 0.8)`. I also make sure that the scales of the two axes are actually different before resetting, to avoid triggering a frame unnecessarily.
> Repair zoom if needed when "keep ratio" becomes enabled

- CONTRIBUTING.md
- README.md
- apps/demo/package.json
- apps/demo/src/DemoApp.tsx
- apps/demo/src/h5wasm/DropZone.tsx
- apps/demo/src/h5wasm/H5WasmApp.module.css
- apps/demo/src/h5wasm/H5WasmApp.tsx
- apps/demo/src/h5wasm/models.ts
- apps/demo/src/styles.css
- apps/demo/vite.config.js
- packages/app/README.md
- packages/app/src/index.ts
- packages/app/src/providers/Provider.tsx
- packages/app/src/providers/utils.ts
- packages/h5wasm/.eslintignore
- packages/h5wasm/.eslintrc.cjs
- packages/h5wasm/README.md
- packages/h5wasm/package.json
- packages/h5wasm/rollup.config.js
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/index.ts
- packages/h5wasm/src/models.ts
- packages/h5wasm/src/types.d.ts
- packages/h5wasm/src/utils.ts
- packages/h5wasm/tsconfig.build.json
- packages/h5wasm/tsconfig.json
- packages/h5wasm/vite.config.js
- packages/lib/README.md
- pnpm-lock.yaml
The provider code is ported from #1031 and https://github.com/bmaranville/h5web/pull/1/ but limited to the low-level `H5WasmProvider` first discussed in https://github.com/silx-kit/h5web/pull/1031#pullrequestreview-924227264. The provider just accepts an `ArrayBuffer` as prop and reads it on demand with `h5wasm`; it doesn't do any fetching and doesn't provide any UI for picking files.
To demonstrate the use of the provider, I implemented a demo with a file picker/drag-and-drop interface. It's available at http://localhost:3000/h5wasm if you want to test it.
The focus for now is to bootstrap the low-level provider and deal with the BigInt issue. I didn't port the slicing code, didn't worry about broken and external links, and didn't fix some of the dtype inconsistencies with H5Grove that I …
> Implement new `H5WasmProvider`

- README.md
- apps/demo/package.json
- apps/demo/src/DemoApp.tsx
- apps/demo/src/Home.module.css
- apps/demo/src/Home.tsx
- packages/app/README.md
- pnpm-lock.yaml
> Add demos homepage

- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/vis-packs/nexus/utils.ts
- packages/app/src/visualizer/utils.ts
- packages/shared/src/mock/metadata.ts
For older NeXus files, the plottable signal is identified by a ```@signal``` attribute on the dataset itself, rather than the NXdata group (see Version 1 and Version 2 at https://manual.nexusformat.org/datarules.html#find-plottable-data). 
This PR implements a fallback strategy for finding these plottable datasets by searching the children of the NXdata group to find a dataset with the ```signal``` attribute.
It does not implement the identification of axes using those older lookup algorithms, and that is still to-do.
---
Part of #1062
> implement resolution of old-style signal on NXdata

- packages/app/src/metadata-viewer/EntityInfo.tsx
- packages/app/src/metadata-viewer/FiltersInfo.tsx
- packages/app/src/metadata-viewer/MetadataViewer.tsx
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/shared/src/models-hdf5.ts
Fix #311 
Requires h5grove [v0.0.16](https://github.com/silx-kit/h5grove/releases/tag/v0.0.16)
**Updated** example on the compressed dataset in **water_224.h5**:
You can also look at [compressed.h5](http://localhost:3000/h5grove?file=compressed.h5) for more examples
> Display chunks and compression info in dataset metadata

- .github/workflows/lint-test.yml
So I've looked a bit more into it and it really sucks... Only way I could find is to add a condition to each job to skip it if it's triggered by a local PR. Downside is that the skipped jobs still appear in the UI.
Running the CI on `push` to any branch is quite convenient in my opinion for a few reasons:
- By the time you open the PR, the CI is likely to have already passed, which means you can be sure it's ready to be reviewed. This saves us a lot of time on a day-to-day basis.
- If you push a new branch and you know you forgot to fix the linting or the tests, you can cancel the CI run or force-push the fixes before opening the PR.
- If you work on something that might affect the screenshots or the CI workflows themselves, it can be useful have a branch to push to before you can be sure …
> Revert CI triggers but skip double runs

- apps/storybook/src/VisGroup.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/vis/shared/VisGroup.tsx
This PR proposes to have a threejs group that uses the coordinates defined by the axes system.
There is a huge obvious limitation in that it only supports linear axes (I was wondering whether to raise an error or not to display anything in this case).
But when using linear axes, it helps organising multiple meshes in a "data" coordinate system.
What do you think?
Extracted from story in #1096
> Add a VisGroup (for linear axes only)

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/utils.ts
Fix #1100 
I also fixed an issue with `Unresolved` entities (such as datatypes): clicking on the `Inspect` page would show `attributes are undefined`.
> Include link metadata for h5wasm and fix unresolved entities

- packages/lib/src/vis/shared/AxisSystem.module.css
- packages/lib/src/vis/shared/AxisSystem.tsx
- packages/lib/src/vis/shared/VisCanvas.module.css
- packages/lib/src/vis/shared/VisCanvas.tsx
Fix #1105
This was a regression caused by the refactoring of `Html` in #1030. I fixed it by removing the `overflow: visible !important` override on `r3fRoot`. This override was necessary for `AxisSystem`, but I realised that the `Html` element in `AxisSystem` can be now appended to `canvasWrapper` instead of `r3fRoot` thanks to the `container` prop! By doing this, we can let `r3FRoot` hide its overflow as it does by default, which avoids having to turn the `Html` element back into an overlay.
> Prevent annotations and other `Html` elements from overflowing canvas

- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
- packages/lib/src/vis/tiles/TiledLayer.tsx
- packages/lib/src/vis/tiles/utils.ts
This PR renders usage of TiledHeatmapMesh more generic.
The computation of requested tiles no longer relies on the axes (thanks @axelboc!) and should also handle almost any transforms.
> TiledHeatmapMesh: added supports of scene transforms

- packages/h5wasm/package.json
- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/models.ts
- packages/h5wasm/src/utils.ts
- pnpm-lock.yaml
Thanks to [v0.4.2](https://github.com/usnistgov/h5wasm/releases/tag/v0.4.2) of h5wasm
I still have some issues with boolean which is why it is not included in this PR
> Add support for complex dataset values in h5wasm

- apps/storybook/src/Html.stories.tsx
- packages/lib/src/vis/shared/Annotation.tsx
- packages/lib/src/vis/shared/Html.tsx
This brings:
- a way for `Annotation` to overflow the canvas, following #1105, as requested by @vallsv 
- a more convenient way to move an `Html` component to `canvasWrapper` to show the overflow (than setting the `container` prop manually). The `container` prop can still be set and takes priority over `overflowCanvas`.
> Add prop `overflowCanvas` to `Html` and `Annotation`

- .github/workflows/lint-test.yml
- apps/storybook/package.json
- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- pnpm-lock.yaml
I've found a library called [greenlet](https://github.com/developit/greenlet), which works beautifully. It creates an inline worker with the function you give it: https://github.com/developit/greenlet and wraps it in a promise API. It's super tiny too.
The demo is a lot more fluid, though still not amazing on my machine, as we're still doing all the computations on the CPU. It can't compare exactly to a fetch-based scenario, but it's already a lot better.
> Move mandlebrot to web worker in tiled heatmap story

- cypress/index.d.ts
- cypress/specs/app.spec.ts
- cypress/support.ts
After working on the feature tests in #1119, it's clear that React Testing Library is much better than Cypress Testing Library at waiting for React to finish rendering. That's why we have a lot of workarounds in the E2E specs, waiting for unrelated things to appear, and why we get a lot of retry attempts in the CI.
In this PR, I'm introducing a query called `cy.waitForStableDom()` found here: https://github.com/narinluangrath/cypress-wait-for-stable-dom/, which seems to perfectly solve all our problems. It tells Cypress to wait until there are no more mutations in the DOM over a given period of time. By calling it after every user action (`click`, `type`, etc.), all the tests pass on their first attempts.
The polling interval is currently set to 300ms, a bit more than the slicing slider, …
> Make E2E tests more robust

- packages/app/src/providers/h5grove/h5grove-api.ts
The only relevant change is the `dtype` argument change for binary data: https://github.com/silx-kit/h5grove/releases/tag/v1.0.0
> Update h5grove API to 1.0.0

- packages/lib/src/interactions/InteractionsProvider.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/models.ts
Looking at #1120 and #1121, I thought we could leverage our interaction registration process to be able to constrain interactions to a single button.
I tried to keep the changes minimal to give a basis of discussion so that when `button` is not given, the behaviour is the same as before (no constrain on button). Among future improvements, I can see:
- Give default values for `button` for the `Pan`
- Take `button` in account when looking at conflicting interactions in `shouldInteract`
> Allow to constrain interactions to a single button

- apps/demo/src/h5wasm/DropZone.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/utils.ts
- Allow files with any extensions to be dropped - fix #1126 
- Allow files that don't start with the HDF5 magic number (called the HDF5 File Signature in the spec), as per the HDF5 spec https://web.ics.purdue.edu/~aai/HDF5/html/H5.format.html
> Make H5Wasm demo more permissive

- CONTRIBUTING.md
- packages/app/package.json
- packages/app/rollup.config.js
- packages/h5wasm/package.json
- packages/h5wasm/rollup.config.js
- packages/lib/package.json
- packages/lib/rollup.config.js
- packages/shared/package.json
- pnpm-lock.yaml
Fix #1099 
Here is the trick: I build the shared types with `tsc` to `packages/shared/dist-ts`, and then in the other packages, when the time comes to merge all the types into a single file with Rollup, I tell Rollup that `@h5web/shared` is an alias for `../shared/dist-ts/index.d.ts`! :tada: 
In `dist/index.d.ts`, the enums are now properly prefixed with `declare`, the `mockMetadata` object is no longer inlined, etc.
This can only be good for package consumers, even when no errors were reported. If anything it will save the TypeScript engine some work in VSCode.
Also, `pnpm packages` used to output warnings like this one:
Now the output is clean:
> Fix rolled-up types

- apps/demo/package.json
- apps/storybook/package.json
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- pnpm-lock.yaml
Nothing very exciting; just a couple of peer deps changes to include React 18.
- https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md
- https://github.com/vitejs/vite/blob/main/packages/plugin-react/CHANGELOG.md
- https://github.com/Swatinem/rollup-plugin-dts/blob/master/CHANGELOG.md
- https://github.com/streamich/react-use/releases
- https://github.com/react-icons/react-icons/releases/tag/v4.4.0
- https://github.com/testing-library/cypress-testing-library/releases (Cypress 10 peer dep)
- https://github.com/prettier/prettier/releases
- https://github.com/leefsmp/Re-Flex/commits/master
- https://github.com/zillow/react-slider/blob/master/CHANGELOG.md
> Upgrade deps

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/utils.ts
Following https://github.com/silx-kit/h5grove/pull/69 and early step for #1130 
Previously, compound dtypes were interpreted by `H5GroveProvider` as `Unknown`. Now, there are rightly shown as `Compound` and the raw inspection can show the fields
> Improve compound dtype parsing in H5GroveProvider

- apps/demo/src/H5GroveApp.tsx
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/h5grove/h5grove-api.ts
Needed for daiquiri implementation as headers will need to be added on the top of query params
> Change H5GroveProvider to supply axios config and not only params

- apps/demo/package.json
- apps/storybook/.storybook/main.js
- apps/storybook/package.json
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- [Control Flow Analysis for Destructured Discriminated Unions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/#control-flow-analysis-for-destructured-discriminated-unions) - may help us write cleaner code in some places, but difficult to identify where at this point.
- [Go to Source Definition](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#go-to-source-definition) - finally!! This command takes you to the actual source code of a method, object or whatever, instead of to its type declaration! You can access the command after upgrading VSCode, by right-clicking on something in the editor or via the command palette. Ctrl+click still takes you to the type declaration.
- [Instantiation Expressions](https://devblogs.microsoft.com/typescript/announcing …
> Upgrade TypeScript, Storybook and Prettier

- apps/storybook/src/SelectToZoom.stories.tsx
- packages/app/src/vis-packs/core/utils.ts
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/DefaultInteractions.tsx
- packages/lib/src/interactions/InteractionsProvider.tsx
- packages/lib/src/interactions/utils.ts
Fix #1066
This PR implements a specific component `AxialSelectToZoom` for drawing a selection to zoom on a single axis. Triggering this zoom mode can be done with  a specific combination of keys (thanks to #1144) rather than relying on the size of the rectangle (which can be fiddly).
> Implement SelectToZoom for a single axis

- apps/demo/package.json
- apps/demo/src/Home.tsx
- apps/demo/src/h5wasm/DropZone.tsx
- apps/demo/src/h5wasm/H5WasmApp.module.css
- apps/demo/src/h5wasm/H5WasmApp.tsx
- apps/demo/src/h5wasm/UrlForm.tsx
- pnpm-lock.yaml
- I've added a form to the H5Wasm demo to allow specifying a URL
- When the form is submitted, the app navigates to `?url=<url>`, which fetches the file as an `ArrayBuffer`
- While fetching, the form is disabled and a spinner is shown
- Once fetched, the buffer is passed to `H5WasmProvider` and the viewer shows up
- The use of the `url` param allows refreshing (cf. GIF below), bookmarking and linking (e.g. from the H5Web homepage)
> Allow viewing remote files in H5Wasm demo

- apps/storybook/src/DefaultInteractions.stories.tsx
- apps/storybook/src/HeatmapVis.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/DefaultInteractions.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/models.ts
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
The main goal of this PR is to make sure that the `interactions` props of the visualizations have a type that is compatible with the props of the interaction components. For instance, previously, you could pass `{ zoom: { button: MouseButton.Middle } }` even though `Zoom` doesn't accept a `button` prop.
To do this, I refactored a few things:
- `DefaultInteractions` is now written more declaratively and is more strongly typed. It accepts interaction configurations directly as props instead of inside an `interactions` prop.
- Every interaction component has its own `Props` interface that is exported and used to type the props of `DefaultInteractions`, which are in turn used to type the `interactions` props of the visualization components.
- I renamed the `Interaction` interface to …
> Enforce stricter types for default interactions configuration

- packages/lib/src/interactions/InteractionsProvider.tsx
Now, when this occurs, the second interaction no longer replaces the first. See https://github.com/silx-kit/h5web/issues/1143#issuecomment-1164050717
> Warn when trying to register two interactions with the same ID

- apps/storybook/src/Pan.stories.tsx
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/Pan.tsx
Follow-up to #1143
The solution of allowing multiple buttons to be passed to the `Pan` component did not allow for the scenario where one and only of the buttons needs to be combined to a modifier key - e.g. middle button without modifier key AND left button with `Ctrl` modifier key:
```tsx
<Pan id="PanMiddle" button={MouseButton.Middle} />
<Pan id="PanLeft" button={MouseButton.Left} modifierKey="Control" />
```
> Allow overriding `Pan` interaction ID

- README.md
Fix #1159 
I'm also adding a section called `Ecosystem` to list related projects, and another called `Contributing` to make the CONTRIBUTING guide more discoverable.
> Shorten "Demos" section in README and add "Ecosystem"/"Contributing" sections

- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
See https://github.com/silx-kit/h5web/pull/1169#discussion_r919805775
Done for `Heatmap` and `Matrix`. `Line` is a bit more complicated:
- `selection` can be forced to `undefined` in the `Mapped..` component due to `autoscale` #445 
- `dataset` is optional for `ComplexLine` as the export is disabled
This would perhaps need a specific refactoring
> Remove derived props in Mapped..Vis components

- packages/lib/src/vis/shared/VisCanvas.module.css
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/42204205/183433820-031e65ab-e3f6-418c-bd9f-1528bc50c513.png) | ![image](https://user-images.githubusercontent.com/42204205/183433973-d1f84635-9660-444d-835a-0936b5f22dc9.png) |
> Fix stacking context of floating toolbar

- packages/lib/src/interactions/SelectionTool.tsx
The `onSelectionChange` callback of `SelectionTool` is not called when the mouse moves (see https://h5web-docs.panosc.eu/?path=/story/building-blocks-selection--rectangle where the title should update when dragging a rectangle).
This is a quick fix as a discussion with @axelboc showed that a bigger refactoring could be envisionned to distinguish checks for starting the interaction and checks for continuing the interaction on pointer moves.
> Fix onSelectionChange not called in SelectionTool

- apps/demo/package.json
- apps/storybook/package.json
- eslint.shared.js
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- packages/shared/package.json
- pnpm-lock.yaml
The `es6` ESLint env is now enabled by default by Galex: https://github.com/ljosberinn/eslint-config-galex/pull/664
> Upgrade linting config

- packages/lib/package.json
Oversight of https://github.com/silx-kit/h5web/pull/1170
Since we are dependant of the changes introduced in `138` (e.g. renaming from `DataTexture3D` to `Data3DTexture`), the version of `three` in `peerDependencies` should have been updated.
> Update peer dep three of h5web/lib

- packages/h5wasm/src/h5wasm-api.ts
Fix https://github.com/silx-kit/vscode-h5web/issues/15
As for #1179, I made use of [to_array](https://github.com/usnistgov/h5wasm/blob/main/README.md#reading) that converts into nested arrays of JSON-compatible values.
But, rather than adding a check like in #1179, I now use `to_array` for attribute values of **any dtype**. The reason is that attribute values get stringified by `JSON.stringify` in `AttributeInfo` so they should be JSON compatible.
This fixes the display of several dtypes:
- `int64` now works
- `float`: Arrays of floats were `TypedArrays` that were stringified as `{"0":4.2,"1":4.3, ...}`. Now, we have `[4.2, 4.3, ...]` with the proper array nesting.
- `complex`: nD (n>2) array were displayed as 1D. They now show the proper nesting.
Note that despite its name, `to_array` …
> Fix serialisation of attributes for several dtypes in h5wasm

- packages/h5wasm/package.json
- packages/h5wasm/src/h5wasm-api.ts
- pnpm-lock.yaml
Emscripten's `FS.writeFile` throws an `FS Error` when called with a filename that contains slashes. This is an unnecessary restriction, since the filename can be anything really -- like a URL.
I workaround the issue by generating a unique ID with https://github.com/ai/nanoid
> Support passing filename with slashes to H5WasmProvider

- apps/demo/package.json
- apps/demo/vite.config.js
- packages/app/package.json
- packages/app/vite.config.js
- packages/h5wasm/package.json
- packages/h5wasm/vite.config.js
- packages/lib/package.json
- packages/lib/vite.config.js
- pnpm-lock.yaml
Release notes:
- https://github.com/vitejs/vite/blob/v3.1.0/packages/vite/CHANGELOG.md#main-changes
- https://github.com/vitejs/vite/blob/main/packages/plugin-react/CHANGELOG.md
- https://github.com/gxmari007/vite-plugin-eslint/blob/main/CHANGELOG.md
Biggest win is that Vite 3.1.0 includes an upgrade of `postcss-modules` to v5, which fixes the issue with `composes` on Windows! https://github.com/vitejs/vite/issues/3092
Lots of great stuff in Vite@3 under the hood. Only thing that may be of interest is that it now only supports Firefox v78 and above out of the box. There's a legacy plugin, but I don't think it's worth using for the demo. Unless I'm mistaken, this is irrelevant for library mode since we generate only an ESM bundle and let consumers bundle it in their own app. We'll have to …
> Upgrade Vite to v3 and remove Windows workarounds

- apps/demo/src/H5GroveApp.tsx
- packages/app/src/App.module.css
- packages/app/src/App.tsx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/models.ts
While working to disable the dark mode in daiquiri, I had the thought that if the switch to dark mode is sometimes undesirable, there should be a way to disable it.
This would avoid the [CSS hack in jupyterlab-h5web](https://github.com/silx-kit/jupyterlab-h5web/blob/8543f67bb93bc6cb19198d5233d1df2c0779758a/style/index.css#L20).
Here is a proposal based on a `disableDarkMode` prop of `App` that gets translated in a `allow-dark-mode` CSS attribute so that CSS dark mode rules can be filtered. I am not convinced this is the best solution so I am drafting it for discussion.
> Allow to disable dark mode of App

- packages/app/package.json
- packages/lib/package.json
- pnpm-lock.yaml
CodeSandboxes are broken for a while due to a failure in the import of `react-slider`.
I hope that the update to [2.0.4](https://github.com/zillow/react-slider/releases/tag/v2.0.4) will fix this.
> Update react-slider to 2.0.4

- apps/storybook/src/LineVis.stories.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/line/models.ts
Even though labels are always set when calling `LineVis` from `NxSpectrum`, it would be nice to lift this constraint for other uses (such as the example https://codesandbox.io/s/h5weblib-demo-multiple-curves-kwkli)
> Make auxiliary labels optional in LineVis

- apps/storybook/src/ScatterVis.stories.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
For consistency with [`HeatmapVis`](https://github.com/silx-kit/h5web/blob/fc409b37725e76f0cb0fcf2ac84a9dc039ccb40a/packages/lib/src/vis/heatmap/HeatmapVis.tsx#L48)
> Make ScatterVis colorMap prop optional

- packages/app/README.md
- packages/app/src/App.tsx
For consumers who want to implement their own error boundary, like in https://gitlab.esrf.fr/ui/myhdf5/-/merge_requests/11
I think this is more flexible than to allow consumers to override the top-level error fallback component, for instance.
Note that I also make `react-error-boundary` an optional peer dependency to reduce bundle size for consumers who do want to provide their own boundary.
> Allow propagating errors through top-level error boundary

- packages/app/src/vis-packs/core/complex/MappedComplexLineVis.tsx
- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/scatter/MappedScatterVis.tsx
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/app/src/vis-packs/nexus/models.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/shared/src/models-nexus.ts
Fix #1214
Most basic fix to let the `axisScaleTypes` array be parsed if it contains `null` values (or `'.'` or whatever -- anything else than a valid scale type is parsed as `undefined`).
This lets the spectrum visualization use the suggested axis scale type for the selected dimension on 2D+ datasets. As you pointed out in #1214, @loichuder, this does not fix the issue of updating the suggested scale type when selecting another dimension. But we agreed this isn't worth fixing until we actually encounter the use case.
> Support axis mapping of scale types in `SILX_style`

- apps/storybook/src/Selection.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/AxialSelectionTool.tsx
I think it is easier to export it rather than reimplementing `getAxialSelection` in daiquiri
> Extract AxialSelectionTool and export it in lib

- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/nexus/NxValuesFetcher.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxRgbContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxScatterContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/guards.ts
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/app/src/vis-packs/nexus/models.ts
- packages/app/src/vis-packs/nexus/utils.ts
In preparation for #1198, labels and units are now retrieved once and for all when calling `useNxData`. We no longer compute labels/retrieves units from `NxValuesFetcher`. This will allow us to access units inside the container in order to pass an initial `layout` value to the heatmap config hook.
> Get all units and labels as part of `useNxData`

- apps/demo/src/styles.css
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
- packages/lib/src/vis/scalar/ScalarVis.module.css
- packages/lib/src/vis/scalar/ScalarVis.tsx
Fix #1223 
In the end, I added wrappers to avoid breaking the other vis. The challenge was keeping the padding on the right and bottom of the overflowing content... I've also added a `min-width` the demo to avoid breaking the layout -- I figure it's safer to let consumers deal with this than to enforce something in @h5web/app.
Note that I did not commit the changes to the mock values visible in the screenshots above.
> Fix overflow on raw and scalar vis

- cypress/plugins.ts
- cypress/support.ts
- package.json
- pnpm-lock.yaml
With PRs https://github.com/narinluangrath/cypress-wait-for-stable-dom/issues/4 and https://github.com/narinluangrath/cypress-wait-for-stable-dom/issues/5 now resolved, I'm able to use the plugin [cypress-wait-for-stable-dom](https://github.com/narinluangrath/cypress-wait-for-stable-dom).
> Use Cypress plugin to wait for stable DOM

- apps/demo/package.json
- apps/demo/vite.config.js
- pnpm-lock.yaml
TS errors were only reported by `pnpm lint:tsc`. This is now corrected thanks to https://vite-plugin-checker.netlify.app/
I'm keeping `vite-plugin-eslint` for now, as the configuration is simpler. We still have the issue that ESLint errors in packages are not reported when developing the demo.
> Report type-checking errors in development

- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/lib/src/toolbar/controls/ExportMenu.tsx
Preparation for #1063 
The `getFormatURL`  prop was confusing. It made it look like the URLs were generated lazily, which isn't the case -- they're generated during render. Also, we used to end up with two arrays, `formats` and `urls`, so we had to access one by `index` in the `map` loop.
> Simplify props API of `ExportMenu`

- apps/demo/src/H5GroveApp.tsx
- apps/demo/src/HsdsApp.tsx
- packages/app/src/index.ts
- packages/shared/src/guards.ts
I had a 404 due to a missing `.env.local` file and it took me a couple of minutes to understand what was going on.
> Assert env vars in demo

- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/vis-packs/core/compound/MappedCompoundMatrixVis.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/lib/src/toolbar/controls/ExportMenu.tsx
Getting closer to #1063 
I pass the `value` of the dataset, which is available in the mapped vis, to the `getExportURL` method of the data provider. This will allow data providers to generate client-side exports without them having to call `valuesStore.get` (which is not doable outside of the `render` pipeline, as the exports will be generated on demand, when clicking on the `ExportMenu` options).
> Pass dataset value to `getExportURL`

- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/models.ts
Before https://github.com/usnistgov/h5wasm/pull/32 is released, entities from h5wasm can be `null` which raises an error in the Provider.
This makes the `null` entities fall back to `Unresolved`.
> Allow H5Wasm entities to be null (e.g. datatype)

- packages/app/src/index.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/shared/src/models-hdf5.ts
Partial fix for [#1063 ](https://github.com/silx-kit/h5web/issues/1063#issuecomment-1293771087)
There was a problem with the `Value<D>` type. In advanced cases, like the one identified by @bmaranville, the shape and dtype of the `Dataset` generic was not properly inferred.
`getExportURL` is only called with array-shaped datasets (`Dataset<ArrayShape>`), but `Value<D>` was not being narrowed down at all. Now, `Value<D>` is properly narrowed down to `unknown[] | TypedArray` (if we go down to the barest types).
```tsx
getExportURL={(format, dataset, selection, value) => async () => {
value.forEach((val) => { /* ... */ }); // `forEach` now works because it is available on both arrays and typed arrays
}}
```
---
I'm also exporting the type of the `getExportURL` function in `@h5web/app` so one …
> Fix `Value<D>` and export `getExportURL` function type

- packages/app/src/vis-packs/core/hooks.ts
- packages/lib/src/vis/heatmap/hooks.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
- packages/shared/src/utils.ts
Three reasons for this:
1. `createMemo` comes from `react-use`, so bring it in helps us move away from this unmaintained library.
2. The implementation is very short, so it's low-risk, low-maintenance.
3. `react-use`'s version was not playing well with functions with overrides: the memoised function would lose the overrides altogether, which prevented memoising some utility functions. I only found one such example, which I've refactored, but perhaps we had worked around other cases or had moved away from using `createMemo` for other reasons (e.g. `useDomain` cannot use `createMemo(getDomain)` because the two internal calls need to be memoised independently.)
> Implement own createMemo that preserves original function's overrides

- packages/app/package.json
- packages/app/src/LoadingFallback.tsx
- packages/app/src/hooks.ts
- packages/app/src/vis-packs/ValueLoader.tsx
- packages/lib/package.json
- packages/lib/src/toolbar/controls/Selector/Selector.tsx
- pnpm-lock.yaml
After #1269, we only had two hooks left from `react-use`:
- `useWindowSize`: can now be used from `react-hookz`
- `useTimeout`: reimplemented in this PR
My implementation does not reach feature parity but I think it fits our simple use of the hook.
> Reimplement useTimeout to remove react-use

- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
- packages/lib/src/vis/tiles/TiledLayer.tsx
- packages/lib/src/vis/tiles/hooks.ts
- packages/lib/src/vis/tiles/utils.ts
In https://github.com/silx-kit/h5web/pull/1193, I moved the handling of the `flip` of the axes inside the `TiledHeatmapMesh` (more specifically at the `TiledLayer` level) to avoid flipping the new `TooltipMesh` that was part of `TiledHeatmapMesh`.
But:
- `TiledTooltipMesh` is now out of `TiledHeatmapMesh`
- In daiquiri-tomo, the `flip` was already handled by a higher-order component (`LinearVisGroup`, also demonstrated in the `WithTransform` story in H5Web). **The flip of axes was therefore applied twice for tiled layers.**
- In `HeatmapMesh`, the `flip` is handled outside of the component and I think we want the two components to behave similarly.
For all these reasons, I moved the handling of `flip` out of `TiledHeatmapMesh` reverting part of #1193.
> Leave `flip` handling out of TiledHeatmapMesh

- apps/storybook/src/Histogram.stories.tsx
- packages/lib/src/toolbar/controls/Histogram/Marker.tsx
Fix #1277 
**Before:** (interaction area in blue)
**After:**
> Extend interaction area of histogram marker to center it

- packages/lib/src/toolbar/controls/Histogram/Markers.tsx
Follow-up of #1280 
The `restrict` prop sets the bound of the **mouse** position while I want to restrict the **marker** position. As I extended the interaction area in #1280, there can be a noticeable mismatch between the two. I therefore store this mismatch (in `deltaX`) so that `restrict` bounds are set to the appropriate value.
> Restrict correctly the marker position when dragging it

- packages/app/src/metadata-viewer/MetadataViewer.tsx
A dataset loaded with h5wasm with no filter shows a disjointed _Compression filters_ header
This PR removes the header if no filter is present
> Do not display the compression filters table in h5wasm if no filter

- apps/storybook/src/HeatmapVis.stories.tsx
- apps/storybook/src/HeatmapVisDisplay.stories.tsx
- apps/storybook/src/VisCanvas.stories.tsx
- packages/app/src/vis-packs/core/heatmap/config.tsx
- packages/app/src/vis-packs/core/heatmap/models.ts
- packages/app/src/vis-packs/core/rgb/config.tsx
- packages/app/src/vis-packs/core/utils.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/models.ts
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/shared/AxisSystem.module.css
- packages/lib/src/vis/shared/AxisSystem.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
- packages/lib/src/vis/shared/Html.tsx
- packages/lib/src/vis/shared/VisCanvas.module.css
- packages/lib/src/vis/shared/VisCanvas.tsx
Part of #1275. Simplifies a lot of things! As discussed someone who wants to get the axes flush against an orthonormal heatmap can always compute the right width/height to give to the canvas' parent element with hard-coded axis offset values.
> Remove `contain` layout and `canvasRatio` prop

- apps/storybook/src/HeatmapVis.stories.tsx
- apps/storybook/src/HeatmapVisDisplay.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- apps/storybook/src/VisCanvas.stories.tsx
- packages/app/src/vis-packs/core/complex/ComplexToolbar.tsx
- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/heatmap/config.tsx
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/rgb/RgbToolbar.tsx
- packages/app/src/vis-packs/core/rgb/config.tsx
- packages/app/src/vis-packs/core/utils.ts
- packages/app/src/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/utils.test.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/models.ts
- packages/lib/src/vis/models.ts
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/utils.ts
Fix #1275 
⚠️ **Significant breaking changes**
- `[VisCanvas]` Prop `visRatio` is replaced with prop `aspect`, which [follows matplotlib](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_aspect.html):
- `'auto'` is equivalent to no `visRatio` (i.e. the heatmap's `'fill'` layout);
- `'equal'` is equivalent to computing `visRatio` from the axis domains to obtain an orthonormal basis (i.e. the heatmap's `cover` layout) -- so now, this ratio computation is performed internally by `VisCanvas` ;
- and if `aspect` is a `number`, then it is used as the ratio directly (this is not used by the viewer; it's just for flexibility of the lib and consistency with matplotlib).
- `[HeatmapVis, RgbVis]` Prop `layout` is replaced with prop `aspect`, which is given sane defaults (`'equal'`) …
> Replace `visRatio` and `layout` props with `aspect` prop

- apps/storybook/src/AxialSelectToZoom.stories.tsx
- apps/storybook/src/DefaultInteractions.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- apps/storybook/src/TiledHeatmapMesh.stories.tsx
- apps/storybook/src/XAxisZoom.stories.tsx
- apps/storybook/src/YAxisZoom.stories.tsx
- apps/storybook/src/hooks.ts
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/DefaultInteractions.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
⚠️ **Breaking change**: `DefaultInteractions` and `SelectToZoom` no longer accept a `keepRatio` prop. Each interaction component adjusts its behaviour automatically when used inside a canvas with an `'equal'` or custom `aspect`.
---
So far, the high-level visualisations had to compute a `keepRatio` flag and pass it to the various interaction components (via `DefaultInteractions`). Since #1284, this flag was computed based on the `aspect` prop passed to `VisCanvas`: `keepRatio={aspect !== 'auto'}`. In practice, this meant that consumers of the low-level components could very well mis-configure the interactions - e.g. by passing `aspect="equal"` to `VisCanvas` and then forgetting to disable axial-zoom interactions.
In this PR, I inject `visRatio` (which is computed internally by …
> Make interaction components smart with regard to canvas aspect

- apps/storybook/src/Context.stories.mdx
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/RatioSelectionRect.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionLine.tsx
- packages/lib/src/interactions/SelectionRect.tsx
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/shared/AxisSystem.tsx
- packages/lib/src/vis/shared/AxisSystemProvider.tsx
- packages/lib/src/vis/shared/Overlay.tsx
- packages/lib/src/vis/shared/TooltipMesh.tsx
- packages/lib/src/vis/shared/TooltipOverlay.tsx
- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
`SelectToZoom` was computing the "ratio to respect" from the visible domains. I came to the realisation that this ratio was always the exact same as the ratio of the canvas, which seems obvious now -- we probably missed it because this wasn't the case when the feature was first developed as we had to iterate quite a bit to get to the current behaviour.
So I decided to inject `canvasRatio` via `AxisSystemContext` and use that directly in `SelectToZoom`. I also decided to inject `canvasSize` for convenience, to avoid using both `useThree` and `useAxisSystemContext` in some places.
> Inject `canvasSize` and `canvasRatio` via context and simplify `SelectToZoom` logic

- apps/storybook/src/DomainSlider.stories.tsx
- apps/storybook/src/Histogram.stories.tsx
- packages/lib/src/toolbar/controls/Histogram/Histogram.tsx
- packages/lib/src/vis/models.ts
Fix #1279 
In `Histogram`:
In `DomainSlider`:
The API is a bit clunky but with #1276 in the works, I thought we should not replicate the axis config API. Feedback welcome though.
> Allow to hide left axis in histogram

- apps/storybook/src/Selection.stories.tsx
- packages/lib/src/interactions/SelectionTool.tsx
For #1296, I'm gonna need access to the selection start/end points in HTML space. Before I can get there, I need to refactor a few things so it doesn't become a huge mess. I'm gonna try to split things up to avoid regressions and make reviewing easier.
First up, I'm storing the entire `selection` in a state inside `SelectionTool` instead of just the `endPoint`. This avoids recomputing `worldStart/EndPoint` during render.
I'm also fixing a very subtle bug in the persisted selection story, where the active and persisted selections would both be visible for one render.
> Avoid duplicate computations in `SelectionTool`

- packages/lib/src/interactions/SelectionTool.tsx
`onSelectionChange` was called on every pointer move event, so it had the potential to affect the performance of the selection tool. I'm moving the call inside a `useEffect` so that it happens asynchronously, after the RAF selection state is updated and after the selection tool and its render prop have had time to re-render.
> Prevent `onSelectionChange` from affecting selection tool performance

- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/RatioSelectionRect.tsx
- packages/lib/src/interactions/SelectionTool.tsx
The goal is twofold:
1. Keep a reference to the start `htmlPt` for #1296 to avoid having to compute it back from the data point.
2. Keep a reference to the start `worldPt` to avoid having to compute it back from the data point in both `onPointerMove` and `onPointerUp`.
I also fix a couple of naming issues. See comments.
> Store full start event in state in `SelectionTool`

- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/shared/RatioEnforcer.tsx
- packages/lib/src/vis/shared/ViewportCenterer.tsx
- packages/lib/src/vis/shared/VisCanvasProvider.tsx
- packages/lib/src/vis/utils.ts
I thought I'd try to bring the vector conversions under control a bit... Basically we need `Vector3` for camera projections, so I thought we could enforce the use of `Vector3` for points in world/camera space. In data/html space, it seems simpler to use `Vector2` as the `z` index makes less sense (in 2D at least...)
> Always use `Vector3` for world/camera and `Vector2` for data/html

- apps/storybook/src/Selection.stories.tsx
- packages/app/src/dimension-mapper/AxisMapper.tsx
- packages/app/src/dimension-mapper/models.ts
- packages/app/src/dimension-mapper/utils.ts
- packages/app/src/vis-packs/core/utils.ts
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/shared/src/models-vis.ts
- I add a prop called `transformSelection` to `SelectionTool`, which allows transforming the selection before it gets passed to `onSelectionChange`, `onSelectionEnd` and the `children` render prop. This cleans up the code of `AxialSelectionTool` quite a bit, since we no longer have to monkey-patch those three props in order to turn the user's selection into an axial selection.
- I change the way `AxialSelectionTool` transforms the user's selection into an axial selection. Instead of doing `data -> world -> data`, we now just do `world -> data`. See comments.
- I move the dimension mapper's `Axis` type (`'x' | 'y'`) into `@h5web/shared` so I can re-use it everywhere. The name technically conflicts with our `Axis` component, but it doesn't seem to be a problem for now.
> Allow transforming selection in `SelectionTool`

- apps/storybook/src/Utilities.stories.mdx
- packages/lib/src/index.ts
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/shared/VisCanvasProvider.tsx
- packages/lib/src/vis/utils.ts
We already had `dataToHtml`; I'm just adding the missing ones. This helps to extract some of the vector conversions and camera projections from the `useCanvasEvents`.
> Add camera utilities `worldToHtml`, `htmlToWorld` and `htmlToData`

- packages/app/package.json
- pnpm-lock.yaml
- Nothing much in https://github.com/testing-library/user-event/releases (from 14.2.0 to 14.4.3) as far as I can tell.
- Some really good stuff in https://github.com/testing-library/dom-testing-library/releases (from 8.13.0 to 8.19.10):
- improved logging for `ByRole` queries (the `name` is now printed);
- improved performance for `ByRole` queries (to be confirmed in CI);
- not new but I've just learnt about the following [debugging feature](https://testing-library.com/docs/queries/about/#screenlogtestingplaygroundurl): `screen.logTestingPlaygroundURL()` -- it logs a URL for debugging the current document in https://testing-playground.com/ which looks really cool.
> Upgrade Testing Library (DOM + user-event)

- .github/workflows/approve-snapshots.yml
- .github/workflows/lint-test.yml
- .github/workflows/release.yml
I was trying to fix a caching issue in the CI related to Cypress binaries, and ended up upgrading all the actions:
- https://github.com/actions/setup-node
- https://github.com/actions/cache/releases
- https://github.com/actions/upload-artifact/releases
- https://github.com/JamesIves/github-pages-deploy-action/releases
- https://github.com/geritol/match-tag-to-package-version/releases
> Upgrade GitHub actions

- packages/app/package.json
- packages/lib/package.json
- pnpm-lock.yaml
Commands for cleaning up files in build:css steps are not cross-platform so replace with node code
> Fix build to work on Windows

- packages/h5wasm/src/H5WasmProvider.tsx
Cherry-picked from https://github.com/silx-kit/h5web/pull/1119
> Fix h5wasm file clean-up in strict mode ahead of React 18 upgrade

- apps/storybook/src/Selection.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/models.ts
Not a huge win (at least for now) in terms of amount of code, but it does feel clearer and it definitely simplifies naming start/end points variables when destructuring, and opens the door to a few simplifications (e.g. one prop/parameter instead of two for `SelectionRect`, `getEnclosedRectangle`, etc.) I haven't made those simplifications yet to keep the PR concise.
> Use tuples to store selection rectangles

- packages/lib/src/vis/heatmap/HeatmapMaterial.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/hooks.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/scatter/ScatterPoints.tsx
- packages/lib/src/vis/scatter/hooks.ts
- packages/lib/src/vis/surface/SurfaceMesh.tsx
- packages/lib/src/vis/surface/hooks.ts
`SurfaceMesh` now uses the same shader as the `HeatmapMesh` (now in a `HeatmapMaterial` to be reusable). This avoids recomputing `BufferAttributes` when changing color map settings.
As a reminder, this shader relies on texture coordinates `uv` to look up the data value in the data texture to then compute the appropriate color. 
**This works in `HeatmapMesh` because the use of a plane geometry means that `uv` are essentially normalized coordinates of the geometry**. As `SurfaceMesh` uses a more complex geometry (an indexed `BufferGeometry`), **this postulate is no longer true**. 
To work around this and still be able to reuse the shader as-is, I now set the `uv` "manually" as attributes of the buffer geometry so that they contain the normalized coordinates expected by the shader. …
> Use shader in SurfaceVis

- apps/storybook/src/AxialSelectToZoom.stories.tsx
- apps/storybook/src/DefaultInteractions.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- apps/storybook/src/Selection.stories.tsx
- packages/lib/src/interactions/SelectionTool.tsx
**EDIT** The problem described below is still accurate, but the solutions I ended up with have changed -- cf. https://github.com/silx-kit/h5web/pull/1317#issuecomment-1344085794
---
Alright, so the axial selection tool stories had not been working for a few days, ever since I moved the `onSelectionChange` call in `SelectionTool` in a `useEffect` (89f5dac3eb1052ca279ef00bc1c00228afadc7bf). Then, the introduction of `transformSelection` made it worse (b3ff1b38f099233eb311f6b6da54ce62f0911b94)...
This is all because some of the selection stories have a state that is updated via `onSelectionChange` (to display the selection in the canvas' title), which means that when the selection changes, the entire `VisCanvas` gets re-rendered and this triggers an infinite render loop.
Obviously, in a real …
> Fix infinite render loop in axial selection tool stories

- .github/workflows/approve-snapshots.yml
- .github/workflows/lint-test.yml
- .github/workflows/release.yml
`actions/setup-node` does not and will not provide a way to pass additional paths to its internal `actions/cache` instance, so I move caching into a separate step that takes care of caching both the pnpm store and Cypress binaries.
> Use single cache for both pnpm store and Cypress binaries in CI

- apps/storybook/src/Selection.stories.tsx
- packages/lib/src/interactions/SelectionTool.tsx
Now that the callbacks are stable, we can really embrace `useEffect`. This PR moves the calls to `onSelectionStart` and `onSelectionEnd` into the `useEffect`.
In addition to reducing the potential impact on performance of consumers doing something really heavy in the callbacks, it also allows me to easily fix two bugs:
1. `onSelectionStart` is now called only when the user actually starts dragging. So a simple click no longer creates a selection and no longer invokes any of the callbacks.
2. `onSelectionEnd` is now called _after_ the render prop, which means that if the consumer persists the selection in `onSelectionEnd` and displays it, we no longer see two selections stacked on top of each other for one render. This allows us to remove the workaround for this subtle bug from the …
> Invoke selection start/end callbacks asynchronously

- packages/lib/src/interactions/SelectionLine.tsx
- packages/lib/src/interactions/SelectionRect.tsx
- packages/lib/src/vis/shared/SvgElement.tsx
- packages/lib/src/vis/shared/VisCanvas.module.css
- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/shared/VisCanvasProvider.tsx
Basically the replacement for SVG scene.
SVG elements wrapped in `SvgElement` get appended to this new global `svg` overlay container via a portal, similarly to floating toolbar controls. When it comes to naming, I hestiated with `SvgShape`, `Svg`, etc. but had issues with each. We can discuss this in person if you like @loichuder .
> Add SVG overlay and `SvgElement` helper

- packages/app/src/__tests__/CorePack.test.tsx
- packages/app/src/__tests__/DimensionMapper.test.tsx
- packages/app/src/__tests__/MetadataViewer.test.tsx
- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/__tests__/VisSelector.test.tsx
- packages/app/src/__tests__/Visualizer.test.tsx
- packages/app/src/test-utils.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
Part three of bringing in test improvements from https://github.com/silx-kit/h5web/pull/1119
> Allow rendering app with preferred vis in tests and improve testing of vis tabs

- packages/app/src/__tests__/NexusPack.test.tsx
Part four of bringing in test improvements from https://github.com/silx-kit/h5web/pull/1119
> Group together  and reorder `NexusPack` tests

- packages/app/src/__tests__/CorePack.test.tsx
- packages/app/src/__tests__/Explorer.test.tsx
- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/__tests__/Visualizer.test.tsx
- packages/app/src/setupTests.ts
- packages/app/src/test-utils.tsx
Part five of bringing in test improvements from https://github.com/silx-kit/h5web/pull/1119
> Abstract away enabling fake timers in tests

- CONTRIBUTING.md
- apps/demo/.env
- packages/app/src/__tests__/CorePack.test.tsx
- packages/app/src/__tests__/DimensionMapper.test.tsx
- packages/app/src/__tests__/DomainSlider.test.tsx
- packages/app/src/__tests__/Explorer.test.tsx
- packages/app/src/__tests__/MetadataViewer.test.tsx
- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/__tests__/VisSelector.test.tsx
- packages/app/src/__tests__/Visualizer.test.tsx
Part six, and final, of bringing in test improvements from https://github.com/silx-kit/h5web/pull/1119
I diffed all the test files and brought a few more things over, including some of the documentation from: https://github.com/silx-kit/h5web/pull/1119/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055
Only thing that's left and that can't be ported is all the async `Suspense` stuff: waiting for all loaders to disappear; using `getBy` instead of `findBy` in tests with real timers; and using `findBy` with a timeout in tests with fake timers. This stuff requires upgrading  React Testing Library to v13, which requires upgrading React to v18.
> Add doc on feature tests and make minor test improvements

- packages/app/src/vis-packs/core/visualizations.ts
- packages/app/src/visualizer/utils.ts
I think our process for enabling experimenal vis was not working properly: the SurfaceVis did appear only when hot-reloading a dev version of the project.
I think this is due to the fact that `window.H5WEB_EXPERIMENTAL` is read before it is set by the `DemoApp` component. Since `window.H5WEB_EXPERIMENTAL` is `undefined`, the SurfaceVis is not enabled (expect if the reading of the variable is triggerred by a hot reloading).
To fix this, I now read `window.H5WEB_EXPERIMENTAL` in the `supportsDataset` function of the SurfaceVis so that its value is always up to date.
> Fix experimental vis not appearing

- package.json
Added in pnpm 7.19: https://pnpm.io/package_json#pnpmrequiredscripts
Note that it only makes sense for linting scripts, which are run with `pnpm run --recursive` (`pnpm -r`). There is a `build` script in every project, but we run those on a per project basis or with a `--filter`.
> Specify pnpm scripts required in every projects

- packages/lib/src/interactions/SelectionTool.tsx
Very minor, subtle bug: consumers of `SelectionTool` registering an `onSelectionChange` callback were not being notified of the first pointer move event. `SelectionTool` was calling `onSelectionStart` but not `onSelectionChange` after the first pointer move event. This is now corrected.
> Fix selection change callback not called on first pointer move

- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/hooks.ts
I realised that the transformed selection as well as the future `isValid` boolean can be derived from the raw selection state; they don't need to be part of the local state. As a result, the justification for having an `isCancelled` flag in the state made in #1338 no longer holds.
So in this PR, I'm going back a little by first reverting #1338 (sorry for the back and forth...) Then, I compute the transformed selection (which I refer to as the "effective" selection in comments) as a derived state in a `useMemo`, and I pass this effective `selection` object to the render prop and to the callbacks.
Finally, now that the render prop of `SelectionTool` has access to both the raw and effective selections, I can refactor `SelectToZoom` in order to compute the effective zoom selection in a …
> Invoke `SelectionTool` render prop and callbacks with transformed selection

- apps/storybook/src/Context.stories.mdx
- apps/storybook/src/SelectionTool.stories.tsx
- apps/storybook/src/SvgLine.stories.tsx
- apps/storybook/src/SvgRect.stories.tsx
- apps/storybook/src/Utilities.stories.mdx
- apps/storybook/src/utils.ts
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
- packages/lib/src/svg/SvgLine.tsx
- packages/lib/src/svg/SvgRect.tsx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/shared/Annotation.tsx
- packages/lib/src/vis/shared/DataToWorld.tsx
- packages/lib/src/vis/shared/ViewportCenterer.tsx
- packages/lib/src/vis/shared/VisCanvasProvider.tsx
- packages/lib/src/vis/utils.ts
Using `Vector2` in HTML and data spaces is actually really inconvenient -- it was making it difficult to explore solutions for switching `SelectionTool` to HTML space. By using `Vector3` in all three coordinate spaces, we can for instance use the `Box` abstraction in all three spaces without pain.
> Use `Vector3` in all coordinate spaces

- apps/storybook/src/AxialSelectionTool.stories.tsx
- apps/storybook/src/SelectionTool.stories.tsx
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/box.ts
At last, the `SelectionTool` can now report whether the selection is valid or not!
By default, it checks for a default width and height of 20px, which seems to be a sensible default behaviour for rectangle selections. Since the validity check is performed on the transformed selection, this behaviour works perfectly for both `SelectToZoom` and `AxialSelectToZoom`:
However, the default validation behaviour does not work for line selection (e.g. for drawing line profiles), as in this case, what matters is the length of the line, not the size of the box. To cover this use case (and most likely others), `SelecionTool` simply accepts a custom validation function. This function has access to the current selection in all three coordinate spaces, so it's really flexible:
> Support validating selections

- apps/storybook/src/AxialSelectionTool.stories.tsx
- apps/storybook/src/SelectionTool.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/SelectToZoom.module.css
- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/svg/SvgElement.tsx
- packages/lib/src/interactions/svg/SvgLine.tsx
- packages/lib/src/interactions/svg/SvgRect.tsx
- packages/lib/src/interactions/utils.ts
- packages/lib/src/vis/shared/DataToHtml.tsx
And.... `SvgRect` and `SvgLine` are back!! 😂 
This is something I had been meaning to fix for a while. Notice how the stroke of the zoom rectangle gets cropped by the the canvas:
What it looks like now:
This is a good use case for re-introducing `SvgRect` and `SvgLine`, as "shifting" the stroke inside of the rectangle requires knowing the `strokeWidth` (and whether `stroke` is declared at all). Utilities aren't great to handle this.
Note, however, that I'm now choosing to keep `SvgElement` out of `SvgRect/Line`.
> Prevent stroke of zoom rectangles from being cropped by canvas

- apps/storybook/src/SelectionTool.stories.tsx
- apps/storybook/src/SvgElement.stories.module.css
- apps/storybook/src/SvgElement.stories.tsx
- packages/lib/src/interactions/AxialSelectionTool.tsx
- packages/lib/src/interactions/SelectionTool.tsx
> Document transforming selections and rendering SVG elements

- .github/workflows/release.yml
- CONTRIBUTING.md
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
This helps with publishing H5Web's packages manually - e.g. to a local registry like Verdaccio: https://github.com/silx-kit/h5web/discussions/1334#discussioncomment-4707965.
I will publish a beta version once merged to confirm that this work as expected.
> Remove `type` fields in prepublish scripts instead of CI

- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/utils.ts
- packages/shared/src/mock/metadata.ts
- packages/shared/src/mock/values.ts
Fix #1350 
I'm loosening the assertion on the length of the `abscissa` array by allowing it to be longer than the data array. If it is, it just gets sliced to the data array's length. I don't think we need to be stricter than that.
Another option was to remove the extra value from the abscissa array inside the NX containers, but it would not have solved the issue for consumers of `@h5web/lib`.
> Allow passing longer abscissa array that data array to `LineVis`

- packages/lib/src/toolbar/controls/Histogram/Histogram.tsx
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/DataCurve.tsx
- packages/lib/src/vis/line/hooks.ts
- packages/lib/src/vis/scatter/ScatterPoints.tsx
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/scatter/hooks.ts
- packages/lib/src/vis/utils.ts
Fix #1356 
Avoid converting to number[] if possible, remove useToArray hook
> Broaden arguments and props to use NumArray for #1356

- packages/lib/src/interactions/SelectionTool.tsx
Fixes a minor bug in the `SelectionTool` and `AxialSelectionTool` stories. Now, when a selection is cancelled with Escape or by releasing the modifier key, the title of the canvas is reset to "No selection" as expected. This is achieved by calling `onSelectionEnd` with `undefined` when the selection is cancelled.
> Invoke `onSelectionEnd` callback when cancelling selection

- packages/lib/src/vis/shared/VisCanvas.tsx
- packages/lib/src/vis/utils.test.ts
- packages/lib/src/vis/utils.ts
In #1284 I say that the new `aspect` prop of `VisCanvas` works like matplotlib's [`Axes.set_aspect`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_aspect.html), but this was not actually true. When passing a number, this number was used as the `visRatio` directly. The beahviour is now in line with matplotlib - i.e. for `aspect={2}`, we get:
> Make `aspect` prop of `VisCanvas` really consistent with matplotlib

- apps/storybook/src/Annotation.stories.tsx
- apps/storybook/src/Utilities.stories.mdx
- apps/storybook/src/decorators/DefaultCanvas.tsx
- apps/storybook/src/utils.ts
- eslint.shared.js
- packages/lib/src/toolbar/floating/ResetZoomButton.tsx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/shared/Annotation.tsx
- packages/lib/src/vis/shared/AxisSystem.tsx
- packages/lib/src/vis/shared/DataToHtml.tsx
- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
I went a bit too far in #1361 by removing the `useEffect` and `deps` array parameter from `useCameraState`. This change broke two library components: `DataToHtml` and `Annotation`, as well as any use of `useCameraState` where the factory function relies on external dependencies. Without `useEffect`, `useCameraState` was no longer recomputing the state when the dependencies changed.
In this PR, I fix this regression by restoring the dependencies array parameter and recommending once again to configure linting rule `exhaustive-deps`. However, instead of restoring `useEffect`, which was triggering an extra render on every dependency change, I replace `useState` with `useRef` and update the ref via `useMemo`. This means that the state is now updated synchronously during the current render. It …
> Fix regression in `useCameraState` when dependencies change

- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/h5wasm-api.ts
Fix #1371 
Oversight in the `BigInt` conversion: we only checked for regular integers and not unsigned.
> Add support for unsigned 64-bit integers in h5wasm

- packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx
I need to avoid displaying the "background" color while the `TiledHeatmapMesh` is loading, i.e., not displaying this `mesh`:
https://github.com/silx-kit/h5web/blob/83c5c513ee0e6d3c6e05b29ede5353ae77f254e6/packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx#L79-L84
~~This PR proposes to add a `background` prop that allows to configure this.~~
~~I hesitated to completely remove this `mesh` and leave it to the users to implement it, but since it's there...~~
~~By default it uses the color of the smallest value of the colormap, it accepts a color as well as 'none' to disable it.~~
This PR removes the background mesh. If needed, it can be added below the `TiledHeatmapMesh`.
> Remove background mesh from `TiledheatmapMesh`

- packages/lib/src/toolbar/Toolbar.tsx
This is to address part of #1377 and allows us to move less commonly used toolbar buttons off the main bar
> Add prop to manually add components to overflow menu

- apps/storybook/src/SvgElement.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/svg/SvgCircle.tsx
Bringing in this component from Braggy where it is used for [drawing circular profiles](https://gitlab.esrf.fr/ui/h5web-braggy/-/blob/1a61841290e7fed59ee5caa0ddf0ed1f89fc7167/src/imageview/profile/ProfileSelectionTool.tsx).
As shown in the story below, where the circle and the rectangle share the same set of `Rect` coordinates, I went with a simple implementation that matches the SVG attributes: the center of the circle is the `start` point and the radius is the distance between `start` and `end`.
We could imagine providing additional features later, such as drawing inscribed and circumscribed circles, if the need arises.
> Add `SvgCircle` component

- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/h5wasm/package.json
- packages/h5wasm/src/h5wasm-api.ts
- pnpm-lock.yaml
Pre-requisite for #1348 
Adds a `getSearchablePaths` mathods to API to return a list of paths in the group. This method can be implemented by the APIs that support it (for now, `h5grove` and `h5wasm` that was updated to 0.4.10)
> Add API for searchable paths

- apps/storybook/src/AxialSelectToZoom.stories.tsx
- apps/storybook/src/SelectToZoom.stories.tsx
- packages/lib/src/interactions/AxialSelectToZoom.tsx
- packages/lib/src/interactions/SelectToZoom.tsx
I'm adding a prop called `minZoom` to both `SelectToZoom` and `AxialSelectToZoom` to allow changing the default min zoom size of 20px.
> Allow controlling min select-to-zoom sizes

- apps/storybook/src/Stacking.stories.mdx
- packages/lib/src/vis/shared/Annotation.tsx
- packages/lib/src/vis/shared/Overlay.tsx
- packages/lib/src/vis/shared/TooltipMesh.module.css
- packages/lib/src/vis/shared/TooltipOverlay.tsx
- packages/lib/src/vis/shared/VisCanvas.module.css
Regression introduced in #1387 ... so much for bringing stacking under control :sweat: 
The canvas was still stacked implicitly at `z-index: 0`, so in front of the grid and SVG elements... Sorry about that. So now it moves behind everything.
Unfortunately, in doing so, `r3fRoot`—which is still stacked implicitly at `z-index: 0` (and cannot be stacked explicitly without creating a new stacking context and breaking the stacking order, as explained in a comment in the CSS)—captures events before the reach the canvas... I had to work around this by moving `pointer-events: none` to `r3fRoot` instead of setting it on every overlay, and then re-enabling it to `auto` on the canvas and floating toolbar.
This feels better in the end, since it removes a bunch of `pointer-events: none` and saves us …
> Fix stacking order of canvas

- apps/demo/src/H5GroveApp.tsx
- apps/demo/src/HsdsApp.tsx
- apps/demo/src/MockApp.tsx
- apps/demo/src/h5wasm/H5WasmApp.tsx
- cypress/e2e/app.cy.ts
- packages/app/README.md
- packages/app/src/App.tsx
- packages/app/src/__tests__/Explorer.test.tsx
- packages/app/src/breadcrumbs/BreadcrumbsBar.tsx
As discussed, I'm deprecating `explorerOpen` instead of removing it to avoid a breaking change in the short term. We'll remove it in v8.
> Deprecate prop `explorerOpen` in favour of `sidebarOpen`

- apps/storybook/src/DataCurve.stories.tsx
- apps/storybook/src/HeatmapMesh.stories.tsx
- apps/storybook/src/HeatmapVis.stories.tsx
- apps/storybook/src/LineVis.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapMaterial.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/hooks.ts
- packages/lib/src/vis/heatmap/utils.ts
This PR suggests renaming the `maskValues` prop in `HeatmapMesh` and `HeatmapMaterial` to just `mask`.
I know `maskValues` takes inspiration from prop `alphaValues`, but I feel like this is a bit different, since a "mask" in this context implies that it's an array, so the `Values` suffix feels redundant. More importantly, `maskValues` can be interpreted as a callback, like `ignoreValue`, since `mask` can be a verb. 
In addition to this, I document the `ignoreValue` and the now-called `mask` props in Storybook:
> Rename prop `maskValues` to `mask`

- .github/workflows/approve-snapshots.yml
- .github/workflows/lint-test.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- apps/demo/package.json
- apps/storybook/package.json
- cypress/support.ts
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- pnpm-lock.yaml
There's a bunch of default configuration changes and a new lockfile version that is apparently more resilient to merge conflicts: https://github.com/pnpm/pnpm/releases/tag/v8.0.0
Config changes that are worth mentioning:
- [`auto-install-peers`](https://pnpm.io/npmrc#auto-install-peers): now enabled by default – as the name implies, pnpm now installs missing peer deps automatically, so we can remove a bunch of overrides from `package.json`. npm decided to reinstate the automatic installation of peer dependencies in v7+, which brought out a whole bunch of problems ... but pnpm can actually do it safely thanks to its non-flat `node_modules` structure.
- [`resolution-mode`](https://pnpm.io/npmrc#resolution-mode): changed from `highest` (`^1.0.0` => `1.2.3`) to `lowest-direct` (`^1.0.0` => …
> Require pnpm v8

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/lib/src/interactions/box.ts
- packages/shared/src/mock/metadata.ts
- packages/shared/src/mock/values.ts
- tsconfig.json
Inspired by https://www.npmjs.com/package/@tsconfig/strictest. I tried enabling a few more options but in the end, I've made only one change to `tsconfig.json`. The other options specified in `@tsconfig/strictest` that we don't already specify are either:
- too crazy and not worth the pain (`exactOptionalPropertyTypes`, `noUncheckedIndexedAccess` and `noPropertyAccessFromIndexSignature`); or
- overly restrictive in development and already reported by ESLint anyway (`allowUnreachableCode`, `noUnusedLocals`, `noUnusedParameters`).
They did allow me to detect and fix a few minor issues, though, which is nice.
> Enforce slightly stricter TS config

- packages/lib/src/vis/line/LineVis.tsx
For https://github.com/silx-kit/jupyterlab-h5web/issues/118
Oversight from our part in `h5web`: we took care of removing the `invert` on curve colors but not on the legend handles displayed when there are several signals.
The issue is visible at https://h5web.panosc.eu/mock on the path `/nexus_entry/spectrum_with_aux` in dark mode.
> Keep the color of curve color legend handles in dark mode

- packages/h5wasm/src/h5wasm-api.ts
https://github.com/silx-kit/h5web/pull/1424#issuecomment-1515863874
Unfortunately, this does not work for some reason. See the path `/gzip` in https://h5web.panosc.eu/h5grove?file=compressed.h5 that has `Chunk size` for h5grove and not for h5wasm.
Perhaps an issue to forward to Brian.
> Parse and display chunks when present in h5wasm metadata

- CONTRIBUTING.md
- apps/demo/package.json
- apps/storybook/package.json
- package.json
- packages/app/package.json
- packages/app/vite.config.js
- packages/h5wasm/package.json
- packages/lib/package.json
- packages/lib/src/index.ts
- packages/lib/src/toolbar/OverflowMenu.tsx
- packages/lib/src/toolbar/Toolbar.tsx
- packages/lib/vite.config.js
- packages/shared/src/guards.ts
- pnpm-lock.yaml
I had tried the upgrade before (cf. https://github.com/silx-kit/h5web/pull/1353) but had run into issues when running tests in Braggy. Turns out Vite 4 upgrades its internal version of Rollup to v3, which changes a bunch of default configuration options: https://rollupjs.org/migration/#changed-defaults
Jest loads CommonJS scripts when available (otherwise it loads ESM modules and transforms them to CommonJS before running the tests). The problem was that some of the `require` statements in the CommonJS bundle of `@h5web/lib` were returning objects with a `default` property (instead of the content of that `default` property directly). In other words, some ESM imports in the lib were transformed into `require('...')` instead of `require('...').default` by Vite/Rollup.
The culprit was …
> Upgrade Vite to v4

- apps/demo/tsconfig.json
- apps/storybook/tsconfig.json
- packages/app/tsconfig.json
- packages/h5wasm/package.json
- packages/h5wasm/src/models.ts
- packages/h5wasm/tsconfig.json
- packages/lib/tsconfig.json
- packages/shared/tsconfig.json
- pnpm-lock.yaml
- tsconfig.bundler.json
- tsconfig.json
[H5wasm v0.5.0](https://github.com/usnistgov/h5wasm/releases/tag/v0.5.0) brings the ability to [dynamically link](https://emscripten.org/docs/compiling/Dynamic-Linking.html) WASM modules at runtime, which will hopefully allow us to support HDF5 compression plugins in the `@h5web/h5wasm` package (notably for [myHDF5](https://myhdf5.hdfgroup.org/) and the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=h5web.vscode-h5web)).
In addition, [h5wasm v0.5.2](https://github.com/usnistgov/h5wasm/releases/tag/v0.5.2) (v0.5.1 was skipped) fixes a package distribution issue that prevented it from working with TS's new [`moduleResolution: "bundler"` setting](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler). I've now switched to this …
> Upgrade h5wasm and switch to TS' `"moduleResolution": "bundler"`

- .github/workflows/lint-test.yml
- cypress.config.ts
- cypress/support.ts
- cypress/tsconfig.json
- package.json
- pnpm-lock.yaml
A fork of `cypress-image-snapshot` has been rewritten and turned into a source repository: https://github.com/simonsmith/cypress-image-snapshot -- here is how this benefits us:
- compatibility with Cypress 12 (no more peer dep warning to ignore)
- types included
- ability to error on CI when a new snapshot is created, thus removing the need to run `git status`
> Switch to maintained `cypress-image-snapshot` package

- .github/workflows/deploy-storybook.yml
- .github/workflows/lint-test.yml
- .github/workflows/publish-packages.yml
... and try [new GitHub Pages deployment](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) ([more info](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow)). Instead of deploying via a `github-pages` branch, we can now deploy to a special [`github-pages` "environment"](https://github.com/silx-kit/h5web/settings/environments/1423492/edit).
This allows us to remove the `.nojekyll` workaround, since Jekyll is not involved in the new deployment process. Obviously, I'll have to merge this PR to try the new workflow, but I've added a manual trigger, so I won't have to publish a tag.
> Split Storybook deployment workflow from package publishing

- .eslintrc.js
- cypress/support.ts
- packages/lib/src/index.ts
- packages/lib/src/vis/line/utils.ts
- packages/lib/src/vis/models.ts
- packages/lib/src/vis/scatter/utils.ts
- packages/lib/src/vis/shared/Axis.tsx
- packages/lib/src/vis/shared/VisCanvasProvider.tsx
- packages/lib/src/vis/utils.ts
Follow-up to #1431 to enforce stricter types for the internal `createScale` and `getCanvasScale` utility functions, and therefore for `abscissaScale` and `ordinateScale` (exposed through `VisCanvasContext`).
To do so, I've added a generic to `Scale`, in order for `abscissaScale` and `ordinateScale` to be typed as `Scale<AxisScaleType>`, and I've reintroduced `AxisScale` (removed in #1431, as before it incorrectly meant "any of the supported scales") as an alias to this type.
The [Storybook](https://h5web-docs.panosc.eu/?path=/docs/context--docs) was still saying that the type of `abscissaScale` and `ordinateScale` was `AxisScale` even though it had basically been renamed to `Scale` in #1431. But with the stronger typing and the reintroduction of `AxisScale`, it is now correct.
> Type `abscissaScale` and `ordinateScale` more strictly

- .github/workflows/lint-test.yml
- .github/workflows/publish-packages.yml
We don't actually need to build the packages before building the demo for Cypress to play with. This should shave roughly 40s off the `e2e` job (in theory ... probably more like 20s in practice).
> Build packages in separate job from E2E tests in CI

- apps/demo/vite.config.js
Linting and type checking in the demo project can be run separately from the production build (and potentially in parallel) with `pnpm lint:eslint` and `pnpm lint:tsc`. This is already the case in the CI (we build the demo before running the E2E tests), so we were basically doubling up on the work.
> Skip linting and type checking when building for production to save time

- apps/storybook/package.json
- apps/storybook/src/Annotation.stories.tsx
- pnpm-lock.yaml
https://github.com/storybookjs/storybook/releases from v7.0.5 to v7.1.1. There's a v7.0.27, so I recommend skipping the release notes, except maybe for https://github.com/storybookjs/storybook/releases/tag/v7.1.0 and https://github.com/storybookjs/storybook/releases/tag/v7.0.25.
The latter patch release fixed an issue that prevented us from rendering `VisCanvas` in decorators. I demonstrate this in `Annotation.stories.tsx` to avoid duplication, but that's the only place I found this pattern to be really useful. At first, I wanted to use it in the `HeatmapMesh.stories.tsx`, for instance, as a way to avoid declaring a custom `render` function in the `Default` stories (and, as a consequence, avoid spreading the `Default` object in all the subsequent stories objects), but on second thought, …
> Upgrade Storybook

- packages/lib/src/vis/shared/R3FCanvas.tsx
Fix #1453. I was able to trace this regression back to the extraction of the `R3FCanvas` component in #1303. The `gl` prop got dropped and we didn't notice it. Thanks for the report @LogWell!
> Preserve GL buffer to fix "save image as"

- packages/lib/src/interactions/SelectionTool.tsx
Fix #1370 -- this is quite a neat interaction, actually.
Couple of notes:
- Pressing the context menu key on the keyboard also cancels the interaction.
- Firefox does not fire the [`contextmenu` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) at all when <kbd>Shift</kbd> is pressed. So with the proposed solution, a select-to-zoom interaction configured with the `Shift` modifier key cannot be cancelled with right click.
> Allow canceling select-to-zoom interaction with right click

- apps/storybook/src/Annotation.stories.tsx
While working on refactoring `Html` in #1465 , I noticed that the `Annotation` stories were in need of a good clean-up.
I took full advantage of Storybook by splitting each annotation example into its own story, which means that the controls now work as expected and the props are properly listed in the _Docs_ page.
I also:
- removed the SVG story, since `Annotation` is no longer the recommended way to render SVG elements;
- added a story to document `overflowCanvas`.
This actually uncovered a bug: annotations that overflow the canvas are not positioned properly, since they are positioned relatively to the `canvasWrapper` element, which includes the axes. I have an idea to fix this, but I'll continue working on declarative axes first.
> Clean up and improve `Annotation` stories

- apps/storybook/src/Utilities.mdx
- packages/lib/src/index.ts
- packages/lib/src/interactions/InteractionsProvider.tsx
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/interaction.ts
- packages/lib/src/interactions/models.ts
- packages/lib/src/interactions/utils.ts
Following #1475, I'm documenting the newly exported `useInteraction` and `useModifierKeyPressed` hooks.
I'm also taking the opportunity to do a bit of a refactoring now, to avoid a breaking change down the line:
- `InteractionEntry` (the second parameter of `useInteraction`) becomes `InteractionConfig`
- We no longer need to cast the `modifierKey` prop to an array before calling `useInteraction` and `useMdifierKeyPressed` (thus removing the need for `getModifierKeyArray`)
- I'm introducing an `Interaction` class internally to encapsulate the casting of the `modiferKeys` and `buttons` arrays and the logic of whether an interaction "matches" a mouse event.
> Simplify and document usage of `useInteraction` and `useModifierKeyPressed`

- apps/storybook/src/Html.stories.tsx
- packages/lib/src/vis/shared/Html.tsx
`Html` allows rendering HTML elements from inside React Three Fiber's renderer. It works by appending a `div` to the DOM and rendering its children into it with `ReactDOM.render()`. The `div` is appended to `r3fRoot` by default, to `canvasWrapper` when `overflowCanvas` is set, or to a custom container when `container` is set.
The problem currently is that the children of `Html` always end up wrapped in an extra `div`. This is a bit annoying when debugging the DOM and it's quite limiting as the extra `div` can make styling cumbersome and can lead to invalid HTML (e.g. `div > svg`). We worked around this extra `div` before in `FloatingControl` and `SvgElement` by rendering the children into another container through a portal. 
The `container` prop has other issues, like the fact that it has …
> Refactor `Html` with portal

- packages/app/src/__tests__/CorePack.test.tsx
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
This is a proposal to fix #917. I'm basically just improving the fallback message to clarify which console it's talking about and how users can access it:
> Improve `RawVis` fallback message when dataset is too big to display

- packages/lib/src/interactions/SelectToZoom.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/svg/SvgRect.tsx
Fix #1407 
I've changed the selection validation logic in `SelectToZoom` to compute the manahattan distance. I'm no longer converting the selection to a `Box` and calling `#hasMinSize`, since `Vector3` already provides a method for computing the manhattan distance.
Of course there are always edge cases to deal with and unforeseen consequences...
---
The edge case is zooming on a 0-width or 0-height box. To deal with this, I had a few options:
1. Keep a `hasMinSize(1)` check in the `validate` prop.
- This kinda goes against the premise of #1407 that if the user releases the pointer, something should happen.
- It also meant that we could see a dashed line when crossing the 0 width/height threshold (because that's the style of an invalid selection box). This style made more sense when the …
> Allow zooming on very thin selection boxes

- packages/app/src/vis-packs/core/complex/config.tsx
- packages/app/src/vis-packs/core/complex/lineConfig.tsx
- packages/app/src/vis-packs/core/heatmap/config.tsx
- packages/app/src/vis-packs/core/line/config.tsx
- packages/app/src/vis-packs/core/matrix/config.tsx
- packages/app/src/vis-packs/core/rgb/config.tsx
- packages/app/src/vis-packs/core/scatter/config.tsx
- packages/app/src/vis-packs/core/surface/config.tsx
No error during the build, but the TS language server in VS Code was not happy. A fix was already in place in the config of the `SurfaceVis` toolbar, but it wasn't working in the `LineVis` toolbar config because of the `partialize` option passed to the `persist` middleware. I found another way to fix the error.
> Fix TS errors in toolbar configs reported only in VS Code

- apps/storybook/src/SvgElement.stories.tsx
- apps/storybook/src/Utilities.mdx
- apps/storybook/src/useDrag.stories.module.css
- apps/storybook/src/useDrag.stories.tsx
- packages/lib/src/index.ts
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
This should hopefully make implementing draggable interactions easier (e.g. moving/resizing ROIs), though I'm hoping it will also abstract out a lot of the code from `SelectionTool` and `Pan`.
The approach taken by `@visx/drag` is not great for us because of our multiple coordinate spaces and because it requires capturing events on a transparent rectangle on top of the element that is being dragged.
Instead, the approach I'm proposing makes use of the new event bubbling mechanism introduced in #1473: `useDrag` automatically registers the `pointermove` and `pointerup` event handlers on `canvasWrapper` with `useCanvasEvents`, thus making sure that no events are missed. The consumer only needs to register a `pointerdown` handler on the draggable element.
I've created a story to demonstrate …
> Implement `useDrag` hook

- apps/storybook/src/Annotation.stories.tsx
- apps/storybook/src/Utilities.mdx
- packages/lib/src/index.ts
- packages/lib/src/interactions/Pan.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/interactions/XAxisZoom.tsx
- packages/lib/src/interactions/YAxisZoom.tsx
- packages/lib/src/interactions/Zoom.tsx
- packages/lib/src/interactions/hooks.ts
- packages/lib/src/interactions/models.ts
I'm rethinking `useCanvasEvents` a bit. The hook is now called `useCanvasEvent` (singular) and allows registering only one event listener at a time. This brings the API closer to that of `useEventListener` from react-hookz and avoids registering event listeners that are not actually used.
Additional benefits of the new implementation:
- It allows more events to be registered, not just `pointerdown`, `pointerup`, `pointermove` and `wheel` — so basically any event that has `offsetX` and `offsetY` (i.e. any event that extends `MouseEvent`, including `WheelEvent`, `PointerEvent`, `DragEvent`).
- It uses `useSyncedRef` so consumers don't have to wrap their listeners in `useCallback` — this simplifies a bunch of code.
- It allows overriding the options passed to `addEventListener`, notably …
> Improve hook to register events on canvas

- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/utils.ts
I was playing with compound datasets as part of #1485 when I noticed this "Unknown" type. Definitely a bit of a niche fix...
| Before | After |
|--------|--------|
| ![image](https://github.com/silx-kit/h5web/assets/2936402/1d76d27e-15ad-4ba3-8936-320c47dda4ee) | ![image](https://github.com/silx-kit/h5web/assets/2936402/7e2295d3-2981-4621-a682-24eed571bf8a) |
> Parse nested array types returned by h5wasm

- packages/app/src/__tests__/CorePack.test.tsx
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/app/src/vis-packs/core/raw/RawToolbar.tsx
- packages/app/src/vis-packs/core/raw/RawVisContainer.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/lib/src/toolbar/OverflowMenu.module.css
- packages/lib/src/toolbar/controls/ExportMenu.tsx
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
- packages/shared/src/mock/values.ts
The `Raw` visualization now supports exporting datasets to JSON when using the h5grove, h5wasm and mock providers.
This provides a much better solution to issue #917 than PR #1462 . As such, large raw datasets that can't be rendered on the screen are no longer logged to the console.
Concerning large datasets, I took the opportunity to do some more testing and decided to increase the threshold for when a dataset is considered to be large by a few orders of magnitude. This is purely empirical...
> Add JSON export to Raw visualization

- packages/lib/src/vis/raw/RawVis.module.css
The root, scrollable container was not taking up the whole width:
> Fix CSS of Raw vis

- CONTRIBUTING.md
- packages/lib/package.json
- packages/lib/vite.config.js
- pnpm-lock.yaml
`react-keyed-flatten-children` [now has an ESM bundle](https://github.com/grrowl/react-keyed-flatten-children/blob/master/CHANGELOG.md), which means we should be able to revert the workaround that consisted in inlining it in the lib's output bundle (cf. #914). It is now marked as an `external` in the Vite config, just like every other prod dependency.
> Revert workaround of bundling in `react-keyed-flatten-children`

- CONTRIBUTING.md
- apps/demo/package.json
- apps/demo/vite.config.js
- apps/storybook/package.json
- packages/app/package.json
- packages/app/rollup.config.js
- packages/app/src/index.ts
- packages/h5wasm/package.json
- packages/h5wasm/rollup.config.js
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/lib/package.json
- packages/lib/rollup.config.js
- pnpm-lock.yaml
Vite 4.4 adds a couple of convenient keyboard shortcuts to the CLI, including one for opening the browser. As a result, I decided to disable opening the browser by default, as this can be annoying sometimes.
Unrelated: after the `rollup` upgrade in #1490, we were getting a lot of warnings when building packages. It turned out that the `index.d.ts` generated for each package was including all the React types! So I'm fixing this.
Also, there was a type import from `@h5web/app/src` in `@h5web/h5wasm` that shouldn't have been there.
> Upgrade Vite and fix generated declaration files

- apps/demo/src/h5wasm/H5WasmApp.module.css
- packages/app/src/breadcrumbs/BreadcrumbsBar.module.css
- packages/app/src/dimension-mapper/DimensionMapper.module.css
- packages/app/src/dimension-mapper/SlicingSlider.module.css
- packages/app/src/explorer/Explorer.module.css
- packages/app/src/search/Search.module.css
- packages/app/src/vis-packs/ValueLoader.module.css
- packages/app/src/visualizer/Visualizer.module.css
- packages/lib/src/toolbar/Toolbar.module.css
- packages/lib/src/toolbar/controls/DomainWidget/BoundEditor.module.css
- packages/lib/src/toolbar/controls/DomainWidget/DomainControls.module.css
- packages/lib/src/toolbar/controls/DomainWidget/DomainWidget.module.css
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/vis/heatmap/ColorBar.module.css
- packages/lib/src/vis/heatmap/HeatmapVis.module.css
- packages/lib/src/vis/line/LineVis.module.css
- packages/lib/src/vis/matrix/MatrixVis.module.css
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/scatter/ScatterVis.module.css
- packages/lib/src/vis/shared/VisCanvas.module.css
- packages/lib/src/vis/surface/SurfaceVis.module.css
If unspecified, the defaults for a flex item are:
- `flex-grow: 0`
- `flex-shrink: 1`
- `flex-basis: auto`
Very often, what we want is `flex: 1 1 0` - i.e. for the item to grow/shrink to fill the available space regardless of its intrinsic size (so that all flex items inside a container get sized equally).
The [`flex`](https://devdocs.io/css/flex) shorthand knows this is the most common case and that people don't generally want `flex-basis: auto`, so when one or two unit-less values are specified (for `flex-grow` and `flex-shrink`) it sets `flex-basis` to `0` instead of keeping the default value of `auto`:
- `flex: 1` <=> `flex: 1 1 0`
- `flex: 1 0` <=> `flex:  1 0 0`
I used to think that this behaviour was kind of obscure and always preferred to write `flex: 1 1 0%`. After seeing that …
> Shorten `flex` shorthand properties

- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
I came across this tool, which reported a couple of errors around missing types: https://arethetypeswrong.github.io/
To fix the issues, I followed the recommendation given in this article: https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/#round-2-results
> Add missing "types" entries in package.json exports

- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/shared/src/guards.ts
- Fix https://github.com/silx-kit/vscode-h5web/issues/15
- Fix https://github.com/silx-kit/vscode-h5web/issues/30
> `[H5WasmProvider + MatrixVis]` Support (u)int64 data inside compound datasets

- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/utils.ts
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/utils.ts
I wasn't fond of `LineVis` and `HeatmapVis` being aware of some of the `DType` models—those should concern only the H5Web viewer.
> Pass `dtype` as string to visualization components

- packages/app/src/providers/h5grove/utils.ts
I've activated CodeQL analysis on the repo to try it out: https://github.com/silx-kit/h5web/settings/security_analysis
It detected an issue in a regex: https://github.com/silx-kit/h5web/security/code-scanning/1
> Fix overly permissive regex

- packages/lib/src/index.ts
- packages/lib/src/vis/heatmap/utils.ts
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/line/hooks.ts
- packages/lib/src/vis/line/utils.ts
- packages/lib/src/vis/utils.ts
When the size of an axis dataset doesn't match the size of the dimension to which it is mapped (via the NX `axes` attribute), the error message was so far reporting an incorrect value, off by 1:
This was due to `HeatmapVis` calling `getPixelEdgeValues`, which in turn was calling `getAxisValues(rawValues, pixelCount + 1);` to account for the fact that the axis values need to include the value of the outside edge of the last pixel.
I didn't try to be smart: I stopped calling `getAxisValues` from `getPixelEdgeValues` and instead duplicated/tweaked the logic appropriately. Since `getAxisValues` is now only used by `LineVis`, I moved it and its hook into dedicated files.
> [HeatmapVis] Fix min axis array length off by 1 in error message

- apps/demo/package.json
- apps/demo/src/h5wasm/H5WasmApp.tsx
- apps/demo/src/h5wasm/plugin-utils.ts
- apps/demo/src/vite-env.d.ts
- apps/demo/vite.config.js
- packages/h5wasm/README.md
- packages/h5wasm/package.json
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/utils.ts
- pnpm-lock.yaml
Thanks to the new [h5wasm-plugins](https://github.com/h5wasm/h5wasm-plugins) package (kudos @bmaranville!!), I'm able to load compression plugins on demand in `H5WasmProvider`. :tada: 
I was hoping that everything could be taken care of by `H5WasmProvider` under the hood, but since `@h5web/h5wasm` is a library, it's not that simple. The plugin files have to be loaded into Emscripten's file system as array buffers, which means they first have to be fetched lazily somehow ... and only the consumer application knows how to do that:
- perhaps the application is bundled with Vite or webpack, which means the plugins can be imported as static assets (i.e. to get their file system URLs) ` and then fetched as array buffers;
- perhaps the application doesn't use a bundler and just serves the plugin …
> Lazy-load compression filters in `H5WasmProvider`

- packages/app/README.md
> Fix outdated documentation of `H5GroveProvider`

- packages/h5wasm/package.json
- pnpm-lock.yaml
Fix #1525 - importing `h5wasm` in NextJS now properly imports h5wasm's browser bundle instead of its Node bundle. See https://github.com/usnistgov/h5wasm/releases/tag/v0.7.0 and https://github.com/usnistgov/h5wasm/pull/64 for more info.
> Upgrade h5wasm to fix NextJS issue

- apps/demo/package.json
- apps/demo/src/DemoApp.tsx
- apps/demo/src/H5GroveApp.tsx
- apps/demo/src/Home.tsx
- apps/demo/src/HsdsApp.tsx
- apps/demo/src/MockApp.tsx
- apps/demo/src/h5wasm/H5WasmApp.tsx
- apps/demo/src/h5wasm/UrlForm.tsx
- pnpm-lock.yaml
[React Router](https://reactrouter.com/) is maintained by the people who make [Remix](https://remix.run/), and they're pushing a lot of features related to data fetching and SSR into `react-router`. It's now similar to the upcoming [Tanstack Router](https://tanstack.com/router/v1) in terms of features. Those solutions are probably great to manage routing and data fetching in complex apps, especially when server-side rendering is involved. However, this is not our use case here, so I've been wanting to go back to something simpler, lighter, and focused on front-end routing.
I've come across two promising libraries: [type-route](https://type-route.zilch.dev/) and [wouter](https://github.com/molefrog/wouter/). The former is really appealing, with a focus on type safety. The latter is pretty …
> Switch to `wouter` for routing

- .github/workflows/publish-packages.yml
- CONTRIBUTING.md
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- pnpm-lock.yaml
The main purpose of this PR (which stems from #1543, which I'll rebase on this one) is to be able to pack a package into a tarball without having to worry about its version (i.e. without ending up with a packed package that has version `0.0.1`).
To do so, I add a `version` script (which runs as part of `pnpm version`) that copies the bumped version number of the monorepo into each package's `package.json`. This allows those `package.json` files to be committed with their real version numbers instead of the placeholder `0.0.1`.
As a side benefit, the _Publish packages_ CI workflow is now a lot shorter and less magical: it just builds the packages and publishes them!
> Sync package versions when bumping monorepo version to simplify CI release workflow

- packages/shared/rollup.utils.js
Rollup wants the aliases to be to absolute paths.
> Fix Rollup alias warnings when building packages

- apps/demo/src/Home.tsx
- create_h5_sample.py
- packages/app/src/index.ts
- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
- packages/app/src/providers/h5grove/h5grove-api.test.ts
- packages/app/src/providers/utils.ts
- packages/h5wasm/src/h5wasm-api.test.ts
Diffing the two files (after removing the `rawType` keys) is quite enlightening: https://www.diffchecker.com/0lEq6wKG/ (`H5GroveApi` on the left, `H5WasmApi` on the right).
I can already see some obvious bugs, some potential quick wins, and some more complicated inconsistencies.
> Test `H5GroveApi`

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/utils.ts
A bit of clean-up before I start improving the parsing of the dtypes in both `H5WasmApi` and `H5GroveApi`. Mostly, I remove a bunch of type guards that are not necessary and I move some functional utilities out of the classes. I recommend reviewing commit by commit.
> Refactor providers to notably remove unneeded type guards

- packages/h5wasm/src/__snapshots__/h5wasm-api.test.ts.snap
- packages/h5wasm/src/guards.ts
- packages/h5wasm/src/models.ts
- packages/h5wasm/src/utils.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
See test snapshot for detailed improvements. I'm also refactoring the `parseDType` function to remove the need for type guards.
> Improve dtype parsing with h5wasm

- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/utils.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
This follows https://github.com/silx-kit/h5grove/pull/85.
I've encountered an issue upgrading the server on Bosquet, so the tests still fail for now.
> Support h5grove@2.0.0 and improve dtype parsing

- apps/demo/src/H5GroveApp.tsx
- apps/demo/src/Home.module.css
- apps/demo/src/Home.tsx
- packages/app/README.md
- Following https://github.com/silx-kit/h5web/issues/1558, I add an info box to point users of the h5wasm demo to myHDF5 and the VS Code extension instead:
- Following https://github.com/silx-kit/h5web/discussions/1553, I document setting a `key` on `H5GroveProvider` and `HsdsProvider` to force a remount and clear the cache:
- While I was looking at `H5GroveProvider`'s documentation, I realised that forgetting to memoise `axiosConfig` would lead to the cache being cleared on every render of the consumer app. For the time being, I simply update the documentation to recommend memoising the object.
> Misc docs improvements following feedback

- .github/workflows/approve-snapshots.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/lint-test.yml
- .github/workflows/publish-packages.yml
- package.json
GitHub was showing a warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
We'll still get a warning for `pnpm/action-setup@v2` as this one is still on Node 16.
> Upgrade GitHub actions to v4 and bump pnpm on CI

- packages/lib/src/toolbar/controls/ExportMenu.tsx
- packages/lib/src/toolbar/controls/Selector/OptionList.tsx
- packages/lib/src/toolbar/controls/Selector/Selector.tsx
...  to work around Vitest warnings in consumer app.
This library is unmaintained and replacing it has been on my TODO list for a while. I'll get to it at some point but this seems like a good work around for now.
> Import CJS module `react-aria-menubutton` via default export

- apps/demo/package.json
- apps/demo/src/h5wasm/plugin-utils.ts
- packages/h5wasm/README.md
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/index.ts
- packages/h5wasm/src/utils.ts
- pnpm-lock.yaml
With [hwasm@0.6.10](https://github.com/usnistgov/h5wasm/releases), the Blosc2 plugin now works as expected! :tada: 
<details>
<summary>Initial PR description</summary>
Opening as draft because Blosc2 is not working as expected. The `blosc2` dataset of the test file `filters.h5` is not correctly decompressed. You can try it locally: http://localhost:5173/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Ffilters.h5
---
What's more, there's definitely something weird going on — it seems that plugins have an impact of the decompression of datasets compressed with other plugins. For instance:
1. Open `filters.h5`
2. Select `lz4` dataset => looks correctly decompressed
3. Select `blosc2` then `lz4` again => still works
4. Reload
5. Select `blosc2` first, then `lz4` => no longer works
Other …
> Support Blosc2 and Bitshuffle plugins

- .github/workflows/approve-snapshots.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/lint-test.yml
- .github/workflows/publish-packages.yml
v3 was just released: https://github.com/pnpm/action-setup/releases/tag/v3.0.0
This should get rid of the Node 16 warning in the CI entirely.
> Bump `pnpm/action-setup` so it runs on Node 20

- packages/h5wasm/src/H5WasmProvider.tsx
We received the following bug report in myHDF5:
> I have problem when loading two HDF5 files of different type into the myHDF5 page. If I look at the files one-by-one there is no problem.
When opening the first file then the second file, a bunch of errors are logged to the console that seem to suggest that the entity at the default path is not found due to an incorrect identifier. Important detail: **both files have the same `default` NeXus path**.
After some investigation, I identified that the problem comes from a stale state issue in `H5WasmProvider`: upon receiving new prop values (`fileName` and `buffer`), an effect runs in order to create a new API instance, update it in local state, and clean-up the old API instance. However, since this is done asynchronously, **the `App` gets …
> Fix subtle stale state issue in `H5WasmProvider`

- packages/app/src/App.module.css
- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/lib/src/vis/raw/RawVis.tsx
This change is in preparation for #1554.
Opaque datasets were so far fetched with h5grove as JSON, which led to back-end errors for datasets that cannot be encoded to strings (like `datetime64_scalar`).
I now fetch opaque datasets as binary and return `UInt8Array` values from `H5GroveProvider` for consistency with `H5WasmProvider`.
With h5grove@2.0.0, this change leads to 422 errors for all opaque datasets. This will be fixed with https://github.com/silx-kit/h5grove/pull/89 and a new release of h5grove. This PR therefore constitutes a breaking change.
While I'm at it, I also improve the display of `UInt8Array` values slightly in `RawVis` by simply calling `toString()` instead of `JSON.stringify()`:
> Fetch opaque datasets with h5grove as binary

- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
Following https://github.com/silx-kit/h5grove/pull/91, h5grove no longer responds with 500 errors when fetching `complex256` datasets. I've upgraded h5grove on Bosquet, so I'm now updating the test snapshots here.
Note that h5grove also no longer casts the `float32` real/imag parts of `complex64` numbers to `float64` when serializing to JSON.
We still have the issue that any `float128` number that overflows the `float64` range is cast to `inf` and serialised to JSON as `null` (cf. #641), which breaks the visualizations. The best way around this would be to fetch complex numbers as binary, but that's a problem for another day.
> Update h5grove snapshot following fix for `complex256` numbers

- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/compound/MappedCompoundMatrixVis.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/raw/RawVisContainer.tsx
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/scalar/ScalarVisContainer.tsx
- packages/app/src/vis-packs/core/scatter/MappedScatterVis.tsx
- packages/app/src/vis-packs/core/surface/MappedSurfaceVis.tsx
- packages/app/src/visualizer/Visualizer.module.css
- packages/lib/src/vis/heatmap/HeatmapVis.module.css
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/line/LineVis.module.css
- packages/lib/src/vis/line/LineVis.tsx
- packages/lib/src/vis/matrix/Grid.tsx
- packages/lib/src/vis/matrix/MatrixVis.module.css
- packages/lib/src/vis/matrix/MatrixVis.tsx
- packages/lib/src/vis/models.ts
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
- packages/lib/src/vis/rgb/RgbVis.tsx
- packages/lib/src/vis/scalar/ScalarVis.module.css
- packages/lib/src/vis/scalar/ScalarVis.tsx
- packages/lib/src/vis/scatter/ScatterVis.module.css
- packages/lib/src/vis/scatter/ScatterVis.tsx
- packages/lib/src/vis/surface/SurfaceMesh.tsx
- packages/lib/src/vis/surface/SurfaceVis.module.css
- packages/lib/src/vis/surface/SurfaceVis.tsx
Specifying `grid-area: vis` in the visualizations did introduce a regression in the end. Turns out that if a [grid area identifier](https://devdocs.io/css/grid-area#custom-ident) is not defined in the parent grid, the cell ends up on a new row/column for reasons that I [don't quite clearly understand](https://stackoverflow.com/a/57750033/758806)... Since we wrap all our stories with `display: grid` in Storybook, the high-level visualization stories were all messed up.
So I went ahead with the plan I had to pass the `grid-area: vis` style from `@h5web/app` down to the visualizations in `@h5web/lib` via a custom `className` prop. I've also added a `style` prop to all the visualizations.
> Fix `grid-area` regression

- CONTRIBUTING.md
- apps/demo/package.json
- apps/demo/src/Home.module.css
- apps/demo/src/h5wasm/H5WasmApp.module.css
- apps/demo/src/utils.module.css
- apps/demo/vite.config.js
- packages/lib/src/toolbar/MeasuredControl.module.css
- packages/lib/src/toolbar/MeasuredControl.tsx
- packages/lib/src/toolbar/OverflowMenu.module.css
- packages/lib/src/toolbar/OverflowMenu.tsx
- packages/lib/src/toolbar/Toolbar.module.css
- packages/lib/src/toolbar/controls/DomainWidget/BoundEditor.module.css
- packages/lib/src/toolbar/controls/DomainWidget/BoundEditor.tsx
- packages/lib/src/toolbar/controls/DomainWidget/DomainWidget.module.css
- packages/lib/src/toolbar/controls/InteractionHelp.module.css
- packages/lib/src/toolbar/controls/InteractionHelp.tsx
- packages/lib/src/toolbar/controls/ScaleSelector/ScaleOption.module.css
- packages/lib/src/toolbar/controls/ScaleSelector/ScaleOption.tsx
- packages/lib/src/toolbar/controls/ScaleSelector/ScaleSelector.module.css
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/toolbar/controls/ToggleGroup.module.css
- packages/lib/src/toolbar/floating/ResetZoomButton.module.css
- packages/lib/src/toolbar/utils.module.css
- packages/lib/src/vis/scatter/ScatterVis.module.css
- pnpm-lock.yaml
Vite has a [new plugin](https://github.com/privatenumber/vite-css-modules) that fixes composition of CSS Modules by treating them as JS modules. It is planned to be integrated into Vite core but it may take a while.
There's one case that is not "fixed" by the plugin, which is when composing from a module that is itself imported from a React component. It's all explained here: https://github.com/privatenumber/vite-css-modules/issues/7. To address this, I decided to refactor the code to never compose from a module that is also imported. I've explained and documented this in the `CONTRIBUTING` guide.
The plugin, in addition to the refactoring above, allow us to remove all of our `!important` workarounds and bring much needed explanations and reassurance that there is indeed a way to use CSS …
> Fix style ordering issues caused by composing from imported CSS modules

- packages/app/package.json
- packages/app/vite.config.js
- packages/lib/package.json
- packages/lib/vite.config.js
- pnpm-lock.yaml
Fix #1598 
So... fun story, I forgot to add the `vite-css-modules` plugin to the Vite configs of `@h5web/app` and `@h5web/lib`. :sweat_smile:
> Install `vite-css-modules` plugin in lib/app packages

- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
- Images in _Raw_ vis were being shrunk to a size of (0,0) in VS Code. I had to add [a little workaround](https://github.com/silx-kit/vscode-h5web/pull/38/files#diff-e8229257c26c02255a32a87e829e98b608a3114b349e59d4958e8ba456a438e7).
- I also noticed that the root container for raw images was not receiving the `grid-area: vis` style.
Neither issue prevented the release of a new version of the VS Code extension, but at least it will be cleaner in the next.
> Fix styling of raw JPEG/PNG images in some contexts

- apps/demo/src/h5wasm/H5WasmApp.tsx
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/h5wasm-api.ts
- packages/h5wasm/src/index.ts
- packages/h5wasm/src/local/H5WasmLocalFileProvider.tsx
- packages/h5wasm/src/local/h5wasm-local-file-api.ts
- packages/h5wasm/src/local/worker.ts
- packages/h5wasm/src/local/worker.utils.ts
- packages/h5wasm/src/models.ts
- packages/h5wasm/src/utils.ts
- packages/shared/src/guards.ts
Adding support for:
- reading compressed datasets;
- exporting datasets (to JSON in _Raw_ vis by default, and via consumer-provided `getExportURL` prop);
- searching through entities.
I'm also making sure that any typed array dataset values are "transferred" between the worker thread and the main thread rather than copied. Same with the buffers of the compression plugin files (but the other way around).
> Improve local file provider

- packages/app/src/metadata-viewer/utils.ts
Addresses the first part of #1612.
Before, we would show only "ASCII string" or "UTF-8 string":
> Make variable-length string types explicit in metadata viewer

- apps/storybook/src/Utilities.mdx
- packages/lib/src/index.ts
- packages/lib/src/vis/line/errorBarsGeometry.ts
- packages/lib/src/vis/line/errorCapsGeometry.ts
- packages/lib/src/vis/line/glyphsGeometry.ts
- packages/lib/src/vis/line/lineGeometry.ts
- packages/lib/src/vis/scatter/scatterPointsGeometry.ts
- packages/lib/src/vis/shared/R3FCanvas.tsx
- packages/lib/src/vis/utils.ts
Fix #1626
I went with `{ near: 0, far: 1000, position: [0, 0, 1000] }` to give a visible `z` range of `[0 1000]` as explained in https://github.com/silx-kit/h5web/issues/1626#issuecomment-2082921944.
To make the relation between the camera frustrum/position settings and the visible `z` range, I've defined three constants and exported/documented them in `@h5web/lib`.
> Tweak camera frustrum to provide wider `z` range

- packages/app/src/vis-packs/core/configs.ts
- packages/app/src/vis-packs/core/raw/RawToolbar.tsx
- packages/app/src/vis-packs/core/raw/RawVisContainer.tsx
- packages/app/src/vis-packs/core/raw/config.tsx
- packages/app/src/vis-packs/core/visualizations.ts
- packages/lib/src/index.ts
- packages/lib/src/vis/raw/RawImageVis.module.css
- packages/lib/src/vis/raw/RawImageVis.tsx
- packages/lib/src/vis/raw/RawVis.module.css
- packages/lib/src/vis/raw/RawVis.tsx
- packages/lib/src/vis/raw/utils.ts
Fix #1630
I add a toggle button to the _Raw_ visualization toolbar and a (persisted) config store to hold the state. The button is toggled on by default. When the dataset isn't a binary image, the button is disabled.
I chose to create a separate visualization component called `RawImageVis` to deal specifically with JPEG/PNG images; it's the `RawVisContainer` that now decides which visualization component to use.
> Add toggle to fit raw image (on by default)

- packages/app/src/__tests__/DimensionMapper.test.tsx
- packages/app/src/dimension-mapper/hooks.ts
Baby step to address #1578
1. We first added debouncing on the dimension mapping state in #888 to address #879.
2. In #920, we then realised that this also debounced the axis mappers (the D0/D1/.../Dn button groups), so we opened #975 with the goal of moving the debounce to the sliders.
3. Turns out that in that PR, we added debouncing to the sliders without actually removing it on the dimension mapping state... So we ended up with two debounces, for a total of 350 ms.
In this PR, I therefore remove the debounce on the dimension mapping state, thus saving 100ms both when slicing and changing axis dimensions.
> Remove debounce on dimension mapping state to reduce lag

- apps/demo/package.json
- apps/demo/vite.config.js
- package.json
- packages/app/package.json
- packages/app/vite.config.js
- packages/h5wasm/package.json
- packages/h5wasm/vite.config.js
- packages/lib/package.json
- packages/lib/vite.config.js
- pnpm-lock.yaml
Replace [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react), which is based on [Babel](https://babeljs.io/), with [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc), which is based a [SWC](https://swc.rs/).
SWC is a Rust-based compiler — some empirical tests seem to confirm that it is indeed faster, shaving a few seconds off `pnpm packages`, and half a second off `pnpm build`. Fast refresh does seem a lot faster as well (even though it was already fast enough).
> Switch to `@vitejs/plugin-react-swc`

- apps/demo/src/DemoApp.tsx
- eslint.shared.cjs
The H5Wasm demo bundle weighs almost 10 MB, so it seems a shame to load that every time, even for users who just want to look at the mock and H5Grove demos.
> Lazy-load H5Wasm demo

- netlify.toml
Two HTTP security headers for the demo that can't hurt:
- [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
- [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)
> Prevent iframe embedding and MIME type sniffing

- packages/app/.env.test
- packages/app/src/providers/h5grove/h5grove-api.test.ts
- packages/app/src/test-utils.tsx
- packages/app/vite.config.js
- packages/h5wasm/.env.test
- packages/h5wasm/src/h5wasm-api.test.ts
- packages/h5wasm/vite.config.js
- I was following an issue on the Vitest repo and finally saw a way to move test configuration to environment variables.
- While I'm at it, I add two env vars to be able to skip running the h5grove/h5wasm API tests (they always fail on my laptop because of the lack of `float128` support)
- And I add a check to make sure that the h5grove support server is running before the test starts (to get a clearer error message).
> Improve h5grove/h5wasm API testing set-up

- packages/app/README.md
- packages/app/src/dimension-mapper/SlicingSlider.tsx
- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/hsds/HsdsProvider.tsx
- packages/app/src/providers/mock/MockProvider.tsx
- packages/app/src/providers/models.ts
- packages/h5wasm/README.md
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/local/H5WasmLocalFileProvider.tsx
Addresses #1578 (not closing for now until we can confirm it's sufficient), and supersedes #1583 and #1635.
Since the debounce behaviour depends directly on the kind of provider used, I ended up injecting a `viewerConfig` object into the `DataContext`. This gives a way for providers to configure the viewer to their liking, and for provider consumers to override the configuration as they see fit through a `viewerConfig` prop.
For now `viewerConfig` has a single property: `slicingTiming` to configure the debounce delay on the slicing sliders. I chose a generic name (instead of `debounceDelay`) in case we need to add a `slicingStrategy` property in the future to allow throttling instead of debouncing.
Some initial testing seems to show that a `slicingTiming` of 20ms for h5wasm providers …
> Reduce delay when slicing with h5wasm through viewer config

- packages/app/README.md
- packages/app/src/dimension-mapper/SlicingSlider.tsx
- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/hsds/HsdsProvider.tsx
- packages/app/src/providers/mock/MockProvider.tsx
- packages/app/src/providers/models.ts
- packages/h5wasm/README.md
- packages/h5wasm/src/H5WasmProvider.tsx
- packages/h5wasm/src/local/H5WasmLocalFileProvider.tsx
Hmm on second thoughts...
I was looking at #1572 and more specifically at the _Autoscale_ feature of the _Line_ visualization. This feature is designed to control how the domain of the line visualization is computed: when toggled on, the domain is computed from the current slice only; when toggled off, the domain is computed from the entire dataset.
Turns out in terms of data fetching, it is very similar to the prefetch button solution I tried in #1635: the difference is that when toggled off, it triggers a fetch/read of the entire dataset and not just one dimension. This actually simplifies a lot of things, since fetching the entire dataset triggers the suspense fallback (which means that the fetch can be cancelled if need be), and we don't have to rely on `react-suspense-fetch` to know …
> Revert "Reduce delay when slicing with h5wasm through viewer config"

- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/hsds/utils.test.ts
- packages/app/src/providers/hsds/utils.ts
- packages/app/src/providers/mock/mock-file.ts
- packages/h5wasm/src/utils.ts
- packages/shared/package.json
- packages/shared/src/h5t.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
[h5wasm@0.7.5](https://github.com/usnistgov/h5wasm/releases) has just been released with the new `strpad` metadata property to address #1621.
Since this is another case where we need to map an [H5T enum](https://docs.hdfgroup.org/hdf5/v1_14/_h5_tpublic_8h.html#title3) number to a more readable string, and since both h5grove and h5wasm expose a few of those raw enum values now (dtype class, charset, sign, order), I thought I'd first normalise things a bit...
1. I create a `h5t.ts` file in the shared package to hold the H5T enums and their mappings to readable strings. 
The enums and their keys are named as closely to the HDF5 spec as possible (though I don't specify keys for errors (`-1`) and reserved values — I'll explain why in a comment.)
2. I refactor the dtype factories …
> Normalise H5T enums and use them to initialise types

- apps/storybook/package.json
- apps/storybook/src/TiledHeatmapMesh/checkerboard-api.ts
- apps/storybook/src/TiledHeatmapMesh/mandlebrot-api.ts
- packages/app/package.json
- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/models.ts
- packages/app/vite.config.js
- packages/h5wasm/vite.config.js
- packages/shared/package.json
- packages/shared/src/react-suspense-fetch.ts
- pnpm-lock.yaml
Since [`react-suspense-fetch`](https://github.com/dai-shi/react-suspense-fetch) is no longer maintained but provides a good abstraction for our data providers (probably even after the next [React 19](https://react.dev/reference/react/use) upgrade), and since we would really benefit from being able to introspect the internal cache of the `valueStore` to address #1578 properly once and for all, I bring in the library's source code into our codebase.
Of course, I also tweak it to my liking a bit:
- I swap the `Input` and `Result` generics (`<Result, Input>` just felt unnecessarily confusing).
- I remove the restriction to always have to call `prefetch` before `get`.
- I take advantage of the new `preset` method, which was added in a recent version we hadn't upgraded to because of the …
> Bring in `react-suspense-fetch` into codebase

- packages/app/src/App.tsx
- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/models.ts
- packages/app/src/vis-packs/ValueLoader.tsx
- packages/app/src/vis-packs/VisBoundary.tsx
- packages/app/src/visualizer/VisManager.tsx
- packages/shared/src/react-suspense-fetch.ts
We used to set up our own axios `CancelToken` to cancel value requests but it's [deprecated](https://github.com/axios/axios?tab=readme-ov-file#canceltoken-deprecated) in favour of the web platform's [AbortController](https://github.com/axios/axios?tab=readme-ov-file#abortcontroller).
Moreover, in newer versions, react-suspense-fetch creates its own `AbortController` for each request and passes it on to the store's fetch function. This allows aborting requests (and then evicting them) through the stores instead of having to keep track of ongoing and cancelled requests ourselves in `DataProviderApi`.
The challenge was that react-suspense-fetch was not providing a way to tell which requests have been aborted in order to evict them from the cache when after the error boundary appears. So I …
> Abort requests with signal via fetch store

- apps/storybook/src/Annotation.stories.tsx
- apps/storybook/src/SelectionTool.stories.tsx
- packages/app/src/VisConfigProvider.tsx
- packages/app/src/metadata-viewer/AttributeLink.tsx
- packages/app/src/metadata-viewer/AttributesInfo.tsx
- packages/app/src/metadata-viewer/FiltersInfo.tsx
- packages/app/src/vis-packs/core/ValueFetcher.tsx
- packages/app/src/vis-packs/nexus/NxValuesFetcher.tsx
- packages/lib/src/interactions/SelectionTool.tsx
- packages/lib/src/vis/matrix/HeaderCells.tsx
- packages/lib/src/vis/rgb/utils.ts
- packages/lib/src/vis/shared/DataToHtml.tsx
I found an old stash from a past attempt at upgrading TypeScript from 5.0 to 5.2. Turns out I missed this refactoring opportunity when I looked at it again in #1636.
I had also taken some notes of interesting changes in 5.1 and 5.2 in case this is of interest:
- [Easier Implicit Returns for undefined-Returning Functions](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#easier-implicit-returns-for-undefined-returning-functions): a `return` statement is still required for all code paths, and it feels weird having `return;` at the end of a function; I much prefer the explicitness of `return undefined;`. Might help simplify other cases that I'm not seeing. 🤷‍♀️
- [Decoupled Type-Checking Between JSX Elements and JSX Tag …
> Remove useless fragments

- packages/app/src/dimension-mapper/AxisMapper.tsx
- packages/app/src/dimension-mapper/DimensionMapper.tsx
- packages/app/src/dimension-mapper/SlicingSlider.tsx
- packages/app/src/dimension-mapper/utils.ts
- packages/app/src/vis-packs/core/complex/ComplexLineVisContainer.tsx
- packages/app/src/vis-packs/core/complex/ComplexVisContainer.tsx
- packages/app/src/vis-packs/core/compound/CompoundMatrixVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/core/rgb/RgbVisContainer.tsx
- packages/app/src/vis-packs/core/surface/SurfaceVisContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxRgbContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/shared/src/react-suspense-fetch.ts
Finally something that truly feels promising for #1578 :partying_face: 
Here's the gist:
- Add a way to check if a slice is already cached (or being fetched) in the store.
- Replace `useDebouncedCallback` with custom `useDynamicDebouncedCallback` in `SlicingSlider` that can adjust the debouncing delay on every call.
- If the user slides to a slice that is already in the fetch cache, set the debounce delay to 20ms; if it's not, set it to 250ms.
How to test this in practice:
1. Move the slider thumb one value at a time relatively slowly to request multiple slices
2. You can now "replay" the fetched slices very quickly
Why this is awesome:
- No need to fetch an entire dataset or dimension to start seeing benefits
- Benefits all providers and visualizations the same way
- No arbitrary …
> Decrease debounce delay dynamically on slices that are already cached

- packages/app/README.md
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/hsds/HsdsProvider.tsx
- packages/h5wasm/README.md
- packages/h5wasm/src/H5WasmLocalFileProvider.tsx
Addresses https://github.com/silx-kit/h5web/discussions/1553#discussioncomment-9787236
I was wrong about `key` not resetting the state of children components, so I'm adding a `resetKeys` array prop to three providers: `H5GroveProvider`, `HsdsProvider` and `H5WasmLocalFileProvider` to allow resetting the fetch cache manually. This prop is inspired from react-error-boundary.
I've tested and it works great: the suspense fallbacks in the explorer and in the visualizer are triggered again as expected. This even works with local files, which will benefit the VS Code extension.
> Add way to reset fetch cache of relevant providers

- apps/storybook/.eslintignore
- apps/storybook/.storybook/main.ts
- apps/storybook/tsconfig.json
- tsconfig.json
Whenever I was opening a file at the root of the repo, like `cypress.config.ts`, VS Code would notify me to properly configure excluded files in `tsconfig.json`.
I used [this technique](https://github.com/microsoft/TypeScript/issues/53492#issuecomment-1876072922) to find out which files were included by the root `tsconfig.json`. Since we didn't use to specify `include` or `exclude`, the defaults applied as expected, which meant that `node_modules` folders were properly excluded but not build folders.
Keeping with our approach of using `include` over `exclude` to specify files to type-check, I add an `include` array in the root `tsconfig.json` that includes all the files that are not included by other `tsconfig.json` files:
- `*` = root TS/JS files
- `apps/*/*`, `packages/*/*` = files at …
> Fix minor linting and type-checking configuration issues

- apps/storybook/src/Utilities.mdx
- packages/lib/src/vis/hooks.ts
- packages/lib/src/vis/line/ErrorBars.tsx
- packages/lib/src/vis/line/Glyphs.tsx
- packages/lib/src/vis/line/Line.tsx
- packages/lib/src/vis/scatter/ScatterPoints.tsx
Introducing a **breaking change** in the signature of the `useGeometry` hook to fix #1684
The problem came from passing `false` or `undefined` as the value of the `params` parameter in order to skip updating the geometry (e.g. when the R3F object is hidden). I change the signature of the hook to decouple this feature from the `params` parameter: the hook now accepts a `config` object as fourth argument (which also makes the `isInteractive` boolean more explicit).
> Fix React warning with `useGeometry` deps array

- package.json
- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/app/src/vis-packs/core/scalar/utils.ts
- packages/h5wasm/package.json
- packages/h5wasm/src/__snapshots__/h5wasm-api.test.ts.snap
- packages/h5wasm/src/h5wasm-api.test.ts
- packages/h5wasm/src/utils.ts
- packages/h5wasm/src/worker-utils.ts
- packages/lib/src/vis/raw/RawVis.tsx
- packages/shared/src/guards.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/vis-utils.ts
- pnpm-lock.yaml
- support/sample/create_h5_sample.py
Two changes in [h5wasm v0.7.6](https://github.com/usnistgov/h5wasm/releases/tag/v0.7.6):
This brings h5wasm in line with h5grove. The only difference is that, for numeric vlen datasets, h5wasm is able to return an array of vlen typed arrays (`TypedArray[]`), whereas h5grove is forced to return an array of plain arrays (`number[][]`) -- this doesn't make any difference, in the viewer though.
> See https://github.com/usnistgov/h5wasm/issues/78 and https://github.com/usnistgov/h5wasm/pull/77
This removes the unnecessary `number->boolean->number` conversion for the line and heatmap vis.
Since h5grove and HSDS still return booleans for now, I decided to allow for both throughout (`Primitive<BooleanType` => `number | boolean`). As a result:
- If `MappedLineVis` and `MappedHeatmapVis` receive …
> Upgrade h5wasm and improve boolean and vlen support

- packages/app/src/__tests__/Explorer.test.tsx
- packages/app/src/__tests__/NexusPack.test.tsx
- packages/app/src/__tests__/Visualizer.test.tsx
- packages/app/src/providers/DataProvider.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/mock/utils.ts
- packages/app/src/vis-packs/ValueLoader.tsx
- packages/shared/package.json
- packages/shared/src/react-suspense-fetch.ts
- pnpm-lock.yaml
This replaces the pub-sub pattern I had implemented in `DataProviderApi`, and considerably simplifies subscribing to the progress state in `ValueLoader`.
Basically, every fetch store now initialises a zustand store to track progress. Each "fetch input" (e.g. dataset+selection for `valuesStore`) is associated with a progress percentage in the zustand store, and the store can be subscribed to with zustand's `useStore` hook.
> Use zustand store inside suspense fetch store to track progress

- packages/app/src/ErrorFallback.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/utils.ts
In this PR, I'm finally removing the `cancellableFetchValue` method from the `DataProviderApi` base class. This method made little sense ever since the arrival of h5wasm, which doesn't require making HTTP requests at all.
This should get rid of `axios` from consumer bundles that use `H5WasmBufferProvider` or `H5WasmLocalFileProvider`. It also means that if we expose `DataProviderApi` in the future, consumers may be able to develop their own network-based provider without having to use `axios` as the fetching library.
So it's now up to `H5GroveProvider` and `HsdsProvider` to initialise and use their own axios client. I had to refactor axios error handling a bit to make this a bit more palatable, but  overall I find the result less convoluted than before. I especially like that the …
> Remove axios from `DataProviderApi` base class and refactor axios error handling

- apps/storybook/src/MatrixVis.stories.tsx
- packages/app/src/vis-packs/core/compound/MappedCompoundVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/lib/src/vis/matrix/MatrixVis.tsx
- packages/shared/src/guards.ts
I've been looking into making the types of `getFormatter` in `MappedMatrixVis` more strict. I'd like to ensure that, for instance, when we have a numeric array:
- the formatter is typed as `(val: number) => string` (instead of `(val: number | string | ...) => string`);
- we can't pass a string formatter with a numeric array.
Unfortunately, I keep hitting roadblocks. While investigating, I found an interesting refactoring of `MatrixVis` that simplifies a bunch of things and may remove at least one of those roadblocks...
The gist is that I remove the `dataArray` prop and let the consumer retrieve the value using the row and column index. This means we no longer have to worry about the formatter `val` parameter matching the type of the values in the array, whether it be when using …
> Simplify `MatrixVis` API

- packages/app/src/vis-packs/core/scalar/ScalarVisContainer.tsx
- packages/lib/src/vis/scalar/ScalarVis.tsx
Following #1702, I now pass a formatted value to `ScalarVis` to remove the risk of passing a formatter that doesn't match the type of the value. An alternative would have been to add a generic to the `Props` interface of `ScalarVis` (which would have probably worked, unlike when I tried it with `MatrixVis` because of ndarray), but I honestly don't see the benefit of calling `formatter` inside `ScalarVis` anymore. It's a misdirection that also unnecessarily restricts the types of values that can be formatted and displayed.
**Breaking change** `[ScalarVis]` Remove prop `formatter` and change type of prop `value` to accept only strings. Typical refactoring:
```tsx
// BEFORE
<ScalarVis value={true} formatter={(val /* number | string | ... */ => (val as boolean).toString()} />
<ScalarVis …
```
> Pass formatted value to `ScalarVis`

- packages/app/src/vis-packs/core/compound/MappedCompoundVis.tsx
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
`Primitive<PrintableCompoundType>` resolves to `(string | number | boolean | H5WebComplex)[]` but we weren't actually asserting for this fully in `assertPrimitiveValue`. I'm correcting this and also generalising things a bit:
- Resolve `Primitive<CompoundType>` to `unknown[]` instead of `unknown` (to match the existing array assertion in `assertPrimitiveValue`)
- Change the generic of `CompoundType` to extend `DType` instead of `Record<string, DType>` to simplify usage (notably when inferring the generic in `Primitive`) and to remove the need for `PrintableCompoundType` (now replaced with just `CompoundType<PrintableType>`)
> Assert compound values

- packages/app/src/providers/h5grove/models.ts
- packages/app/src/providers/h5grove/utils.ts
[h5grove@2.3.0](https://github.com/silx-kit/h5grove/releases/tag/v2.3.0) now returns the metadata of committed datatypes, so we just need to parse it.
With this PR, committed datatypes are now fully supported in all providers, which fixes #1699.
> Parse metadata of committed datatypes with h5grove

- packages/lib/src/toolbar/controls/CellWidthInput.module.css
- packages/lib/src/toolbar/controls/Selector/Selector.module.css
- packages/lib/src/vis/matrix/MatrixVis.module.css
This fixes two jittering issues when resizing the explorer sidebar:
- Some control labels would sometimes wrap onto two lines. I noticed this with the _Cell width_ control on the _Matrix_ vis, but the same could most likely happen with `Selector` labels. I now prevent wrapping in both cases.
- The _Matrix_ visualization would overflow and cause sidebars to appear and disappear quickly.
| BEFORE | AFTER |
| --- | --- |
| ![matrix-resize-jitter](https://github.com/user-attachments/assets/89b5b1bc-a89d-45cb-9ab3-e89b156efb9b) | ![matrix-resize-jitter-fixed](https://github.com/user-attachments/assets/a9dfa596-9c28-4a1b-855f-b8557a9a00d7) |
> Fix jitter when resizing explorer sidebar on Matrix vis

- packages/shared/src/mock-utils.ts
`IMAGE_VERSION` is actually not checked/relevant
The only thing we check is that `CLASS` is `IMAGE` and that if there is a `IMAGE_SUBCLASS` attribute, it is equal to `IMAGE_TRUECOLOR`.
> Change image mock dataset attr

- .github/workflows/lint-test.yml
- apps/demo/tsconfig.json
- apps/storybook/tsconfig.json
- cypress/tsconfig.json
- packages/app/tsconfig.build.json
- packages/app/tsconfig.json
- packages/h5wasm/tsconfig.build.json
- packages/h5wasm/tsconfig.json
- packages/lib/tsconfig.build.json
- packages/lib/tsconfig.json
- packages/shared/tsconfig.build.json
- packages/shared/tsconfig.json
- tsconfig.json
The migration from the Galex ESLint config to our own config is pretty much ready, but I'm going to make a couple of preparatory PRs to ease the review...
This is the first one to:
- Pin Poetry in the CI (there are breaking changes in [v2](https://github.com/python-poetry/poetry/releases))
- Prepare each project to lint its own JS/TS setup files (e.g. `packages/shared/rollup.utils`) instead of doing this from the root of the monorepo.
> Let each project lint its own setup files

- packages/lib/src/vis/utils.ts
As explained in https://github.com/silx-kit/h5web/pull/1726#discussion_r1916192752, the log ticks formatter selection logic doesn't work when the domain array is in the wrong order (`[max, min]` instead of `[min, max]`). Ideally this shouldn't happen, and I'll investigate the idea of asserting `min < max` in `VisCanvas`.
Regardless, I'm not happy with the domain-flipping logic `const [min, max] = domain[0] > 0 ? domain : [-domain[1], -domain[0]];`. In this PR, I refactor it so it's more robust and explain why we need it at all in a comment. The new logic works with `[max, min]`, because why not:
| BEFORE | AFTER |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/72ecb8cd-ab71-46c0-a978-cfd08c185f4e) | ![image](https://github.com/user-attachments/assets/f2bb3352-a3a6-42fa …
> Make log ticks formatter selection logic more robust

- packages/app/src/metadata-viewer/utils.ts
- packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap
- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/hsds/utils.test.ts
- packages/app/src/providers/hsds/utils.ts
- packages/app/src/providers/mock/mock-file.ts
- packages/app/src/providers/utils.ts
- packages/app/src/vis-packs/core/utils.ts
- packages/app/src/vis-packs/core/visualizations.test.ts
- packages/h5wasm/src/__snapshots__/h5wasm-api.test.ts.snap
- packages/h5wasm/src/utils.ts
- packages/h5wasm/src/worker-utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
- packages/shared/src/mock-utils.ts
The goal is to split `NumericType` into two dtypes: `IntegerType` and `FloatType`, and to replace `DTypeClass.Unsigned` with a `signed` boolean in `IntegerType`.
I had first planned to introduce this change as part of adding support for big integers (cf. https://github.com/silx-kit/h5web/issues/1679#issuecomment-2333937430). At the time I wanted to introduce a new `DType` called `BigIntegerType` and it didn't really make sense to have this dtype together with `NumericType`... I'm now going back on this solution for reasons I'll explain soon, but I find that the `NumericType` refactoring still makes sense. `IntegerType`/`FloatType` brings us closer to the HDF5 types, and representing the sign as a boolean avoids relying on the `DTypeClass` enum's value too much in the metadata viewer (i.e. …
> Merge signed and unsigned integer types

- eslint.config.base.js
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/mock-values.ts
- packages/shared/src/vis-utils.ts
As a reminder, providers are allowed to return boolean datasets as `boolean[]` (HSDS only) or as `number[]` (h5wasm  #1692 and h5grove  #1709).
The goal here is for `ArrayValue<BooleanType>` to evaluate to `number[] | boolean[]` instead of `(number | boolean)[]` (which was quite wrong). This doesn't change much but it will matter more when introducing `bigint`...
While I'm at it, I give the `Primitive` and `ArrayValue` generics default values, and I use `ArrayValue` in a bunch of places to replace `unknown[] | TypedArray`. This will save me later from adding `BigInt64Array` and `BigUint64Array` to that type everywhere...
> Make `ArrayValue` type distributive

- packages/app/src/providers/mock/mock-file.ts
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/nexus/NxSignalPicker.tsx
- packages/app/src/vis-packs/nexus/NxValuesFetcher.tsx
- packages/app/src/vis-packs/nexus/guards.ts
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/app/src/vis-packs/nexus/models.ts
- packages/shared/src/mock-values.ts
`assertNumericLikeNxData` was asserting for `NxData<NumericType>` instead of `NxData<NumericLikeType>` ... but was correctly calling `assertNumericLikeType` internally! So `MappedLineVis` thought it could only receive numeric (nd)arrays (`number[] | TypedArray`) when in fact, at runtime, it could receive `boolean[]`.
No errors were thrown at runtime because JS automatically coerces booleans to numbers in all mathematical operations (e.g. `Math.min(false, 2) => 0`). This typing bug would have been more problematic with `bigint[]`, though.
I say "Fix support", because the fix still has invisible runtime implications: I now convert boolean auxiliary arrays to number arrays in `MappedLineVis` with a new hook called `useToNumArrays`, which avoids type coercion further down the line (e.g. in …
> Fix support for enum/bool auxiliary signals in NX Line visualization

- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/mock/utils.ts
- packages/app/src/vis-packs/core/complex/MappedComplexLineVis.tsx
- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/compound/MappedCompoundVis.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/scatter/MappedScatterVis.tsx
- packages/app/src/vis-packs/core/surface/MappedSurfaceVis.tsx
- packages/app/src/vis-packs/nexus/models.ts
- packages/app/src/vis-packs/nexus/utils.ts
- packages/shared/src/guards.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/vis-models.ts
- packages/shared/src/vis-utils.ts
From https://github.com/silx-kit/h5web/pull/1738#discussion_r1924836346
The `value`, `auxValues`, `errors`, `auxErrors` and `axisValues` props of mapped components (`MappedLineVis`, `MappedRgbVis`, etc.) were typed in a few different, inconsistent ways:
- with `NumArray` (= `number[] | TypedArray`)
- with `ArrayValue<DType>` (where `DType` matches the one of the `dataset` prop — e.g. `Dataset<ArrayShape, NumericType>` => `ArrayValue<NumericType>`, but it works with any other dtype or dtype union like `NumericLikeType`)
- with `Value<Props['dataset']>` to avoid duplicating the dtype.
While the third way is the most robust and DRY, it's not the most readable since it adds an extra level of misdirection. And while the first way is the most explicit, it becomes less readable and/or more …
> Normalise prop types of mapped components with `ArrayValue`

- apps/storybook/src/HeatmapVisDisplay.stories.tsx
- packages/app/src/metadata-viewer/utils.ts
- packages/app/src/vis-packs/core/complex/MappedComplexLineVis.tsx
- packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/utils.ts
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/scalar/utils.ts
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/models.ts
- packages/shared/src/guards.ts
- packages/shared/src/mock-utils.ts
- packages/shared/src/mock-values.ts
- packages/shared/src/vis-models.ts
- packages/shared/src/vis-utils.ts
A final mixed bag of changes ahead of supporting bigints (cf. list of commits).
> Assert values of enum datasets and other tweaks

- CONTRIBUTING.md
- apps/demo/package.json
- apps/storybook/package.json
- package.json
- packages/app/package.json
- packages/h5wasm/package.json
- packages/lib/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Upgrade Node to v22, which is the current LTS version, and fix #1717 by mentioning the prerequisite of installing Node and pnpm in the _Getting started_ section of the CONTRIBUTING guide.
> Upgrade Node to 22

- packages/app/src/providers/h5grove/utils.test.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/hsds/models.ts
- packages/app/src/providers/hsds/utils.test.ts
- packages/app/src/providers/hsds/utils.ts
- packages/app/src/providers/mock/mock-file.ts
- packages/h5wasm/src/worker-utils.ts
- packages/shared/src/hdf5-models.ts
- packages/shared/src/hdf5-utils.ts
Following the split of `NumericType` into `IntegerType` and `FloatType` in #1736, I'm doing the same with  `ArrayType`, which was covering two [`H5T_class_t`](https://support.hdfgroup.org/documentation/hdf5/latest/_h5_tpublic_8h.html#a071841985f647f69516dbe77d93167f2) values: `H5T_ARRAY` and `H5T_VLEN`.
Turns out this was making things more complicated than they needed to be... So now we have two separate dtypes: `VLenType` and `ArrayType`.
Note that nothing changes in the UI or in the provider snapshots, since the enum value `DTypeClass.VLen` doesn't change: it remains "Array (variable-length)".
> Split `VLenType` out of `ArrayType`

- packages/lib/src/vis/line/DataCurve.tsx
- packages/lib/src/vis/line/utils.ts
Fix #1720
`[DataCurve]` Add props `onLineClick`, `onLineEnter` and `onLineLeave`
The three new line event handlers all receive the `index` of the line segment that was interacted with, just like the three existing data point event handlers.
I didn't change the [_Interactive_ story](https://h5web-docs.panosc.eu/?path=/story/building-blocks-datacurve--interactive) since the actions add-on already logs the new events by default:
> Add line event handlers to `DataCurve`

- apps/storybook/src/VisCanvas.stories.tsx
- packages/lib/src/vis/models.ts
- packages/lib/src/vis/shared/Axis.tsx
Fix #1701
`VisCanvas`' internal tick formatter is meant as a good default:
- It uses D3 with format [`.3~g`](https://d3js.org/d3-format) to strongly limit the number of characters and prevent tick labels from overflowing.
- It tells D3 to force exponent notation for numbers such as `0.00000123` (for which D3 doesn't respect the precision in `g` mode).
- It skips rendering some tick labels in log scale when space is limited.
Unfortunately, this is far from perfect.
Finding the perfect tick formatting algorithm is just not possible, so the idea with this PR is to allow consumers of `VisCanvas` to implement one that works for their use case.
I think this opens the door to a lot of use cases. For instance, in the new `VisCanvas` story that demonstrates the use of `formatTick`, I pass a …
> Allow passing custom axis tick formatters to `VisCanvas`

- packages/app/src/index.ts
- packages/shared/src/guards.ts
Consumers using the provider API would benefit from having access to all our models, type guards and assertions. Example inspired from the [Data Portal project](https://gitlab.esrf.fr/icat/data-portal/-/blob/main/packages/h5/src/h5/H5ImageHeatmapViewer.tsx#L54-62):
```ts
const { entitiesStore, valuesStore } = useDataContext();
const entity = entitiesStore.get('/my-dataset'); // ProvidedEntity
assertDataset(entity); // Dataset
assertNonNullShape(entity) // Dataset<ScalarShape | ArrayShape>
// Now it's safe to get the value
const data = valuesStore.get({ dataset: entity }); // unknown
// I can keep going...
assertArrayShape(entity); // Dataset<ArrayShape>
const { shape } = entity; // number[] with at least one element
assertFloatType(entity); // Dataset<ArrayShape, FloatType> …
```
> Export models, type guards and assertions

- packages/app/README.md
- packages/app/src/dimension-mapper/hooks.ts
- packages/app/src/explorer/EntityList.tsx
- packages/app/src/hooks.ts
- packages/app/src/index.ts
- packages/app/src/metadata-viewer/MetadataViewer.tsx
- packages/app/src/vis-packs/core/ValueFetcher.tsx
- packages/app/src/vis-packs/core/complex/ComplexLineVisContainer.tsx
- packages/app/src/vis-packs/core/complex/ComplexVisContainer.tsx
- packages/app/src/vis-packs/core/compound/CompoundVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/hooks.ts
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/core/rgb/RgbVisContainer.tsx
- packages/app/src/vis-packs/core/surface/SurfaceVisContainer.tsx
- packages/app/src/vis-packs/nexus/NxNoteFetcher.tsx
- packages/app/src/vis-packs/nexus/NxValuesFetcher.tsx
- packages/app/src/vis-packs/nexus/hooks.ts
- packages/shared/src/guards.ts
Following #1759, I'm exporting a few more hooks and guards, still with the goal of making it easier to build a custom visualization that accesses data from one of `@h5web/app`'s providers, like [in the data portal](https://gitlab.esrf.fr/icat/data-portal/-/blob/main/packages/h5/src/h5/ImageVisForMXData.tsx).
Most notably, I'm exporting the following five hooks:
- **`useEntity`** (new) to get the metadata of an entity  at a given path from the entities store
- **`useDatasetValue`** to get a dataset's value from the values store
- **`useDatasetsValues`**  (previously named `useDatasetValues`) to get multiple datasets' values from the values store (notably when the list of datasets to access is dynamic)
- **`usePrefetchValues`** to prepare getting multiple datasets' values so they are …
> Export and document context access hooks

- packages/app/src/vis-packs/core/compound/utils.ts
- packages/app/src/vis-packs/core/line/utils.ts
We get column headers when exporting to CSV from the _NX Line_ and _Compound_ visualizations. In #1763, I overlooked the fact that dataset labels and compound field names can contain comas, which could potentially break CSV files.
> Strip comas in column headers when exporting to CSV

- apps/storybook/src/HeatmapMesh.stories.tsx
- apps/storybook/src/HeatmapVis.stories.tsx
- packages/lib/src/vis/heatmap/HeatmapMaterial.tsx
- packages/lib/src/vis/heatmap/HeatmapMesh.tsx
- packages/lib/src/vis/heatmap/HeatmapVis.tsx
- packages/lib/src/vis/heatmap/utils.ts
Fix #1721
`[HeatmapVis, HeatmapMesh]` Add props `magFilter` and `minFilter` to allow changing the heatmap texture's [magnification and minification filters](https://threejs.org/docs/#api/en/constants/Textures) (`NearestFilter` by default)
> Allow changing texture mag/min filter of Heatmap vis

- apps/demo/package.json
- packages/app/package.json
- pnpm-lock.yaml
Thank you for this amazing project!
This PR tries to bump Axios in order resolve [this vulnerability](https://github.com/axios/axios/security/advisories/GHSA-jr5f-v2jv-69x6).
I ran `pnpm outdated -r` and saw a fair few other dependencies that could be bumped, but I wanted to keep the PR small and targetted to have the smallest chance of causing unrelated issues.
> Bump `axios` to resolve vulnerability

- apps/demo/package.json
- apps/storybook/package.json
- apps/storybook/src/Toolbar.stories.tsx
- package.json
- packages/app/package.json
- packages/app/src/breadcrumbs/BreadcrumbsBar.tsx
- packages/app/src/vis-packs/VisBoundary.tsx
- packages/app/src/vis-packs/core/complex/ComplexLineToolbar.tsx
- packages/app/src/vis-packs/core/complex/ComplexToolbar.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapToolbar.tsx
- packages/app/src/vis-packs/core/line/ErrorsIcon.tsx
- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/app/src/vis-packs/core/matrix/MatrixToolbar.tsx
- packages/app/src/vis-packs/core/raw/RawToolbar.tsx
- packages/app/src/vis-packs/core/rgb/RgbToolbar.tsx
- packages/app/src/vis-packs/core/scatter/ScatterToolbar.tsx
- packages/h5wasm/package.json
- packages/lib/package.json
- packages/lib/src/toolbar/OverflowMenu.tsx
- packages/lib/src/toolbar/controls/Btn.tsx
- packages/lib/src/toolbar/controls/CellWidthInput.tsx
- packages/lib/src/toolbar/controls/ColorMapSelector/ColorMapSelector.tsx
- packages/lib/src/toolbar/controls/DomainWidget/DomainWidget.tsx
- packages/lib/src/toolbar/controls/ExportMenu.tsx
- packages/lib/src/toolbar/controls/InteractionHelp.tsx
- packages/shared/package.json
- pnpm-lock.yaml
I've relaxed the rule [`react/no-unstable-nested-components`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md) to allow the render prop pattern:
```tsx
<ErrorBoundary
fallbackRender={(args) => (
<ErrorFallback className={visualizerStyles.vis} {...args} />
)}
/>
```
The code above is okay (and unavoidable) as long as `fallbackRender` is used as a function inside `ErrorBoundary` - e.g. `{fallbackRender(...args)}`.
It's not okay when the render prop is used as a component. An example of this was the `icon` prop of the `Btn` component:
```tsx
// Btn.tsx
const { icon: Icon } = props;
return <>{Icon && <Icon className={styles.icon} />}</>
<Btn
// render prop but used as component
icon={(iconProps) => (
<FiItalic
transform="skewX(20)" …
```
> Don't misuse render prop pattern

- CONTRIBUTING.md
- apps/demo/package.json
- apps/demo/src/styles.css
- apps/storybook/.storybook/preview.ts
- apps/storybook/package.json
- apps/storybook/src/styles.css
- package.json
- packages/app/README.md
- packages/app/package.json
- packages/app/src/global-styles.css
- packages/app/src/styles.css
- packages/app/src/styles.ts
- packages/app/vite.styles.config.js
- packages/h5wasm/package.json
- packages/lib/README.md
- packages/lib/package.json
- packages/lib/src/global-styles.css
- packages/lib/src/styles.css
- packages/lib/vite.styles.config.js
- packages/shared/package.json
- pnpm-lock.yaml
- [Vite 6](https://vite.dev/blog/announcing-vite6.html) ([migration](https://vite.dev/guide/migration.html#migration-from-v5), [CHANGELOG](https://github.com/vitejs/vite/blob/v6.2.4/packages/vite/CHANGELOG.md))
- Only breaking change that concerns us is how Vite names CSS output files. It used to be `style.css` and couldn't be configured. Now, it uses either the package name (e.g. `app`) or the configured JS output `fileName` by default, and can be overridden with a dedicated option called [`cssFileName`](https://vite.dev/config/build-options.html#build-lib). So I made some minor adjustments to the `vite.styles.config.js` files and to the `build:css` scripts.
- [Vitest 3](https://github.com/vitest-dev/vitest/releases?page=2) ([migration](https://vitest.dev/guide/migration.html#migrating-to …
> Upgrade Vite and related dependencies

- .github/workflows/lint-test.yml
- apps/demo/src/Home.tsx
We received a report that `links.h5` did not actually contain external links and virtual datasets, contrary to what was said on the homepage. This is [now corrected](https://h5web.panosc.eu/h5grove?file=links.h5).
While I was at it, I updated the lists of files. I'll comment on the changes.
> Update lists of HDF5 files on homepage

- packages/app/src/ErrorFallback.tsx
- packages/app/src/providers/api.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/mock/utils.ts
- packages/app/src/providers/utils.ts
- packages/app/src/vis-packs/ValueLoader.tsx
- packages/shared/src/react-suspense-fetch.ts
I've got a working solution for removing `axios` from the providers (#1800), but it's going to take a few PRs...
This PR focuses on cleaning up the code related to aborting requests. I won't reexplain how this all works — the important bit is that, in order to show an informative error message with a "retry" button, we have to know when a request is aborted and why (e.g. manually by the user, or automatically when switching dataset).
To do this, we catch the error that axios (and the underlying `fetch` call) throws when a request is aborted via its [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/signal). We then rethrow our own error so that we have a very simple check to do in the generic `ErrorFallback` component (we definitely don't want to check if an …
> Throw custom `AbortError` when aborting a fetch

- packages/app/src/App.tsx
- packages/app/src/visualizer/VisManager.tsx
- packages/shared/src/react-suspense-fetch.ts
An abort error shows up when switching between two visualisation and the dimension mapping/slicing state is maintained. (Before, #1801, the abort reason "visualization changed" was displayed.)
This was due to a race condition:
```ts
function onVisChange(index: number) {
setActiveVis(index);
valuesStore.abortAll('visualization changed'); # aborts the fetch request, which is asynchronous
valuesStore.evictErrors(); # tries to evict error from store cache before it's actually been caught
}
```
[Screencast from 2025-05-16 09-30-11.webm](https://github.com/user-attachments/assets/b63ec505-d039-4733-b30a-c502dfa2b239)
The fix is to evict from cache as part of the `abortAll` call.
[Screencast from 2025-05-16 09-30-54.webm](https://github.com/user-attachments/assets/a58d2e39-566b-45a6-8d31-3bd8d073 …
> Fix race condition when evicting aborted requests from cache

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/utils.ts
- packages/app/src/providers/models.ts
- packages/app/src/providers/utils.ts
Part of #1800 
In order to remove `axios` from `H5GroveApi`, I first need to add a level of abstraction. In this PR, I introduce:
- a new `Fetcher` function type that accepts a URL and some params and returns an `ArrayBuffer`;
- a new  `FetcherError` class;
- a `createAxiosFetcher` utility to create a `Fetcher` function from an axios instance.
To keep the diff readable, I don't actually remove `axios` from `H5GroveApi` yet. For now, it's just an internal refactoring of `H5GroveApi`. The goal will of course be for consumers of `H5GroveProvider` to be able to pass their own `Fetcher` function.
> Refactor `H5GroveApi` with `Fetcher` abstraction

- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/h5grove/models.ts
Two individual commits to finish cleaning up `H5GroveApi` before I extract the `fetcher`:
1. First, I remove the private `fetch*` methods (like `fetchEntity`, `fetchValue`, etc.), as I no longer think they make the code more readable anymore. The calls to the new `fetcher` are now inlined in the main provider methods (`getEntity`, `getValue`, etc.)
I kept being annoyed at having to go up and down the file to follow what is, in the end, fairly straightforward code. This refactoring also reduces duplication a bit in the `getValue` method: I can prepare a `baseParams` object (with the `file`, `path` and `selection` parameters) and spread it in all three `fetcher` calls.
2. Second, I extract the h5grove error handling logic into a private method and use it on every endpoint.
The h5grove …
> Refactor `H5GroveApi` to simplify internals + handle errors on all endpoints

- apps/demo/src/H5GroveApp.tsx
- packages/app/README.md
- packages/app/src/index.ts
- packages/app/src/providers/h5grove/H5GroveProvider.tsx
- packages/app/src/providers/h5grove/h5grove-api.test.ts
- packages/app/src/providers/h5grove/h5grove-api.ts
- packages/app/src/providers/utils.ts
- packages/app/src/vis-packs/ValueLoader.module.css
- packages/shared/src/react-suspense-fetch.ts
It's finally coming together. Closes #1800.
Consumers can now provide their own fetcher and therefore their own axios instance (with custom headers, interceptors, etc.) As documented, some config options of the axios instance are ignored, like `baseURL`, `responseType`, etc.
Now that the `fetcher` is exposed through a prop on `H5GroveProvider` comes the question of whether to make it required or not. I chose to make it **optional** and to provide a basic fetcher implementation internally based on the Fetch API. My reasoning is that I don't want consumers to have to think about this `fetcher` business when they first install `@h5web/app` and try to use `H5GroveProvider` for the first time.
Technically, the only thing that the basic fetcher doesn't do that axios does is to track the …
> Allow consumers of `H5GroveProvider` to pass their own fetcher

- apps/demo/src/HsdsApp.tsx
- packages/app/src/providers/hsds/HsdsProvider.tsx
- packages/app/src/providers/hsds/hsds-api.ts
- packages/app/src/providers/hsds/utils.ts
- packages/app/src/providers/utils.ts
- packages/app/src/test-utils.tsx
To follow up on #1800, I now decouple axios from `HsdsApi` like I did in `H5GroveApi`.
I worked on improving error handling in a separate commit. Every internal `fetch` method now handles HSDS' "file not found" errors, and when HSDS doesn't return valid JSON (e.g. when a compression is not supported), I no longer silence the JSON parsing error:
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/569a3650-fa8e-4bc1-ae44-3fabc17bc15c) | ![image](https://github.com/user-attachments/assets/ae72173c-d322-43a4-bbfc-d39ba925a8a2) |
> Decouple axios from `HsdsProvider`

- packages/app/README.md
- packages/app/src/index.ts
- packages/app/src/providers/utils.ts
- Document the new `fetcher` prop of `HsdsProvider`
- Provide a way to initialialise a basic fetcher for `HsdsProvider` using basic HTTP authentication (just for convenience and so we can document a simple way to get started):
```ts
const fetcher = createBasicFetcher({
headers: buildBasicAuthHeader(USERNAME, PASSWORD),
});
```
> Allow passing request options to `createBasicFetcher`

- packages/app/package.json
- packages/app/src/providers/utils.ts
- pnpm-lock.yaml
I was planning on removing axios from the app package completely, but we need to keep it if we want `createAxiosFetcher` to be properly typed and type-checked.
So in the end, I turn it into a dev dependency and add it as an optional peer dependency. And to make sure this doesn't cause issues in consumer packages that don't install axios, I remove the two remaining non-type imports of `axios` from the app package (`isAxiosError` and `isCancel`).
> Make axios a peer/dev dep in app package

- packages/app/src/ErrorFallback.tsx
- packages/app/src/providers/mock/mock-api.ts
- packages/app/src/providers/mock/utils.ts
- packages/app/src/providers/utils.ts
- packages/shared/src/react-suspense-fetch.ts
This fixes an issue with the basic fetcher when requests are aborted (via `abortSignal.abort(<reason>)`).
In the h5grove demo, where the basic fetcher is configured without any headers, the browser throws a `DOMException`. But in the HSDS demo, where we pass an `Authentication` header for basic auth, the browser throws the abort reason as is (i.e. the reason string itself). Our current error handling logic expects a `DOMException`, so in the HSDS demo, we just see "Unknown error".
Both Firefox and Chrome behave the same way, so there must be an explanation but I could not find it. :disappointed: 
The fix is to simply look at the `abortSignal.aborted` flag in the `catch` block... It's basically what axios does as well (though in a much more convoluted way).
Additionally, I realised that …
> Fix abort error handling

- apps/storybook/src/DimensionMapper.stories.tsx
- packages/app/src/hooks.ts
- packages/app/src/vis-packs/core/complex/ComplexLineVisContainer.tsx
- packages/app/src/vis-packs/core/complex/ComplexVisContainer.tsx
- packages/app/src/vis-packs/core/compound/CompoundVisContainer.tsx
- packages/app/src/vis-packs/core/heatmap/HeatmapVisContainer.tsx
- packages/app/src/vis-packs/core/line/LineVisContainer.tsx
- packages/app/src/vis-packs/core/matrix/MatrixVisContainer.tsx
- packages/app/src/vis-packs/core/rgb/RgbVisContainer.tsx
- packages/app/src/vis-packs/core/surface/SurfaceVisContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxComplexSpectrumContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxImageContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxRgbContainer.tsx
- packages/app/src/vis-packs/nexus/containers/NxSpectrumContainer.tsx
- packages/lib/src/dimension-mapper/AxisMapper.tsx
- packages/lib/src/dimension-mapper/DimensionMapper.tsx
- packages/lib/src/dimension-mapper/SlicingSlider.module.css
- packages/lib/src/dimension-mapper/SlicingSlider.tsx
- packages/lib/src/toolbar/controls/ToggleGroup/ToggleGroup.module.css
I've made separate commits but I think the global diff is clear enough with some comments. The goal here is to improve the public API of `DimensionMapper` and to document it in Storybook:
Remaining work:
- allow customising appearance through CSS variables, and
- document utilities and hooks.
> Document dimension mapper and improve props

- apps/storybook/src/Utilities.mdx
- packages/lib/src/dimension-mapper/AxisMapper.tsx
- packages/lib/src/dimension-mapper/DimensionMapper.tsx
- packages/lib/src/dimension-mapper/hooks.ts
- packages/lib/src/dimension-mapper/models.ts
- packages/lib/src/dimension-mapper/utils.test.ts
- packages/lib/src/dimension-mapper/utils.ts
- packages/lib/src/index.ts
- packages/shared/src/vis-models.ts
Final PR about moving the dimension mapper and related utilities to the lib.
- Extract and expose a non-memoised utility from `useSlicedDimsAndMapping`: `getSlicedDimsAndMapping`.
- Document `initDimMapping`, `getSliceSelection`, `getSlicedDimsAndMapping` (and `useSlicedDimsAndMapping`)
- Unit test `getSliceSelection` and `getSlicedDimsAndMapping` (I already wrote tests for `initDimMapping` in a previous PR)
> Document and test dimension mapping utilities

- packages/h5wasm/src/worker.ts
Fix #1835 
My very naïve repro seems to confirm that it works:
```py
import h5py, numpy, time
with h5py.File("../swmr.h5", "w", libver="latest") as file:
arr = numpy.array([1, 2, 3, 4])
dset = file.create_dataset("data", data=arr)
file.swmr_mode = True
time.sleep(3600)
```
It's definitely simpler to just open all files in SWMR mode (rather than to first open without, catch the error and try again with SWMR). Do you know if there's any issue with that @woutdenolf @loichuder?
> Open local files in SWMR read mode with h5wasm

- .github/workflows/lint-test.yml
- apps/storybook/src/Histogram.stories.tsx
- packages/lib/src/toolbar/controls/Histogram/Histogram.tsx
It's the same issue we had with the heatmap vis: the x axis needs to go up to the right-hand edge of the last bin; otherwise we can't compute the width of the last bar and we get a `NaN` width warning in the browser console.
This PR makes the extra value in the `bins` array optional. If it's not present, we assume we want the same step value as between the last and second last bins.
> Make N+1 bin optional in histogram

- packages/app/src/vis-packs/core/complex/MappedComplexHeatmapVis.tsx
- packages/app/src/vis-packs/core/complex/MappedComplexLineVis.tsx
- packages/app/src/vis-packs/core/complex/hooks.ts
- packages/app/src/vis-packs/core/complex/utils.ts
- packages/app/src/vis-packs/core/heatmap/MappedHeatmapVis.tsx
- packages/app/src/vis-packs/core/line/MappedLineVis.tsx
- packages/app/src/vis-packs/core/matrix/MappedMatrixVis.tsx
- packages/app/src/vis-packs/core/rgb/MappedRgbVis.tsx
- packages/app/src/vis-packs/core/surface/MappedSurfaceVis.tsx
Memoisation was not quite right in the mapped complex vis components, especially in `MappedComplexLineVis`. The choice between using the phase or amplitude arrays and domains based on `complexVisType` has to be the last step—we have to compute and memoise them separately all the way otherwise we end up recomputing them or even re-transposing the arrays when the user interacts with the dimension mapper or the toolbar...
This neatens things up quite nicely, actually! :raised_hands:  We used to call the low-level utilities `getValidDomainForScale` and `getBaseArray` from the mapped complex vis components instead of the higher-level `useDomain` and `useMappedArray`. Now it's all consistent with the non-complex mapped vis components. :tada:
> Refactor mapped complex components to improve memoisation

- packages/app/src/App.module.css
We had chosen custom, brighter colors for auxiliary lines in dark mode but they were no longer applied due to an outdated CSS variable name.
> Fix aux colors in dark mode

- packages/lib/src/toolbar/controls/InteractionHelp.tsx
Fix #1869
@NAThompson I've used <kbd>Opt</kbd> instead of <kbd>⌥</kbd> for readability and consistency with using the names of the keys rather than their symbols. Is it okay do you think?
> Switch Alt to Opt on Mac in interaction help menu

- packages/app/src/vis-packs/core/line/LineToolbar.tsx
- packages/lib/src/index.ts
- packages/lib/src/toolbar/controls/LineAspectSelector/LineAspectSelector.tsx
- packages/lib/src/toolbar/controls/LineAspectSelector/RadioGroup.module.css
- packages/lib/src/toolbar/controls/LineAspectSelector/RadioGroup.tsx
Fix #1875 
[Screencast from 2025-09-25 13-48-01.webm](https://github.com/user-attachments/assets/a7488aa2-da4e-40b8-a740-d6cf5ca753cc)
Side boon: interpolation is disabled when displaying only points (since it is not relevant).
> Replace Line/Points and Piecewise toggle buttons by a dropdown
