silx-kit/h5web

src/h5web/metadata-viewer/MetadataViewer.module.css, src/h5web/metadata-viewer/MetadataViewer.tsx, src/h5web/metadata-viewer/RawInfo.tsx
=> Display raw metadata in accordion

src/h5web/App.module.css, src/h5web/App.tsx, src/h5web/dataset-visualizer/DatasetVisualizer.module.css, src/h5web/dataset-visualizer/DatasetVisualizer.tsx, src/h5web/dataset-visualizer/VisSelector.module.css, src/h5web/dataset-visualizer/VisSelector.tsx, src/h5web/dataset-visualizer/vis/MatrixVis.module.css, src/h5web/dataset-visualizer/vis/RawVis.module.css, src/h5web/dataset-visualizer/vis/RawVis.tsx, src/h5web/explorer/Explorer.module.css, src/styles/vars.css
=> Style visualization selector

package-lock.json, package.json, src/h5web/dataset-visualizer/DatasetVisualizer.tsx, src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/dataset-visualizer/VisSelector.tsx, src/h5web/dataset-visualizer/models.ts, src/h5web/dataset-visualizer/utils.ts, src/h5web/dataset-visualizer/vis/LineVis.module.css, src/h5web/dataset-visualizer/vis/LineVis.tsx, src/h5web/providers/models.ts, src/h5web/providers/utils.ts
Overall, it was quite straightforward to get a simple line graph up and running with [**Recharts**](http://recharts.org/en-US/examples/SimpleLineChart).
A few observations:
- I had some issues with their `ResponsiveContainer` so I used `AutoSizer` from `react-virtualized` instead. It does the same thing (i.e. provide a width and height to a sub-component).
- The input data array (a 1D array of numbers) has to be transformed into an array of objects representing each datapoint. I have the feeling this is the case with other charting libraries as well.
- There's an example of a [zoomable graph](http://recharts.org/en-US/examples/HighlightAndZoomLineChart) in the docs, which looks relatively straightforward.
- With 100,000 points, rendering takes a bit more than a second and the app doesn't …
=> Implement line vis 🎉✨🍻 

src/h5web/explorer/TreeView.tsx
=> Branchs in TreeView now collapse only if it was selected first

package-lock.json, package.json, src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/dataset-visualizer/VisSelector.tsx, src/h5web/dataset-visualizer/models.ts, src/h5web/dataset-visualizer/utils.ts, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/utils.ts, src/h5web/visualizations/index.ts, tsconfig.json
- Use Three.JS via react-three-fiber
- Render mesh with place geometry and basic material.
- Compute texture data in JS with `d3-scale` and map the texture to the basic material.
- Use `interpolateMagma` from `d3-scale-chromatic` for color map.
=> Implement Heatmap visualization

package-lock.json, package.json, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/IndexAxis.tsx, src/styles/base.css, src/styles/vars.css
=> Added indices axes for HeatMap

src/h5web/visualizations/heatmap/IndexAxis.tsx
<s>Uses an adapted version of what is given in [VX Axis demo](https://vx-demo.now.sh/axis).</s>
Uses d3-scale.
=> Number of ticks now depends on axis length in IndexAxis

src/h5web/visualizations/heatmap/utils.ts
=> Zoom to cursor

src/h5web/visualizations/heatmap/ColorBar.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/LogScaleToggler.tsx, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts, src/h5web/visualizations/heatmap/utils.ts
Uses [d3.scaleSymlog](https://github.com/d3/d3-scale/#symlog-scales) to handle 0 and negative numbers.
=> Implemented log scale for the colormap

package-lock.json, package.json, src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/visualizations/heatmap/ColorMapSelector.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/IndexAxis.tsx, src/h5web/visualizations/heatmap/interpolators.ts, src/h5web/visualizations/heatmap/store.ts
I use a lib called [easy-peasy](https://easy-peasy.now.sh/), more specifically [createContextStore](https://easy-peasy.now.sh/docs/api/create-context-store.html). It's built on top of Redux while providing a simple API for defining actions, computed properties, etc. and for accessing the state with hooks.
I've also refactored `IndexAxis` a little to use VX's `AxisLeft` and `AxisRight` components instead of `Axis`, which simplifies a couple of things.
=> Provide centralised heatmap state through context

src/h5web/dataset-visualizer/DatasetVisualizer.module.css, src/h5web/visualizations/heatmap/AxisGrid.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/IndexAxis.tsx, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts, src/h5web/visualizations/heatmap/store.ts
=> Axes now follows correctly when panning and zooming

src/h5web/BreadcrumbsBar.tsx, src/h5web/visualizations/heatmap/AxisGrid.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts
Fix #96 
Comments coming up...
=> Simplify Heatmap rendering and interactions with WebGL viewport

src/h5web/visualizations/heatmap/AxisGrid.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts
I think it will make more sense if you look at the files from bottom to top... and if you inspect the DOM yourself.
=> Position axis outside of canvas instead of setting viewport

src/h5web/visualizations/heatmap/ColorMapSelector.tsx, src/h5web/visualizations/heatmap/HeatmapToolbar.module.css, src/h5web/visualizations/heatmap/Toggler.tsx
PR to discuss the aspect of ColorMapSelector
=> Customization of the aspect of ColorMapSelector

src/h5web/visualizations/heatmap/DomainSlider.module.css, src/h5web/visualizations/heatmap/DomainSlider.tsx, src/h5web/visualizations/heatmap/config.ts
=> Added a button to reset colormap limits to data

src/h5web/visualizations/heatmap/DomainSlider.module.css, src/h5web/visualizations/heatmap/DomainSlider.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts
✨ 🎇 🌟 
It looks better live, but here's a taster:
=> Implement texture loading effect

src/h5web/storage-utils.ts, src/h5web/visualizations/heatmap/config.ts
Fix #72 
I added quite a few comments in the code, since it's not trivial. Let me know if anything needs clarifying.
=> Persist heatmap config

src/h5web/visualizations/shared/AxisSystem.module.css
=> Fix size of vertical axis when canvas is tiny

src/h5web/visualizations/heatmap/ColorBar.tsx, src/h5web/visualizations/heatmap/HeatmapToolbar.tsx, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/models.ts, src/h5web/visualizations/heatmap/utils.ts, src/h5web/visualizations/heatmap/worker.ts, src/h5web/visualizations/line/DataLine.tsx, src/h5web/visualizations/line/LineToolbar.tsx, src/h5web/visualizations/line/LineVis.tsx, src/h5web/visualizations/line/config.ts, src/h5web/visualizations/line/hooks.ts, src/h5web/visualizations/shared/AxisSystem.tsx, src/h5web/visualizations/shared/AxisSystemProvider.tsx, src/h5web/visualizations/shared/VisCanvas.tsx, src/h5web/visualizations/shared/models.ts, src/h5web/visualizations/shared/utils.ts
x log scale can be implemented along the same lines
=> Implemented y SymLog scale for LineVis

.eslintrc.json, package-lock.json, package.json, src/h5web/App.test.tsx, src/h5web/App.tsx, src/setupTests.js
Well, this was not trivial. I ran into versioning issues with the testing library, a bug when toggling the explorer panel, and plenty of uncertainties around when to use the testing library's async utilities...
I think the result takes us in the right direction with regard to testing, though.
Some of the documentation pages that helped me through this:
- https://testing-library.com/docs/guide-which-query - a god overview of all the queries avaialble
- https://testing-library.com/docs/dom-testing-library/api-queries - which query function throws, which is async, how to query multiple elements, etc.
- https://testing-library.com/docs/dom-testing-library/api-queries#byrole - the handiest query IMO
- https://github.com/A11yance/aria-query#elements-to-roles - if an element doesn't have an …
=> Add application tests

src/h5web/visualizations/heatmap/ColorMapSelector.tsx, src/h5web/visualizations/heatmap/config.ts, src/h5web/visualizations/heatmap/interpolators.ts, src/h5web/visualizations/heatmap/models.ts, src/h5web/visualizations/heatmap/utils.ts
=> Sort and group colour maps

src/h5web/dataset-visualizer/DatasetVisualizer.tsx, src/h5web/dataset-visualizer/DimensionMapper.module.css, src/h5web/dataset-visualizer/DimensionMapper.tsx, src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/dataset-visualizer/VisProvider.tsx, src/h5web/dataset-visualizer/models.ts, src/h5web/dataset-visualizer/utils.test.ts, src/h5web/dataset-visualizer/utils.ts, src/h5web/visualizations/line/hooks.ts
A first try to implement dimension mapping in the LineVis for 2D datasets.
This is rough around the edges but I think it was worth discussing the path it takes before going too far in the refinement.
=> Added DimensionMapper for 2D LineVis

src/h5web/dataset-visualizer/DimensionMapper.module.css, src/h5web/dataset-visualizer/DimensionMapper.tsx, src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/dataset-visualizer/VisProvider.tsx, src/h5web/dataset-visualizer/models.ts, src/h5web/visualizations/RawVis.tsx, src/h5web/visualizations/ScalarVis.tsx, src/h5web/visualizations/heatmap/hooks.ts, src/h5web/visualizations/line/hooks.ts, src/h5web/visualizations/matrix/hooks.ts
- Mapping is now an array of indices or dimensions.
- Values are transposed so that the slicing always operate on shallow dimensions for performance
- Some CSS styling
All in all, I hope this leads to clearer and better typed code.
=> Improvements to mapping of LineVis for 2d

src/h5web/visualizations/heatmap/DomainSlider.module.css, src/h5web/visualizations/heatmap/DomainSlider.tsx, src/h5web/visualizations/heatmap/HeatmapToolbar.tsx, src/h5web/visualizations/shared/ScreenshotButton.module.css
=> Improve domain slider design

src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/heatmap/hooks.ts, src/h5web/visualizations/heatmap/models.ts
=> Reset texture when changing dimensions

src/h5web/visualizations/heatmap/hooks.ts
=> Fix extraneous texture computations

.storybook/main.js, .storybook/preview.js, README.md, package-lock.json, package.json, src/h5web/visualizations/shared/AxisSystem.tsx, src/h5web/visualizations/shared/VisCanvas.tsx, src/stories/AxisSystem.stories.tsx
=> Install Storybook and write AxisSystem stories

src/stories/AxisSystem.stories.tsx
Fix #187 
- The canvas now fills the available space in every story.
- I've also added a story to demonstrate how to style the tick labels.
=> Improve AxisSystem stories

.storybook/decorators/FillHeight.tsx, .storybook/preview-head.html, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/stories/AxisSystem.stories.tsx, src/stories/HeatmapVis.stories.tsx
=> Add HeatmapVis story

src/stories/ColorBar.stories.tsx
=> Added more ColorBar stories

.storybook/decorators/FillHeight.tsx, src/h5web/visualizations/heatmap/ColorBar.module.css, src/h5web/visualizations/heatmap/ColorBar.tsx, src/h5web/visualizations/heatmap/HeatmapVis.module.css, src/stories/ColorBar.stories.tsx
Perhaps a bit early, but I foresee this will be needed for future integrations.
=> ColorBar can now be horizontal

src/h5web/dataset-visualizer/VisDisplay.tsx, src/h5web/visualizations/MappedHeatmapVis.tsx, src/h5web/visualizations/MappedLineVis.tsx, src/h5web/visualizations/MappedMatrixVis.tsx, src/h5web/visualizations/ScalarVis.tsx, src/h5web/visualizations/index.tsx
Next steps:
1. replace`MappedVis` with a hook;
1. pass configs as props to line and heatmap vis.
=> Replace `render` function with components in vis definitions

src/h5web/visualizations/MappedHeatmapVis.tsx, src/h5web/visualizations/MappedLineVis.tsx, src/h5web/visualizations/MappedMatrixVis.tsx, src/h5web/visualizations/shared/hooks.ts, src/react-app-env.d.ts
Next step:
1. Pass vis configs as props.
=> Turn MappedVis into a hook

src/h5web/dataset-visualizer/DatasetVisualizer.tsx, src/h5web/dataset-visualizer/hooks.ts, src/h5web/visualizations/MappedHeatmapVis.tsx, src/h5web/visualizations/MappedLineVis.tsx, src/h5web/visualizations/heatmap/HeatmapToolbar.tsx, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/config.ts, src/h5web/visualizations/heatmap/hooks.ts, src/h5web/visualizations/heatmap/utils.ts, src/h5web/visualizations/line/DataCurve.tsx, src/h5web/visualizations/line/LineVis.tsx, src/h5web/visualizations/shared/hooks.ts, src/stories/HeatmapVis.stories.tsx
=> Pass vis configs as props

.github/workflows/deploy-storybook.yml, .github/workflows/main.yml, .gitignore, README.md
I'll still need to set up the domain in the settings after I merge, and document the URL in the README.
=> Deploy Storybook to Github Pages

src/stories/ScalarVis.stories.tsx
While very basic, we might as well put it as it is an example in the [Story homepage](https://h5web-docs.panosc.eu/?path=/story/home--page).
=> Adding ScalarVis story

README.md, packages/package-lock.json, packages/package.json, packages/webpack.config.js, src/h5web/visualizations/heatmap/Mesh.tsx, src/h5web/visualizations/shared/AxisSystem.tsx, src/h5web/visualizations/shared/TooltipMesh.tsx
Fix #216 -- see https://github.com/silx-kit/h5web/issues/216#issuecomment-700613125 for details (which I've updated with the solution implemented in this PR).
=> Reduce lib bundle size by tree-shaking ThreeJS

src/h5web/dataset-visualizer/VisSelector.tsx, src/h5web/nexus-visualizer/NexusVisualizer.tsx, src/h5web/nexus-visualizer/models.ts, src/h5web/nexus-visualizer/utils.ts
Fix #231, #232 and #234 :shrug:
=> NexusVisualizer now provides a vis for NXdata group with valid signal attributes

src/h5web/visualizations/containers/NxImageContainer.tsx, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx, src/h5web/visualizations/shared/AxisSystem.module.css, src/h5web/visualizations/shared/AxisSystem.tsx, src/h5web/visualizations/shared/VisCanvas.tsx, src/stories/AxisSystem.stories.tsx, src/stories/HeatmapVis.stories.tsx
Fix #244 
Related stories were updated.
=> NxImage now shows the signal name as title of the heatmap

src/h5web/visualizations/containers/NxImageContainer.tsx, src/h5web/visualizations/containers/NxSpectrumContainer.tsx, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx, src/h5web/visualizations/heatmap/utils.ts, src/h5web/visualizations/line/MappedLineVis.tsx, src/h5web/visualizations/nexus/utils.ts, src/h5web/visualizations/shared/utils.ts, src/stories/HeatmapVis.stories.tsx
=> NxImage now uses the axes attribute values and labels

src/h5web/visualizations/shared/Axis.tsx
Fix #272 
Might be worth discussing a more clever fix
=> labelOffset is now dependent on the axis type

src/h5web/providers/mock/data.ts, src/h5web/visualizations/containers/NxImageContainer.tsx, src/h5web/visualizations/containers/NxSpectrumContainer.tsx
=> Now using NXdata dataset title for plot titles when available

.eslintignore, .gitignore, cypress.json, cypress/integration/app.spec.ts, cypress/support/index.js, cypress/tsconfig.json, package-lock.json, package.json, src/h5web/BreadcrumbsBar.tsx, src/h5web/dimension-mapper/DimensionMapper.module.css, src/h5web/dimension-mapper/DimensionMapper.tsx, src/h5web/visualizations/heatmap/HeatmapVis.tsx, src/h5web/visualizations/line/LineVis.tsx, src/h5web/visualizations/shared/AxisSystem.module.css, src/h5web/visualizations/shared/AxisSystem.tsx
Makes a good dent in #289.
To run the tests locally in a real browser:
1. Start the dev server.
2. In a second terminal, run `npm run cypress -- open`.
3. Click on "Run all tests" in the Cypress window that pops up. This will open a new browser window, run the tests in that browser, and re-run them when changes occur.
To run the tests headlessly, use `npm run cypress -- run --browser firefox`
Next steps will be to run Crypress in the CI and update the README.
=> Set up Cypress and write E2E tests

.github/workflows/deploy-storybook.yml, .github/workflows/main.yml, README.md, cypress.json, cypress/integration/app.spec.ts, package-lock.json, package.json
- Fix #289.
- Fix #292 
Well, this was not a walk in the park.
=> Run Cypress on CI

src/h5web/visualizations/line/ErrorBarCurve.tsx
Part of #235 
Could have been part of #298, sorry ! :pray:
=> Adding caps to error bars

src/h5web/providers/mock/data.ts, src/h5web/visualizations/containers/NxSpectrumContainer.tsx, src/h5web/visualizations/line/MappedLineVis.tsx, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/models.ts
=> Adds support for errors in NxSpectrum

src/h5web/providers/mock/data.ts, src/h5web/visualizations/line/LineVis.tsx, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/models.ts, src/h5web/visualizations/nexus/utils.ts, src/h5web/visualizations/shared/models.ts, src/h5web/visualizations/shared/utils.ts, src/stories/LineVis.stories.tsx, src/stories/LineVisDisplay.stories.tsx, src/stories/LineVisScales.stories.tsx
=> Added support for silx axes_scale_style in LineVis

src/h5web/providers/mock/data.ts, src/h5web/visualizations/containers/NxSpectrumContainer.tsx, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/models.ts
Once we agree on this, I will use the same process for the HeatmapVis
=> Added support of signal_scale_type for LineVis

src/h5web/providers/mock/data.ts, src/h5web/visualizations/containers/NxImageContainer.tsx
Same, same.
Final step of #281 
Love to put these green checkmarks everywhere :heavy_check_mark:
=> Added support of signal_scale_type for HeatmapVis

src/h5web/metadata-viewer/EntityInfo.tsx, src/h5web/providers/mock/utils.ts, src/h5web/providers/utils.ts, src/h5web/visualizations/index.tsx
=> Use generic types in HDF5 type guards

src/h5web/providers/utils.ts, src/h5web/visualizations/index.tsx, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/models.ts, src/h5web/visualizations/nexus/utils.ts, src/h5web/visualizations/shared/utils.ts
Nothing crazy, just adding a couple of utilities to remove duplicated code, and doing some minor clean-ups.
=> Add utilities to find signal name and dataset

src/h5web/visualizations/line/MappedLineVis.tsx
=> Domain is computed without errors if they are disabled in MappedLineVis

src/h5web/visualizations/shared/hooks.ts
See https://stackoverflow.com/questions/65020025/reduce-duplication-when-overloading-functions-in-typescript
=> Simplify TS overrides of `useBaseArray` and `useMappedArray`

README.md
With #279 fixed, the HSDS demo is now working.
=> Added HSDS demo section to README

packages/tsconfig.json, src/packages/lib.ts
Adding some building blocks :bricks:
=> Adding some exports to @h5web/lib and set rootDir for tsc

src/h5web/visualizations/nexus/config.ts
=> Error toggle in NxSpectrum config is now persisted

src/h5web/providers/mock/utils.ts
=> Fixed mock array generation

src/h5web/guards.ts, src/h5web/providers/Provider.tsx, src/h5web/providers/context.ts, src/h5web/visualizations/containers/hooks.ts, src/h5web/visualizations/index.tsx, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/utils.ts
Sooo much cleaner!! Good call on having a second look at `useDatasetValues` 😉
=> Take advantage of `name` property on `Dataset` model

src/h5web/providers/mock/data.ts, src/h5web/providers/mock/utils.ts, src/h5web/visualizations/containers/hooks.ts, src/h5web/visualizations/index.test.ts, src/h5web/visualizations/nexus/hooks.ts, src/h5web/visualizations/nexus/models.ts, src/h5web/visualizations/nexus/utils.ts, src/h5web/visualizer/utils.test.ts
=> Bit more cleanup in `useNxData`

src/h5web/dimension-mapper/DimensionMapper.tsx, src/h5web/providers/context.ts, src/h5web/providers/hsds/api.ts, src/h5web/providers/silx/api.ts, src/h5web/visualizations/containers/HeatmapVisContainer.tsx, src/h5web/visualizations/containers/LineVisContainer.tsx, src/h5web/visualizations/containers/MatrixVisContainer.tsx, src/h5web/visualizations/containers/NxImageContainer.tsx, src/h5web/visualizations/containers/NxSpectrumContainer.tsx, src/h5web/visualizations/containers/RawVisContainer.tsx, src/h5web/visualizations/containers/ScalarVisContainer.tsx, src/h5web/visualizations/containers/hooks.ts, src/h5web/visualizations/heatmap/MappedHeatmapVis.tsx, src/h5web/visualizations/line/MappedLineVis.tsx, src/h5web/visualizations/nexus/models.ts, src/h5web/visualizations/nexus/utils.ts, src/h5web/visualizations/shared/models.ts
... + a couple of other minor changes
=> Remove obsolete early returns in containers

src/h5web/visualizations/line/MappedLineVis.tsx
Fix #396  -- well, this was quite trivial!
=> Respect auto-scale when toggling errors

.github/workflows/release.yml, packages/package-lock.json, packages/package.json
For #358. To be tested once merged on `master`...
I think it's pretty self-explanatory, but here are the links to the GitHub Actions that I've used for reference:
- https://github.com/geritol/match-tag-to-package-version
- https://github.com/nyaa8/package-version (may not this one if the previous action were to output the version number - cf. https://github.com/geritol/match-tag-to-package-version/issues/2)
- https://github.com/Reedyuk/NPM-Version
- https://github.com/marketplace/actions/npm-publish
=> Implement CI release workflow

.prettierrc.json, CONTRIBUTING.md, LICENSE.md, README.md, packages/app/README.md, packages/lib/README.md
=> Add CONTRIBUTING, document release process and improve README

src/h5web/App.tsx, src/h5web/BreadcrumbsBar.tsx, src/h5web/explorer/EntityList.tsx, src/h5web/guards.ts, src/h5web/providers/context.ts, src/h5web/providers/hsds/api.ts, src/h5web/providers/mock/MockProvider.tsx, src/h5web/providers/mock/data.ts, src/h5web/providers/mock/utils.ts, src/h5web/utils.ts
=> Check for absolute paths and facilitate their creation

src/h5web/toolbar/controls/ScaleOption.tsx, src/h5web/toolbar/controls/ScaleSelector.tsx
Perhaps the root cause of https://github.com/silx-kit/jupyterlab-h5web/issues/1 ?
=> Moved ScaleOption in its own file

cypress/specs/app.spec.ts, src/h5web/explorer/Explorer.module.css, src/h5web/metadata-viewer/MetadataViewer.test.tsx
=> Fix wrapping of text in Explorer

src/h5web/vis-packs/core/heatmap/MappedHeatmapVis.tsx, src/h5web/vis-packs/core/line/MappedLineVis.tsx, src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx, src/h5web/vis-packs/hooks.ts
Just creating a hook to abstract some of the complexity, and make it fit on one line and potentially move it in the container.
=> Refactor initialisation of dimension mapping state

src/h5web/providers/hsds/models.ts, src/h5web/providers/hsds/utils.test.ts, src/h5web/providers/hsds/utils.ts
=> Added tests for convertHsdsType

.env, package-lock.json, package.json, src/h5web/test-utils.tsx, src/h5web/vis-packs/core/CorePack.test.tsx, src/h5web/vis-packs/nexus/NexusPack.test.tsx, src/h5web/vis-packs/nexus/utils.test.ts, src/setupTests.js
https://github.com/facebook/create-react-app/releases/tag/v4.0.2
=> Upgrade react-scripts to 4.0.2

src/h5web/providers/hdf5-models.ts, src/h5web/providers/jupyter/api.ts, src/h5web/providers/jupyter/utils.test.ts, src/h5web/providers/jupyter/utils.ts
=> HDF5type is now deduced from dtype in JupyterProvider

src/h5web/providers/hdf5-models.ts, src/h5web/providers/hsds/models.ts, src/h5web/providers/hsds/utils.test.ts, src/h5web/providers/hsds/utils.ts, src/h5web/providers/jupyter/utils.test.ts, src/h5web/providers/jupyter/utils.ts, src/h5web/providers/mock/metadata-utils.ts
Follow up of #459 : https://github.com/silx-kit/h5web/pull/459#discussion_r570146915 and https://github.com/silx-kit/h5web/pull/459#discussion_r570147159
=> Removed strPad and prefix of charSet in HDF5StringType

src/h5web/App.module.css, src/h5web/App.tsx, src/styles/base.css
Follow-up of #472 to fix https://github.com/silx-kit/jupyterlab-h5web/issues/12
=> Moved white background setting at the App level

src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx, src/h5web/vis-packs/core/heatmap/ShadersMesh.tsx
Co-authored-by: Axel Bocciarelli <axelboc@gmail.com>
=> Implemented color map support in ShadersMesh

src/h5web/vis-packs/nexus/hooks.ts, src/h5web/vis-packs/nexus/models.ts
=> useNxData now gets auxiliary_signals attr and associated datasets

src/h5web/vis-packs/core/utils.test.ts, src/h5web/vis-packs/core/utils.ts
Fixed a bug introduced in #537 
Sorry :pray:
=> Fixed domain extension for single negative value domain

src/h5web/vis-packs/core/hooks.ts, src/h5web/vis-packs/core/shared/Html.tsx, src/h5web/vis-packs/core/shared/PanZoomMesh.tsx, src/stories/HeatmapVis.stories.tsx
=> Stop wheel events so page doesn't scroll while zooming

src/h5web/toolbar/controls/DomainSlider/BoundEditor.module.css, src/h5web/toolbar/controls/DomainSlider/BoundEditor.tsx, src/h5web/toolbar/controls/DomainSlider/DomainTooltip.module.css, src/h5web/utils.ts
Also, deal with minus sign to avoid `NaN`.
=> Keep exponent notation when editing bounds (but increase precision)

src/h5web/providers/jupyter/api.ts, src/h5web/providers/jupyter/models.ts
`attributeCount` and `childrenCount` were added after 0.5.1 release
=> Made Jupyter provider compatible with jupyterlab_hdf 0.5.1

src/h5web/dimension-mapper/DimensionMapper.test.tsx, src/h5web/explorer/Explorer.test.tsx, src/h5web/metadata-viewer/MetadataViewer.test.tsx, src/h5web/test-utils.tsx
`userEvent.click` simulates a proper browser click, with all the underlying events and behaviours: https://github.com/testing-library/user-event/blob/master/src/click.ts
=> Replace `fireEvent.click` with `userEvent.click`

src/h5web/metadata-viewer/AttributesTable.tsx, src/h5web/providers/hsds/api.ts, src/h5web/providers/hsds/utils.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/providers/mock/metadata.ts, src/h5web/providers/models.ts, src/h5web/vis-packs/nexus/utils.test.ts
Part of #519 
Same as #587 but with attributes.
=> Simplify representation of attribute shapes

src/h5web/metadata-viewer/MetadataViewer.test.tsx, src/h5web/metadata-viewer/utils.ts, src/h5web/providers/hdf5-models.ts, src/h5web/providers/hsds/models.ts, src/h5web/providers/hsds/utils.test.ts, src/h5web/providers/hsds/utils.ts, src/h5web/providers/jupyter/utils.test.ts, src/h5web/providers/jupyter/utils.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/vis-packs/core/models.ts
=> Simplify and improve rendering of HDF5 types

src/h5web/providers/hdf5-models.ts, src/h5web/providers/hsds/models.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/providers/models.ts
Just a quick one so it doesn't clutter the next one with the links.
=> Remove `HDF5Dims` type

src/h5web/providers/context.ts, src/h5web/providers/hdf5-models.ts, src/h5web/providers/hsds/api.ts, src/h5web/providers/hsds/models.ts, src/h5web/providers/jupyter/api.ts, src/h5web/providers/jupyter/models.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/providers/mock/models.ts, src/h5web/providers/models.ts, src/h5web/vis-packs/core/hooks.ts, src/h5web/vis-packs/nexus/pack-utils.ts, src/h5web/vis-packs/nexus/utils.ts
=> Remove `HDF5Value` and use `unknown` directly

src/h5web/App.tsx, src/h5web/breadcrumbs/BreadcrumbsBar.tsx, src/h5web/explorer/EntityItem.tsx, src/h5web/metadata-viewer/AttributesTable.tsx, src/h5web/metadata-viewer/MetadataViewer.module.css, src/h5web/metadata-viewer/MetadataViewer.test.tsx, src/h5web/metadata-viewer/MetadataViewer.tsx
Part of #582 
https://user-images.githubusercontent.com/2936402/114418536-e564bb00-9bb2-11eb-8fa2-dc1f1fc606cc.mp4
I haven't made attributes with array values clickable yet.
=> Make paths in metadata viewer clickable

src/h5web/providers/hsds/api.ts, src/h5web/providers/jupyter/api.ts
=> Added compatible provider versions to API

src/h5web/breadcrumbs/Breadcrumbs.tsx, src/h5web/breadcrumbs/BreadcrumbsBar.module.css, src/h5web/breadcrumbs/CopyableCrumb.tsx
I used `navigator.clipboard.writeText`: https://caniuse.com/?search=clipboard
=> Added button to copy current path to clipboard

src/h5web/guards.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/vis-packs/core/visualizations.test.ts
Fixes a regression introduced in #519 resolution
=> Matrix and Scalar vis support datasets of unsigned int types 

src/h5web/Profiler.tsx, src/h5web/vis-packs/core/line/DataCurve.tsx, src/h5web/vis-packs/core/line/ErrorBars.tsx, src/h5web/vis-packs/core/line/LineVis.tsx, src/h5web/vis-packs/core/line/hooks.ts, src/h5web/vis-packs/core/shared/VisCanvas.tsx
One big optimisation with `useMemo` and some minor ones.
=> Optimise LineVis when slicing

src/h5web/guards.ts, src/h5web/vis-packs/core/line/LineVis.tsx, src/h5web/vis-packs/core/utils.ts
Just to clean up the `LineVis` component, and `getDomain` a bit.
=> Add same-length assertion function for arrays

src/h5web/vis-packs/core/hooks.ts, src/h5web/vis-packs/core/shared/PanZoomMesh.tsx
=> Fix scroll capture

src/h5web/visualizer/Visualizer.test.tsx, src/h5web/visualizer/Visualizer.tsx
=> Change "Nothing to Visualize" message

src/h5web/guards.ts, src/h5web/metadata-viewer/AttributesTable.tsx, src/h5web/metadata-viewer/utils.ts, src/h5web/providers/hsds/utils.ts, src/h5web/providers/mock/metadata-utils.ts, src/h5web/providers/models.ts, src/h5web/utils.ts, src/h5web/vis-packs/core/containers/ScalarVisContainer.tsx, src/h5web/vis-packs/core/matrix/Cell.tsx, src/h5web/vis-packs/core/matrix/GridSettingsContext.tsx, src/h5web/vis-packs/core/matrix/MappedMatrixVis.tsx, src/h5web/vis-packs/core/matrix/MatrixVis.tsx, src/h5web/vis-packs/core/scalar/ScalarVis.tsx
Retry of #627 by implementing https://github.com/silx-kit/h5web/pull/627#discussion_r618433862 (in some measure) and https://github.com/silx-kit/h5web/pull/627#discussion_r618446924.
**Matrix:**
**Attribute:**
**Scalar:**
=> Fixed display of complex data for attributes, Matrix and ScalarVis

src/h5web/providers/utils.ts, src/h5web/vis-packs/core/hooks.ts, src/h5web/vis-packs/core/utils.ts
There was a small bug that prevented retrying the fetch of a 2D dataset from the Heatmap vis.
=> Fix retrying to fetch 2D dataset from Heatmap vis

package-lock.json, package.json, src/h5web/vis-packs/core/heatmap/config.tsx, src/h5web/vis-packs/core/line/config.tsx
zustand has two excellent improvements that allow us to simplify a few things: https://github.com/pmndrs/zustand/releases/tag/v3.5.0
=> Upgrade zustand and simplify code

package-lock.json, package.json, src/h5web/providers/hsds/HsdsProvider.tsx, src/h5web/toolbar/controls/ToggleGroup.tsx, src/h5web/vis-packs/core/complex/hooks.ts, src/h5web/vis-packs/core/hooks.ts, src/h5web/vis-packs/core/shared/VisCanvas.tsx
https://prettier.io/blog/2021/05/09/2.3.0.html#api
=> Upgrade Prettier and apply new formatting

.storybook/preview.js, src/h5web/vis-packs/core/line/LineVis.tsx, src/packages/app.ts, src/stories/Customization.stories.mdx, src/stories/GettingStarted.stories.mdx, src/stories/Utilities.stories.mdx, src/styles/vars.css
Fix #631, fix #644 and proof of concept for #555
=> Add "Customization" page to Storybook and first two semantic CSS vars for line vis

cypress/specs/app.spec.ts, src/h5web/toolbar/ComplexLineToolbar.tsx, src/h5web/vis-packs/core/complex/MappedComplexLineVis.tsx, src/h5web/vis-packs/core/complex/MappedComplexVis.tsx, src/h5web/vis-packs/core/complex/hooks.ts, src/h5web/vis-packs/core/complex/lineConfig.tsx, src/h5web/vis-packs/core/complex/models.ts, src/h5web/vis-packs/core/complex/utils.ts, src/h5web/vis-packs/core/containers/ComplexLineVisContainer.tsx, src/h5web/vis-packs/core/visualizations.test.ts, src/h5web/vis-packs/core/visualizations.ts
Work on #310 
I kept `ComplexVis` as name for the 2D Complex vis but we can rename it (in `ComplexMap` for example).
=> Adds LineVis for complex data (phase/amplitude)

.eslintrc.js, .gitignore, .prettierignore, package-lock.json, package.json, src/h5web/dimension-mapper/AxisMapper.tsx, src/h5web/dimension-mapper/DimensionMapper.tsx, src/h5web/dimension-mapper/utils.ts, src/h5web/metadata-viewer/EntityTable.tsx, src/h5web/providers/mock/values.ts, src/h5web/vis-packs/core/heatmap/utils.ts, src/h5web/vis-packs/core/matrix/IndexTrack.tsx, src/h5web/vis-packs/core/shared/PanZoomMesh.tsx, src/h5web/vis-packs/core/utils.ts, src/h5web/vis-packs/nexus/containers/NxSpectrumContainer.tsx
Applying some of the things I learned while working on Braggy.
=> Replace lodash-es with lodash

src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx, src/packages/lib.ts, src/stories/HeatmapVis.stories.tsx
I added a new story to see if it worked but I want to try with a "real" usecase before documenting it thoroughly
=> Export Html and add possibility to add children to HeatmapVis

.storybook/main.js
=> Fix storybook error with TS 4.3 by using react-docgen

cypress/specs/app.spec.ts, src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx, src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx, src/h5web/vis-packs/core/line/LineVis.tsx, src/h5web/vis-packs/core/line/hooks.ts, src/h5web/vis-packs/core/shared/Annotation.tsx, src/h5web/vis-packs/core/shared/AxisSystem.tsx, src/h5web/vis-packs/core/shared/AxisSystemContext.tsx, src/h5web/vis-packs/core/shared/AxisSystemProvider.tsx, src/h5web/vis-packs/core/shared/PanZoomMesh.tsx, src/h5web/vis-packs/core/shared/TooltipMesh.tsx, src/h5web/vis-packs/core/shared/VisCanvas.tsx, src/h5web/vis-packs/core/shared/VisMesh.tsx, src/packages/lib.ts, src/stories/Utilities.stories.mdx, src/stories/VisCanvas.stories.tsx
... and bring `AxisSystem` and its provider back inside `VisCanvas`.
=> Fix continuous re-renders by separating out provider from `AxisSystem`

src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx, src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx, src/h5web/vis-packs/core/models.ts, src/h5web/vis-packs/core/utils.ts, src/stories/HeatmapVis.stories.tsx
=> Add the possibility to flip the y axis in HeatmapVis

packages/lib/package.json, packages/package-lock.json, packages/package.json, packages/webpack.config.js
Re-opening this, but limiting the change to R3F as per your initial PR @loichuder, so we can at least remove the `// @ts-ignore` from Braggy.
=> Put R3F in dep of lib and external in webpack

src/h5web/utils.ts, src/h5web/vis-packs/core/containers/RgbVisContainer.tsx, src/h5web/vis-packs/core/models.ts, src/h5web/vis-packs/core/utils.ts, src/h5web/vis-packs/core/visualizations.ts
Follow-up of https://github.com/silx-kit/h5web/pull/723#pullrequestreview-693953694 and https://github.com/silx-kit/h5web/pull/723#issuecomment-870329229
=> Make clear that IMAGE_SUBCLASS other than IMAGE_TRUECOLOR are unsupported

.storybook/preview.js, src/h5web/vis-packs/core/heatmap/ColorBar.tsx, src/h5web/vis-packs/core/shared/TooltipMesh.module.css, src/h5web/vis-packs/core/shared/TooltipMesh.tsx, src/stories/ColorBar.stories.tsx, src/stories/ColorBarHorizontal.stories.tsx, src/stories/HeatmapVis.stories.tsx, src/stories/LineVis.stories.tsx, src/stories/LineVisDisplay.stories.tsx, src/stories/LineVisScales.stories.tsx, src/stories/MatrixVis.stories.tsx, src/stories/Toolbar.stories.tsx, src/stories/VisCanvas.stories.tsx, src/stories/VisCanvasInteraction.stories.tsx, src/stories/decorators/FillHeight.tsx
=> Document tooltip and pan-zoom interactions

src/h5web/metadata-viewer/EntityTable.tsx, src/h5web/providers/Provider.tsx, src/h5web/providers/context.ts
=> Show filepath instead of filename in root group entity table

README.md
Codesandboxes were updated btw.
=> Add h5grove to the list of demos

src/h5web/vis-packs/core/shared/VisMesh.tsx
=> Fix position of TooltipMesh when X/Y scales are not linear

src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx, src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx, src/h5web/toolbar/controls/DomainSlider/Histogram.tsx, src/h5web/toolbar/controls/DomainSlider/HistogramColorBar.tsx, src/h5web/vis-packs/core/heatmap/utils.ts, src/h5web/vis-packs/core/models.ts, src/stories/ColorBar.stories.tsx, src/stories/ColorBarHorizontal.stories.tsx, src/stories/DomainSlider.stories.tsx
=> Add color bar below the histogram

package-lock.json, package.json, src/h5web/toolbar/ComplexToolbar.tsx, src/h5web/toolbar/HeatmapToolbar.tsx, src/h5web/toolbar/controls/DomainSlider/ScaledSlider.tsx, src/h5web/vis-packs/core/gammaScale.test.ts, src/h5web/vis-packs/core/gammaScale.ts, src/h5web/vis-packs/core/heatmap/ColorBar.tsx, src/h5web/vis-packs/core/heatmap/HeatmapMesh.tsx, src/h5web/vis-packs/core/heatmap/HeatmapVis.tsx, src/h5web/vis-packs/core/heatmap/models.ts, src/h5web/vis-packs/core/models.ts, src/h5web/vis-packs/core/scales.ts, src/h5web/vis-packs/core/shared/Axis.tsx, src/h5web/vis-packs/core/utils.ts, src/stories/HeatmapVis.stories.tsx, src/stories/HeatmapVisScales.stories.tsx
Fix #741 
So messy :disappointed:
=> Implement gamma scale

packages/lib/src/h5web/toolbar/controls/Selector/Selector.tsx, packages/lib/src/h5web/toolbar/controls/Selector/models.ts
Requested in https://gitlab.esrf.fr/ui/h5web-braggy/-/merge_requests/45#note_143426
=> Add `isSelected` prop to `Option` in `Selector`

packages/lib/src/h5web/toolbar/controls/DomainSlider/DomainSlider.tsx, packages/lib/src/h5web/toolbar/controls/DomainSlider/DomainTooltip.tsx, packages/lib/src/h5web/toolbar/controls/DomainSlider/Histogram.tsx
Fix #793 
The problem was in fact twofold (see below)
=> Make histogram domain safe with respect to data domain 

apps/demo-cra-lib/src/App.tsx, apps/demo-cra-lib/src/styles.css
=> Improve lib demo

apps/demo-cra-lib/config-overrides.js, apps/demo/config-overrides.js
=> Detect and report linting errors in entire workspace when running demos

packages/app/src/vis-packs/nexus/utils.ts, packages/app/src/visualizer/utils.ts
=> Fetch `NX_class` attributes on demand when looking for implicit default child

cypress/specs/app.spec.ts
=> Wait for color map scale to change in E2E tests to avoid failures

apps/storybook/src/VisCanvasInteraction.stories.tsx, packages/lib/src/index.ts, packages/lib/src/vis/shared/Selection.tsx, packages/lib/src/vis/shared/SelectionMesh.tsx
Answering the most basic need of #862
This is mostly to discuss integration/organization in the exisiting projects and packages.
=> Add a component to be able to draw selections on data

packages/app/src/providers/h5grove/h5grove-api.ts, packages/app/src/providers/h5grove/utils.ts, packages/app/src/providers/models.ts
=> Add specific Provider error for unresolvable links

packages/app/src/App.tsx, packages/app/src/__tests__/Visualizer.test.tsx, packages/app/src/visualizer/VisManager.tsx
=> Cancel on-going requests when changing entity or vis

packages/app/src/__tests__/CorePack.test.tsx, packages/app/src/__tests__/DimensionMapper.test.tsx, packages/app/src/dimension-mapper/hooks.ts
=> Debounce dim mapping state to reduce fetching rate when slicing

packages/app/src/App.tsx
=> Fix resizing of explorer

packages/lib/src/vis/shared/PanZoomMesh.tsx
Next up, I'll do some optimising in `VisCanvas`, as we're currently over-rendering on resize because of `useMeasure`. I'll also tweak the `debounce` settings of R3F, as it is currently inconsistent (no debounce at all when resizing the window vs. a significant debounce when resizing the explorer panel).
=> Keep viewport center ... centered on resize

apps/storybook/src/HeatmapVis.stories.tsx, packages/app/src/vis-packs/core/complex/MappedComplexVis.tsx, packages/lib/src/vis/heatmap/HeatmapVis.tsx
=> Display alpha values in Heatmap tooltip

packages/app/src/providers/Provider.tsx, packages/app/src/providers/api.ts, packages/app/src/providers/context.ts, packages/app/src/providers/h5grove/h5grove-api.ts, packages/app/src/providers/models.ts, packages/app/src/vis-packs/ValueLoader.module.css, packages/app/src/vis-packs/ValueLoader.tsx
Fix #892 
New version with listeners in the API.
Still the problem that the back-end doesn't send the total size of the data for some reason (probably missing `Content-Length` HTTP header).
=> Show progress while fetching dataset values

apps/storybook/src/Customization.stories.mdx, apps/storybook/src/GettingStarted.stories.mdx, apps/storybook/src/Utilities.stories.mdx, apps/storybook/src/VisCanvasInteraction.stories.tsx, packages/lib/src/index.ts, packages/lib/src/vis/shared/LineSelectionMesh.tsx, packages/lib/src/vis/shared/RectSelectionMesh.tsx, packages/lib/src/vis/shared/SelectionLine.tsx, packages/lib/src/vis/shared/SelectionMesh.tsx, packages/lib/src/vis/shared/SelectionRect.tsx
=> Allow SelectionMesh to display lines instead of rectangles

packages/lib/src/vis/shared/PanZoomMesh.tsx
=> Compute camera bounds from camera matrix rather than manually

apps/demo-cra-lib/package.json, apps/demo/package.json, apps/storybook/.eslintrc.cjs, apps/storybook/package.json, apps/storybook/src/ColorBar.stories.tsx, apps/storybook/src/ColorBarHorizontal.stories.tsx, apps/storybook/src/react-app-env.d.ts, apps/storybook/src/types.d.ts, cypress/specs/app.spec.ts, package.json, packages/app/README.md, packages/app/package.json, packages/app/vite.config.js, packages/lib/package.json, packages/lib/src/vis/heatmap/utils.test.ts, packages/lib/vite.config.js, packages/shared/package.json, pnpm-lock.yaml
Only the safe stuff for now, will try to upgrade CRA tomorrow.
=> Upgrade dependencies

apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts
As requested by @t20100 for BM18.
=> Expose `useFrameRendering` hook

README.md, apps/storybook/src/GettingStarted.stories.mdx, packages/app/README.md, packages/lib/README.md
=> Put forward data visualisation instead of HDF5 viewing in doc

apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts, packages/lib/src/vis/hooks.ts, packages/lib/src/vis/shared/AxisSystem.tsx, packages/lib/src/vis/shared/AxisSystemContext.tsx, packages/lib/src/vis/shared/PanZoomMesh.tsx, packages/lib/src/vis/utils.ts
@t20100 this should make your life much easier, as you requested :wink:
=> Add hook to compute visible axis domains

apps/storybook/src/VisCanvasInteraction.stories.tsx, packages/lib/src/index.ts, packages/lib/src/vis/shared/PanZoomMesh.tsx, packages/lib/src/vis/shared/SelectionMesh.tsx, packages/lib/src/vis/shared/TooltipMesh.tsx, packages/lib/src/vis/utils.ts
Work for #769 
Follow-up of #947
=> Allow disabling pan/zoom and modifier keys to zoom in X or Y

packages/lib/src/vis/line/DataCurve.tsx
To be able to toggle its visibility
=> Add visible prop to DataCurve

packages/lib/src/vis/heatmap/HeatmapMesh.tsx, packages/lib/src/vis/heatmap/HeatmapVis.tsx, packages/lib/src/vis/heatmap/models.ts, packages/lib/src/vis/heatmap/utils.ts, packages/lib/src/vis/utils.ts, packages/shared/src/guards.ts, packages/shared/src/utils.ts
Very elegant solution @t20100, thanks!
I took the opportunity to refactor the shader's scale functions a bit further.
=> Support raw uint8 values in `HeatmapMesh`

apps/storybook/src/ScatterVis.stories.tsx, packages/lib/src/vis/scatter/ScatterVis.tsx
=> Fix y axis domain computation in ScatterVis

apps/storybook/src/Selection.stories.tsx, apps/storybook/src/VisCanvasSelection.stories.tsx, packages/lib/src/vis/shared/LineSelectionMesh.tsx, packages/lib/src/vis/shared/RectSelectionMesh.tsx, packages/lib/src/vis/shared/SelectionLine.tsx, packages/lib/src/vis/shared/SelectionMesh.tsx, packages/lib/src/vis/shared/SelectionRect.tsx
And [Move Selection stories out of VisCanvas category](https://github.com/silx-kit/h5web/commit/70e35f1a867fde33f364a0f3808a2bf30a1ff6c2)
=> Allow Line and RectSelectionMesh to specify color of the selection

packages/app/src/__tests__/CorePack.test.tsx, packages/app/src/__tests__/DimensionMapper.test.tsx, packages/app/src/dimension-mapper/DimensionMapper.tsx, packages/app/src/dimension-mapper/SlicingSlider.tsx
=> Debounce slicing without affecting UI responsiveness

packages/lib/src/vis/heatmap/HeatmapVis.tsx, packages/lib/src/vis/line/LineVis.tsx, packages/lib/src/vis/rgb/RgbVis.tsx, packages/lib/src/vis/scatter/ScatterVis.tsx, packages/lib/src/vis/shared/ZoomSelectionMesh.tsx
Fix #966. I still need to fix the behaviour when the pointer goes out of the window. Probably related to pointer capture
=> Add ZoomSelectionMesh to Heatmap, Line, Rgb and ScatterVis

apps/storybook/src/Selection.stories.tsx, packages/lib/src/vis/shared/AxisSystemContext.tsx, packages/lib/src/vis/shared/AxisSystemProvider.tsx, packages/lib/src/vis/shared/Html.tsx, packages/lib/src/vis/shared/SelectToZoom.tsx, packages/lib/src/vis/shared/SelectionLine.tsx, packages/lib/src/vis/shared/SelectionRect.tsx, packages/lib/src/vis/shared/TooltipMesh.tsx, packages/lib/src/vis/shared/hooks.ts, packages/lib/src/vis/utils.ts
Fix #997 and https://github.com/silx-kit/h5web/issues/993#issuecomment-1058018044.
Fixes #998 as well.
=> Draw SelectionLine and Rect with svg rather than WebGL

apps/storybook/src/Pan.stories.tsx, apps/storybook/src/SelectToZoom.stories.tsx, apps/storybook/src/Selection.stories.tsx, apps/storybook/src/Utilities.stories.mdx, apps/storybook/src/XZoom.stories.tsx, apps/storybook/src/YZoom.stories.tsx, apps/storybook/src/Zoom.stories.tsx, packages/app/README.md, packages/lib/README.md, packages/lib/src/index.ts, packages/lib/src/vis/shared/hooks.ts
=> Expose and document hook `useCanvasEvents` + misc documentation improvements

apps/storybook/src/Pan.stories.tsx, apps/storybook/src/SelectToZoom.stories.tsx, apps/storybook/src/Selection.stories.tsx, apps/storybook/src/Toolbar.stories.tsx, apps/storybook/src/XZoom.stories.tsx, apps/storybook/src/YZoom.stories.tsx, apps/storybook/src/Zoom.stories.tsx, packages/lib/src/index.ts, packages/lib/src/interactions/Pan.tsx, packages/lib/src/interactions/XAxisZoom.tsx, packages/lib/src/interactions/YAxisZoom.tsx, packages/lib/src/interactions/Zoom.tsx, packages/lib/src/interactions/hooks.ts, packages/lib/src/interactions/models.ts, packages/lib/src/toolbar/Toolbar.tsx, packages/lib/src/toolbar/controls/InteractionHelp.tsx, packages/lib/src/vis/heatmap/HeatmapVis.tsx, packages/lib/src/vis/line/LineVis.tsx, packages/lib/src/vis/rgb/RgbVis.tsx, packages/lib/src/vis/scatter/ScatterVis.tsx, packages/lib/src/vis/shared/AxisSystemProvider.tsx, packages/lib/src/vis/shared/VisCanvas.tsx, packages/lib/src/vis/utils.ts
Work towards #1020 
The last step will be to allow interactions to be changed through a prop of `...Vis` components that will be forwarded to `VisCanvas`
=> Disable interactions via VisCanvas

packages/lib/src/vis/scatter/ScatterVis.tsx
=> Make ScatterVis children optional

packages/app/src/providers/h5grove/models.ts, packages/app/src/providers/h5grove/utils.ts
Typo found while browsing the code.
=> Fix typo: H5GroveDatasetRe*s*ponse

packages/lib/src/interactions/SelectionTool.tsx
=> Cancel selection in SelectionTool on Escape

apps/storybook/src/SelectToZoom.stories.tsx, packages/lib/src/interactions/RatioSelectionRect.tsx, packages/lib/src/interactions/SelectToZoom.tsx, packages/lib/src/interactions/utils.ts
=> Center ratio-respecting rectangle around drawn rectangle

apps/storybook/.storybook/preview.js, apps/storybook/src/Context.stories.mdx, apps/storybook/src/Selection.stories.tsx, apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts, packages/lib/src/toolbar/floating/FloatingControl.tsx, packages/lib/src/vis/heatmap/HeatmapVis.tsx, packages/lib/src/vis/shared/AxisSystemContext.tsx, packages/lib/src/vis/shared/AxisSystemProvider.tsx
Repurposed from #1065. See individual commits.
=> Misc docs improvements

packages/lib/src/interactions/Pan.tsx, packages/lib/src/interactions/SelectionTool.tsx, packages/lib/src/interactions/hooks.ts
=> Stop panning temporarily if modifier key is released

packages/lib/src/interactions/InteractionsProvider.tsx, packages/lib/src/interactions/Pan.tsx, packages/lib/src/interactions/SelectionTool.tsx, packages/lib/src/interactions/XAxisZoom.tsx, packages/lib/src/interactions/YAxisZoom.tsx, packages/lib/src/interactions/Zoom.tsx, packages/lib/src/interactions/hooks.ts, packages/lib/src/vis/shared/AxisSystemContext.tsx, packages/lib/src/vis/shared/AxisSystemProvider.tsx, packages/lib/src/vis/shared/VisCanvas.tsx
While looking at #1017, I ended up creating an `InteractionsProvider` to extract the three interaction callbacks out of `AxisSystemContext`. I also renamed `useRegisterInteraction` to `useInteraction`. Let me know what you think.
=> Interactions provider

packages/app/package.json, packages/app/src/providers/utils.ts, packages/app/src/types.d.ts, packages/app/src/vis-packs/core/scatter/MappedScatterVis.tsx, packages/h5wasm/package.json, packages/h5wasm/src/h5wasm-api.ts, packages/h5wasm/src/models.ts, packages/lib/src/interactions/utils.ts, packages/lib/src/types.d.ts, packages/shared/src/guards.ts, packages/shared/src/mock/utils.ts, pnpm-lock.yaml
- https://github.com/usnistgov/h5wasm/releases/tag/v0.3.2 - `group.get(path)` can return `null` if no entity is found at the given path
- https://github.com/axios/axios/releases/tag/v0.27.0 - new `AxiosError` class that can be used with `instanceof` to check for axios errors
=> Upgrade h5wasm and axios

packages/h5wasm/package.json, packages/h5wasm/src/h5wasm-api.ts, packages/h5wasm/src/models.ts, pnpm-lock.yaml
https://github.com/usnistgov/h5wasm/releases/tag/v0.4.0
The typing of attributes gave me a headache. See below.
=> Update h5wasm to 0.4.0

packages/lib/src/interactions/hooks.ts
=> Remove precomputation of zoom factor to avoid rounding issues

packages/h5wasm/src/h5wasm-api.ts, packages/h5wasm/src/utils.ts
Part of #1097 
Compound dtypes will have to wait for https://github.com/usnistgov/h5wasm/pull/21
=> Infer basic dtypes from metadata in h5wasm

packages/lib/src/vis/heatmap/interpolators.ts
For consistency with other Recommended interpolators
Fix #1054
=> Reverse single-hue interpolators.

packages/h5wasm/src/h5wasm-api.ts, packages/h5wasm/src/utils.ts
=> Implement slicing for h5wasm provider

packages/lib/src/vis/scatter/ScatterPoints.tsx, packages/lib/src/vis/scatter/ScatterVis.tsx
=> Fix tooltip not appearing for first point of ScatterVis

README.md
Adding the zenodo badge for giving h5web DOI
=> Add zenodo DOI badge

apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts, packages/lib/src/vis/heatmap/HeatmapVis.tsx, packages/lib/src/vis/heatmap/hooks.ts, packages/lib/src/vis/heatmap/utils.ts, packages/lib/src/vis/hooks.ts, packages/lib/src/vis/line/LineVis.tsx, packages/lib/src/vis/utils.ts
=> Add util getAxisValues in h5web/lib

.github/workflows/approve-snapshots.yml, .github/workflows/lint-test.yml, .github/workflows/release.yml, CONTRIBUTING.md, apps/demo/package.json, apps/storybook/package.json, cypress/tsconfig.json, netlify.toml, package.json, packages/app/jest.config.js, packages/app/package.json, packages/app/src/setupTests.ts, packages/h5wasm/package.json, packages/lib/package.json, pnpm-lock.yaml, tsconfig.lint.json
Lots of breaking changes: https://github.com/pnpm/pnpm/releases/tag/v7.0.0
I'll try to explain them as I go.
=> Upgrade pnpm to v7

packages/app/src/index.ts, packages/app/src/providers/mock/mock-api.ts, packages/app/src/providers/utils.ts, packages/h5wasm/package.json, packages/h5wasm/src/guards.ts, packages/h5wasm/src/h5wasm-api.ts, packages/h5wasm/src/models.ts, packages/h5wasm/src/utils.ts, packages/shared/src/guards.ts, pnpm-lock.yaml
Drafting for discussion about the value conversion
**EDIT: Now ready for review. `h5wasm` 0.4.4 brings `to_array` that handles the conversion for us**
=> Add support for bool dataset and attributes in h5wasm

apps/storybook/src/Annotation.stories.tsx, apps/storybook/src/HeatmapVisDisplay.stories.tsx, apps/storybook/src/Html.stories.tsx, apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts, packages/lib/src/vis/utils.test.ts, packages/lib/src/vis/utils.ts
Also, document the `Annotation` component in its own stories.
=> Export and document `getAxisDomain`, `useCameraState` and camera-based utilities

packages/lib/src/interactions/SelectionTool.tsx, packages/lib/src/interactions/models.ts, packages/lib/src/vis/utils.ts
To ease #1134 
See https://github.com/silx-kit/h5web/pull/1134#discussion_r895532239
=> Include world points in Selection

packages/lib/src/index.ts
=> Export MouseButton in h5web/lib

apps/storybook/src/DataCurve.stories.tsx, apps/storybook/src/ScatterVis.stories.tsx, packages/lib/src/vis/hooks.ts, packages/lib/src/vis/line/DataCurve.tsx, packages/lib/src/vis/scatter/ScatterPoints.tsx
For https://gitlab.esrf.fr/ui/daiquiri-ui/-/merge_requests/405#note_195040
=> Allow to attach a handler for clicks on the DataCurve

apps/storybook/src/LineVis.stories.tsx, apps/storybook/src/Utilities.stories.mdx, packages/lib/src/vis/utils.ts
=> Update storybook with auxiliary errors

packages/h5wasm/src/guards.ts, packages/h5wasm/src/h5wasm-api.ts
Fix #1178
@linupi This should fix the issue for the file you gave as example in #1158
=> Add support of int64 and fix 2d bool support in h5wasm

packages/lib/src/vis/hooks.ts, packages/lib/src/vis/line/LineVis.module.css, packages/lib/src/vis/line/LineVis.tsx, packages/lib/src/vis/models.ts
https://github.com/silx-kit/h5web/pull/1190#pullrequestreview-1103713685
=> Set line color feedback in CSS

packages/lib/src/vis/scalar/ScalarVis.module.css, packages/lib/src/vis/scalar/ScalarVis.tsx
=> Display scalar values as preformatted text

packages/app/src/explorer/EntityItem.tsx, packages/app/src/explorer/Explorer.tsx, packages/app/src/explorer/utils.ts
Last part: it fixes #1173 :tada: 
That was easier than the support of arrow keys.
=> Add support for Home/End key presses

packages/app/src/metadata-viewer/EntityInfo.tsx, packages/h5wasm/package.json, packages/h5wasm/src/guards.ts, packages/h5wasm/src/h5wasm-api.ts, packages/shared/src/models-hdf5.ts, pnpm-lock.yaml
cf. https://github.com/usnistgov/h5wasm/pull/32
=> Upgrade h5wasm and add basic support for datatypes

packages/h5wasm/src/h5wasm-api.ts
=> Show compression filters info and throw on unsupported filter with h5wasm

apps/storybook/src/TiledHeatmapMesh.stories.tsx, apps/storybook/src/VisCanvas.stories.tsx, packages/lib/src/vis/shared/Axis.tsx, packages/lib/src/vis/shared/AxisSystem.tsx, packages/lib/src/vis/shared/VisCanvas.tsx
=> Add setting to hide axes in VisCanvas

packages/app/src/vis-packs/core/rgb/RgbVisContainer.tsx, packages/app/src/vis-packs/core/visualizations.ts, packages/app/src/vis-packs/nexus/containers/NxRgbContainer.tsx, packages/app/src/visualizer/utils.ts
Given the little added value and the fact that it is not supported on browser versions we expect to support (FF<90)
=> Remove Array.at() calls

apps/storybook/src/Context.stories.mdx, apps/storybook/src/TiledHeatmapMesh.stories.tsx, apps/storybook/src/Utilities.stories.mdx, packages/lib/src/index.ts, packages/lib/src/interactions/AxialSelectToZoom.tsx, packages/lib/src/interactions/AxialSelectionTool.tsx, packages/lib/src/interactions/RatioSelectionRect.tsx, packages/lib/src/interactions/SelectToZoom.tsx, packages/lib/src/interactions/SelectionLine.tsx, packages/lib/src/interactions/SelectionRect.tsx, packages/lib/src/interactions/SelectionTool.tsx, packages/lib/src/interactions/XAxisZoom.tsx, packages/lib/src/interactions/YAxisZoom.tsx, packages/lib/src/interactions/hooks.ts, packages/lib/src/toolbar/floating/FloatingControl.tsx, packages/lib/src/vis/hooks.ts, packages/lib/src/vis/line/hooks.ts, packages/lib/src/vis/scatter/hooks.ts, packages/lib/src/vis/shared/AxisSystem.tsx, packages/lib/src/vis/shared/Overlay.tsx, packages/lib/src/vis/shared/RatioEnforcer.tsx, packages/lib/src/vis/shared/TooltipMesh.tsx, packages/lib/src/vis/shared/TooltipOverlay.tsx, packages/lib/src/vis/shared/ViewportCenterer.tsx, packages/lib/src/vis/shared/VisCanvas.tsx, packages/lib/src/vis/shared/VisCanvasProvider.tsx, packages/lib/src/vis/shared/VisMesh.tsx, packages/lib/src/vis/tiles/TiledHeatmapMesh.tsx, packages/lib/src/vis/tiles/hooks.ts, packages/lib/src/vis/utils.ts
=> Rename `AxisSystemProvider` to `VisCanvasProvider`

packages/lib/src/interactions/SelectToZoom.tsx
Fix https://gitlab.esrf.fr/ui/daiquiri-tomo/-/issues/220#note_219092
=> Prevent zooming on empty box

apps/storybook/package.json, apps/storybook/src/SurfaceVis.stories.tsx, packages/lib/src/index.ts, packages/lib/src/vis/hooks.ts, packages/lib/src/vis/scatter/ScatterPoints.tsx, packages/lib/src/vis/shared/R3FCanvas.tsx, packages/lib/src/vis/shared/VisCanvas.tsx, packages/lib/src/vis/surface/SurfaceMesh.tsx, packages/lib/src/vis/surface/SurfaceVis.module.css, packages/lib/src/vis/surface/SurfaceVis.tsx, packages/lib/src/vis/surface/hooks.ts, pnpm-lock.yaml
For https://github.com/silx-kit/h5web/issues/1292.
There is a lot of room for improvements but I thought I would ask for a review before it gets too bloated.
=> Prototype surface plot component

apps/storybook/src/VisCanvas.stories.tsx, packages/lib/src/vis/models.ts, packages/lib/src/vis/shared/Axis.tsx, packages/lib/src/vis/utils.ts
This passes through to D3 and allows domains to be extended to nice values
=> Add nice property to AxisConfig

.npmrc, cypress/e2e/app.cy.ts, packages/app/src/App.tsx, packages/app/src/EntityLoader.tsx, packages/app/src/__tests__/CorePack.test.tsx, packages/app/src/__tests__/DomainSlider.test.tsx, packages/app/src/__tests__/MetadataViewer.test.tsx, packages/app/src/__tests__/NexusPack.test.tsx, packages/app/src/__tests__/Visualizer.test.tsx, packages/app/src/dimension-mapper/SlicingSlider.tsx, packages/app/src/test-utils.tsx, packages/lib/src/toolbar/controls/DomainSlider/BoundEditor.tsx, packages/lib/src/toolbar/controls/DomainSlider/DomainSlider.tsx, packages/lib/src/toolbar/controls/DomainSlider/DomainTooltip.tsx, packages/lib/src/toolbar/controls/DomainSlider/Thumb.tsx, packages/lib/src/vis/matrix/StickyGrid.tsx
First batch of commits to bring the feature tests improvements made in the React 18 branch #1119. I've made separate commits for clarity. Another PR to come.
=> Improve feature tests

packages/app/src/__tests__/CorePack.test.tsx, packages/app/src/__tests__/DimensionMapper.test.tsx, packages/app/src/__tests__/DomainSlider.test.tsx, packages/app/src/__tests__/Explorer.test.tsx, packages/app/src/__tests__/MetadataViewer.test.tsx, packages/app/src/__tests__/NexusPack.test.tsx, packages/app/src/__tests__/VisSelector.test.tsx, packages/app/src/__tests__/Visualizer.test.tsx, packages/app/src/test-utils.tsx
Part two of bringing in test improvements from #1119
=> Render app with initial path in tests

packages/lib/src/interactions/SelectionTool.tsx
Contrary to what I said in https://github.com/silx-kit/h5web/pull/1318#discussion_r1045568583, I was able to move the "cancelled" flag into the local state of `SelectionTool` without problem. I kept a simple boolean flag, though, instead of a more complex enum/union-based state.
The goal of this change is to be able to add an `isValid` flag to the state next, to indicate whether the selection respects a minimum size threshold. I wasn't sure whether `SelectionTool` should take care of checking the validity or if that should be done by the consumer, but now I'm strongly leaning towards the first option. At first, I thought that `SelectToZoom` and `AxialSelectToZoom` would require different validity checks (i.e. `w >= min && h >= min` for `SelectToZoom`, and `axis === 'x' ? w >= min : h >= …
=> Store cancelled flag in state in `SelectionTool` in preparation for validity check

apps/storybook/src/HeatmapMesh.stories.tsx, packages/lib/src/vis/heatmap/HeatmapMaterial.tsx, packages/lib/src/vis/heatmap/HeatmapMesh.tsx
=> HeatmapMaterial NaN color can be configured and now keep colors for Infinity

apps/demo/src/styles.css, packages/app/src/App.module.css, packages/app/src/App.tsx, packages/app/src/Sidebar.module.css, packages/app/src/Sidebar.tsx, packages/app/src/explorer/EntityItem.tsx, packages/app/src/explorer/Explorer.tsx, packages/app/src/search/Search.module.css, packages/app/src/search/Search.tsx, packages/app/src/search/SearchContainer.tsx, packages/app/src/search/SearchEntry.tsx
Fix #1348 
[Screencast from 21-03-2023 17:00:24.webm](https://user-images.githubusercontent.com/42204205/226667755-a74d3820-f15a-4e3a-9694-3536218cdf89.webm)
=> Add search feature in the explorer

packages/app/src/App.tsx
Oversight when refactoring #1391
=> Fix sidebar area CSS

apps/storybook/src/HeatmapVis.stories.tsx
=> Fix HeatmapVis story with aspect equal

packages/app/README.md, packages/app/src/App.tsx
=> Remove deprecated prop `explorerOpen` from `App`

packages/lib/src/index.ts
Left over required export from our domain configuration dialog
=> Export color map option

packages/lib/src/index.ts
This allows for an external implementation of a multiclick selection tool
=> Export bits from interactions

.github/workflows/lint-test.yml, apps/demo/package.json, apps/demo/vite.config.js, apps/storybook/package.json, cypress/index.d.ts, package.json, packages/shared/package.json, pnpm-lock.yaml
Following the set-up of a monorepo based on H5Web's, I've identified a couple of opportunities to tweak things a bit.
=> Minor monorepo tweaks

apps/storybook/src/Context.mdx, apps/storybook/src/Html.stories.tsx, packages/lib/src/interactions/hooks.ts, packages/lib/src/vis/shared/AxisSystem.tsx, packages/lib/src/vis/shared/Html.tsx, packages/lib/src/vis/shared/VisCanvas.module.css, packages/lib/src/vis/shared/VisCanvas.tsx, packages/lib/src/vis/shared/VisCanvasProvider.tsx
=> Inject `visCanvas` through context and rename `canvasWrapper` to `canvasArea`

packages/lib/src/interactions/hooks.ts
Small bug fix for `useDrag`: the start point has to be stored in data space for the delta to remain correct throughout the drag, even if the user zooms in/out while dragging.
Notice that, as the user zooms in, the cursor moves slightly away from the reference point (i.e. the point to which the delta is applied) -- in this case, the center of the disc. The fix for this would be to take into account the offset between the pointer and the reference point when the drag starts, but this feels overly complicated for `useDrag` to handle internally (since it requires `useDrag` to be aware of this reference point).
=> [useDrag] Make dragging stable while zooming

apps/demo/package.json, apps/demo/vite.config.js, apps/storybook/package.json, packages/app/jest.config.js, packages/app/package.json, packages/lib/jest.config.js, packages/lib/package.json, packages/lib/src/vis/heatmap/HeatmapMaterial.tsx, packages/lib/src/vis/heatmap/HeatmapMesh.tsx, packages/lib/src/vis/heatmap/utils.ts, packages/lib/src/vis/tiles/Tile.tsx, packages/shared/jest.config.js, pnpm-lock.yaml
- https://github.com/mrdoob/three.js/releases
- https://github.com/mrdoob/three.js/wiki/Migration-Guide
=> Upgrade Three.js

CONTRIBUTING.md
Mostly taken from https://github.com/silx-kit/h5web/discussions/1334#discussioncomment-4589453.
=> Document local testing with `pnpm pack`

.github/workflows/approve-snapshots.yml, .github/workflows/deploy-storybook.yml, .github/workflows/lint-test.yml, .github/workflows/publish-packages.yml, .npmrc, CONTRIBUTING.md, package.json, pnpm-lock.yaml
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
=> Upgrade pnpm to v9

packages/lib/src/vis/raw/RawVis.tsx
=> Disable dark mode on raw JPEG/PNG images

packages/lib/src/interactions/SelectionTool.tsx
=> Start selection on `pointerdown`

.npmrc, apps/demo/package.json, apps/storybook/package.json, eslint.shared.cjs, package.json, packages/app/package.json, packages/h5wasm/package.json, packages/lib/package.json, packages/lib/src/interactions/models.ts, packages/lib/src/toolbar/controls/FlipYAxisToggler.tsx, packages/lib/src/toolbar/controls/GridToggler.tsx, packages/lib/src/vis/models.ts, packages/shared/package.json, packages/shared/src/hdf5-models.ts, packages/shared/src/vis-models.ts, pnpm-lock.yaml, tsconfig.json
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/
=> Upgrade TypeScript to 5.4

packages/lib/src/vis/shared/R3FCanvas.tsx
Thanks for the report @PeterC-DLS 
Fix #1685
=> Customize frustrum only when using orthographic camera

apps/storybook/src/Customization.mdx, packages/lib/src/toolbar/OverflowMenu.module.css
=> Allow customising alignment of controls in overflow menu

packages/app/src/dim-mapping-store.tsx
I came across this article on the week-end: https://tkdodo.eu/blog/deriving-client-state-from-server-state — turns out that this trick can be applied to our dimension mapping state.
In order to remember the dimension mapping state (e.g. when switching between _Inspect_ and _Visualize_, or when selecting another dataset with the same dimensions and the visualization stays the same), we hold it in a zustand store. 
When comes the time to initialise a new mapping state in `useDimMappingState`, we first check if the new mapping is compatible with the previous mapping in the store (same dims, etc.) If it is, we return the mapping from the store; otherwise it is "stale" so we return the new mapping and reset the store via a `useEffect`.
The `useEffect` triggers an extra render, which, as it …
=> Remember better the last known dimension mapping state

packages/app/src/vis-packs/core/line/LineToolbar.tsx, packages/app/src/vis-packs/core/line/MappedLineVis.tsx, packages/app/src/vis-packs/core/line/config.tsx, packages/lib/src/index.ts, packages/lib/src/vis/line/DataCurve.tsx, packages/lib/src/vis/line/Line.tsx, packages/lib/src/vis/line/LineVis.tsx, packages/lib/src/vis/line/models.ts
Early step for the new line aspect selector
=> Replace pieceWiseConstant bool by Interpolation enum
